### ISSUE TITLE
Unexpected result when I try to format code.

### ISSUE THREAD

**Issue by da2018** [intellij-rust/intellij-rust#2559] opened 2018-05-30 07:57 UTC
```
use api::config::Config;

// ...
#[cfg(test)]
mod tests {
    use api::config::Config;
    use api::client::Client;
    use api::error::Error;
}
```

changes to 
```
use api::config::Config;
use api::config::Config;
use api::client::Client;
 use api::error::Error;
// ...
#[cfg(test)]
mod tests {
}
```

Is this a bug?

**Comment by Undin** [comment] 2018-05-30 08:13
Yes, it's a bug
But looks like it was fixed in #2521 and landed in the latest release
What version of plugin do you use?

**Comment by da2018** [comment] 2018-05-30 09:37
version 0.2.0.2094-173

**Comment by Undin** [comment] 2018-05-30 10:38
Unfortunately, we don't support 2017.3 IDEs anymore and this bug was fixed only for 2018.1 and above
To get the latest plugin version, please, update your IDE to 2018.1

**Comment by Undin** [comment] 2018-05-30 10:39
Duplicate of #2519

**Comment by da2018** [comment] 2018-05-30 10:39
Got it.

**Closed by Undin** 2018-05-30 10:39 UTC
Labels: bug, code insight
