### ISSUE TITLE
Error with array reference match

### ISSUE THREAD

**Issue by yoav-steinberg** [intellij-rust/intellij-rust#6073] opened 2020-09-06 06:28 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.129.3308-202
* **Rust toolchain version:** 1.45.2 (d3fb005a3 2020-07-31) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.2.1 (CL-202.6948.80)
* **Operating system:** Linux 5.4.0-45-generic

## Problem description
Fails to correctly analyze array referece `match` in following case. See attached image.

## Steps to reproduce

```rust
fn main() -> Result<(), ()> {
    let x = [1, 2, 3];
    let y: &[i32] = &x;

    match y {
        [1] => {
            println!("1");
            Ok(())
        }
        [2] => { // Problem is here
            println!("2");
            Ok(())
        }
        [1, 2, 3] => {
            println!("got it!");
            Ok(())
        }
        _ => {
            println!("Yes!");
            Ok(())
        }
    }
}
```
![image](https://user-images.githubusercontent.com/1160578/92319616-05cc0600-f023-11ea-8231-af2f8a124009.png)

**Comment by Undin** [comment] 2020-09-06 06:33
Duplicate of #5786

**Closed by Undin** 2020-09-06 06:33 UTC
Labels: bug, rust
