### ISSUE TITLE
Allow running external tools with a different toolchain

### ISSUE THREAD

**Issue by afetisov** [intellij-rust/intellij-rust#10093] opened 2023-02-07 12:38 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.188.5178-223-nightly
* **Rust toolchain version:** 1.67.0 (fc594f156 2023-01-24) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.3.2 (CL-223.8617.54)
* **Operating system:** Linux 5.4.0-137-generic
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.macros.proc

## Problem description

It is sometimes desirable to run external tools (Clippy, cargo check, rustfmt etc) with a different toolchain than the one used by the compiler. For example, one would generally stick to the `stable` channel for the compiler, but may use a `nightly` rustfmt because it can use unstable formatting options, or `nightly` Clippy because it has a different set of lints.

Case in point: in Rust 1.67 the Clippy lint `uninlined_format_args` is enabled by default in the `clippy::style` category. This lint is obnoxious, and the inlined format args syntax isn't properly supported in the IDE. On `nightly` it was moved to a `clippy::pedantic` category and allowed by default, but the IDE runs Clippy on the default (stable) toolchain, producing numerous annoying warnings.

However, AFAIK it's impossible to tell IDE to use nightly Clippy. There is an "Additional arguments" option, but setting it to `+nightly` silently disables the linter. As I understand it, additional options are passed at the end, and the toolchain selection option is invalid at that point.

It should be possible to select either `<default>` or separate toolchains in `Rustfmt` and `External linters` menus.

Note that, besides the `default, stable, beta, nightly` options, there should also be an option to specify a custom toolchain (e.g. a different stable or a specific nightly version).

**Comment by Undin** [comment] 2023-02-14 10:41
I think it's a duplicate of #8884

**Closed by Undin** 2023-02-14 10:41 UTC
Labels: subsystem::tools, feature
