### ISSUE TITLE
can not infer rayon library

### ISSUE THREAD

**Issue by Silentdoer** [intellij-rust/intellij-rust#5977] opened 2020-08-22 09:34 UTC
like title

**Comment by vlad20012** [comment] 2020-08-28 19:41
Hello! Could you please attach a code snipped you're experiencing problems with? Screenshots could help too.

**Comment by Silentdoer** [comment] 2020-08-29 08:42
![Uploading image.png…]()
like the picture, can infer iter(), but can not infer rayon's par_iter() and par_iter().sum()|find()|filter_map() ...

**Comment by Silentdoer** [comment] 2020-08-29 08:43
![par_iter](https://user-images.githubusercontent.com/30740234/91632911-c2680b00-ea16-11ea-9503-c38e9a02a077.PNG)
infer picture

**Comment by Undin** [comment] 2020-08-29 08:49
Looks like it's duplicate of #4475

**Comment by Undin** [comment] 2020-12-21 14:16
Duplicate of #4475

**Closed by Undin** 2020-12-21 14:16 UTC
Labels: bug, subsystem::type inference & name resolution
