### ISSUE TITLE
Incorrect type inference

### ISSUE THREAD

**Issue by ice1000** [intellij-rust/intellij-rust#2776] opened 2018-08-15 22:37 UTC
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2103-182
* **Rust toolchain version:** 1.29.0 (nightly-2018-07-18-x86_64-unknown-linux-gnu)
* **IDE name and version:** CLion 182.4129.15
* **Operating system:** Ubuntu Linux 16.04

## Problem description

![image](https://user-images.githubusercontent.com/16398479/44176902-b15f3200-a0b9-11e8-98a0-ebfd0e32bb6d.png)

## Steps to reproduce

Write

```rust
let a: u32 = 233;
u64::from(a);
```

or even simpler:
```rust
u64::from(0u32);
```

**Comment by Undin** [comment] 2018-08-23 15:08
Duplicate of #2713

**Closed by Undin** 2018-08-23 15:08 UTC
Labels: bug, type inference & resolve
