### ISSUE TITLE
Support error-chain

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#2095] opened 2017-12-03 09:44 UTC
Code compiles, but there are errors in the editor:

![image](https://user-images.githubusercontent.com/873919/33524120-a84d5fa8-d827-11e7-97f6-b9644a7581e2.png)

**Comment by IntrepidPig** [comment] 2017-12-04 04:05
This is because in the plugins current state it's not capable of macro expansion. Right now it only handles the ones included in the standard library as special cases. It seems to be in progress though, as there are files in the source tree that seem to work with macros.

**Comment by tarcieri** [comment] 2017-12-15 17:38
This is a duplicate of #1243

**Comment by vlad20012** [comment] 2018-04-06 22:31
Fixed with #2331

**Closed by vlad20012** 2018-04-06 22:31 UTC
Labels: feature, macros
