### ISSUE TITLE
No autocompletion for Rayon par_iter methods

### ISSUE THREAD

**Issue by AqlaSolutions** [intellij-rust/intellij-rust#6537] opened 2020-12-21 13:55 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.136.3514-203
* **Rust toolchain version:** 1.45.2 (d3fb005a3 2020-07-31) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2020.3 Community Edition (IC-203.5981.155)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description

IntelliSense list after `par_iter().` doesn't have `map`, `collect` and other methods in it even though code is successfully compiled.

Also navigating to definition of manually typed methods like `map` is not possible.

## Example
Add rayon dependency to the cargo.toml.

```rust
use rayon::prelude::*;
fn main() {
    let v = vec![1,2,3];
    let x = v.par_iter()./*cursor here*/map(|x| 1);

}

```

**Comment by Undin** [comment] 2020-12-21 14:16
Duplicate of #4475

**Closed by Undin** 2020-12-21 14:16 UTC
Labels: bug, subsystem::type inference & name resolution
