### ISSUE TITLE
Some types aren't recognized

### ISSUE THREAD

**Issue by DevAlone** [intellij-rust/intellij-rust#6210] opened 2020-10-06 19:30 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.132.3395-202
* **Rust toolchain version:** 1.46.0
* **IDE name and version:** Clion 2020.2.3
* **Operating system:** Fedora

## Problem description

Some types aren't recognized by IDE and there's no autocompletion, for example `Window` in orbtk:

```rust
use orbtk::prelude::*;

fn main() {
      Application::new()
        .window(|ctx| {
            Window::new()
                .title("OrbTk - minimal example")
                .position((100.0, 100.0))
                .size(420.0, 730.0)
                .child(TextBlock::new().text("OrbTk").build(ctx))
                .build(ctx)
        })
        .run();
}
```

## Steps to reproduce

Use the code above in the new project with dependency `orbtk = "0.3.1-alpha3"`

**Comment by Undin** [comment] 2020-10-07 08:29
Duplicate of #5146

**Closed by Undin** 2020-10-07 08:29 UTC
Labels: bug, subsystem::type inference & name resolution
