### ISSUE TITLE
Unresolved reference in use statement

### ISSUE THREAD

**Issue by moxaj** [intellij-rust/intellij-rust#4344] opened 2019-09-02 12:25 UTC
## Environment
* **IntelliJ Rust plugin version:**
0.2.104.2132-192
* **Rust toolchain version:**
rustc 1.39.0-nightly (dfd43f0fd 2019-09-01)
* **IDE name and version:**
Ultimate 2019.2.1
* **Operating system:**
Windows 10 Pro 1903

## Problem description
^ title

Might be related to `async_trait::async_trait` being a `proc_macro_attribute`?

## Steps to reproduce
1. Add `async-trait = "0.1.11"` to your `[dependencies]`
2. `use async_trait::async_trait;`

__Expected:__ `async_trait::async_trait` resolved
__Actual:__ `async_trait::async_trait` is unresolved
![image](https://user-images.githubusercontent.com/7839686/64113962-01279e80-cd8c-11e9-8f62-911865d29985.png)

**Comment by fan-tom** [comment] 2019-09-03 19:40
I belive it is the same issue as #4186

**Comment by Undin** [comment] 2020-01-09 01:46
Duplicate of #4509

**Closed by Undin** 2020-01-09 01:46 UTC
Labels: bug, type inference & resolve
