### ISSUE TITLE
Functions with same name but different cfg break analysis.

### ISSUE THREAD

**Issue by 27factorial** [intellij-rust/intellij-rust#4384] opened 2019-09-12 22:40 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.106.2735-192-nightly
* **Rust toolchain version:**  rustc 1.39.0-nightly (f0b58fcf0 2019-09-11)
* **IDE name and version:** CLion 2019.2.2
* **Operating system:** Windows 10 (nightly-x86_64-pc-windows-gnu)

## Problem description

When two functions of the same name are created under different configurations, the plugin detects that the function has already been declared in this module, while the project compiles fine. This also happens with the latest non-nightly version of the intellij-rust plugin.

## Steps to reproduce

Use the latest version of the plugin (nightly or non-nightly), create a new cargo binary project, paste this gist into `main.rs`:
https://gist.github.com/27factorial/996c37e255ce778195cbb70ac17fccab
The plugin gives the error "A value named `intellij_test` has already been defined in this module".

**Comment by Undin** [comment] 2019-09-16 21:54
Duplicate of #1191

**Closed by Undin** 2019-09-16 21:54 UTC
Labels: cfg, duplicate
