### ISSUE TITLE
mismatched types [E0308]

### ISSUE THREAD

**Issue by mah-sim** [intellij-rust/intellij-rust#4594] opened 2019-11-04 16:41 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.109.2149-192
* **Rust toolchain version:** 1.40.0-nightly (10a52c25c 2019-10-24) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2019.2.4 Ultimate Edition (IU-192.7142.36)
* **Operating system:** Windows 10 10.0

## Problem description
Code marked as error, but can be compiled.
![mismatched-types](https://user-images.githubusercontent.com/56928799/68139370-aef12e00-ff32-11e9-93db-afd5c8545c91.png)

## Steps to reproduce
```rust
fn main() {
    assert!("ONE".to_lowercase() == "one");
}

```

**Comment by Undin** [comment] 2019-11-05 06:23
Duplicate of #4224
Try to enable new experimental macro engine - it should fix your issue. See #3628 for more details

**Closed by Undin** 2019-11-05 06:23 UTC
Labels: bug, type inference & resolve
