### ISSUE TITLE
Importing macro from equally named crate breaks lint

### ISSUE THREAD

**Issue by ssankko** [intellij-rust/intellij-rust#4786] opened 2019-12-26 04:50 UTC
## Environment

IntelliJ Rust plugin version: 0.2.112.2153-192
Rust toolchain version:  1.39.0 
IDE name and version: Jetbrains Rider 2019.2.3
Operating system: Win10

## Problem description
Looks like if i import macro `bson` from a crate named `bson`, linter breaks.

![image](https://user-images.githubusercontent.com/20635035/71458357-2aae7f00-27ee-11ea-9795-498b60f01054.png)

Without macro everything works.

![image](https://user-images.githubusercontent.com/20635035/71458389-49ad1100-27ee-11ea-8c18-ebcef5f8ff12.png)

It compiles though.

## Steps to reproduce
Create new project, add `bson = "0.14.0"` to dependencies and reproduce code from screenshot above.

**Comment by fan-tom** [comment] 2020-01-08 11:47
I believe it's the same issue as #4186

**Comment by Undin** [comment] 2020-01-09 01:40
Duplicate of #4509

**Closed by Undin** 2020-01-09 01:40 UTC
Labels: bug, type inference & resolve

**Comment by Undin** [comment] 2020-01-09 01:45
@fan-tom Thanks!
