### ISSUE TITLE
Invalid never used warning

### ISSUE THREAD

**Issue by gleb-chipiga** [intellij-rust/intellij-rust#8654] opened 2022-03-10 13:35 UTC
## Environment

* **IntelliJ Rust plugin version: 0.4.166.4486-213**
* **Rust toolchain version: 1.59.0 (49d8809dc 2022-02-10) stable-x86_64-unknown-linux-gnu**
* **IDE name and version: PyCharm 2021.3.2 (Community Edition)**
* **Operating system: Kubuntu 21.10**

## Problem description
Get invalid never used warning when using captured identifiers in format strings.

## Steps to reproduce

``` rust
fn main() {
    let username = "Bob";

    println!("Hello, {username}!");
}
```

Get warning ```Variable `username` is never used```.

**Comment by Undin** [comment] 2022-03-10 18:10
Duplicate of #8417

**Closed by Undin** 2022-03-10 18:10 UTC
Labels: bug, subsystem::highlighting
