### ISSUE TITLE
Changing return type imports unused types

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#7151] opened 2021-04-20 15:29 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.145.3797-211
* **Rust toolchain version:** 1.53.0-nightly (16bf626a3 2021-04-14) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.1 (CL-211.6693.114)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

When changing return type of a fn with the "change signature" function, unneeded imports are added with defaulted generic types.

## Steps to reproduce

```
fn foo() -> Result<Option<i8>, i8> {
    todo!()
}
```

Use the "change signature" function on the fn above and change the return type to `Vec<i8>`. The signature will be changed, but an unneeded `use std::alloc::Global;` will be also added.

**Comment by Kobzol** [comment] 2021-04-20 16:49
This has already been fixed, the fix will be available in the next release (next week). You can use the nightly version if you want to test it out right now.

Closing as a duplicate of https://github.com/intellij-rust/intellij-rust/issues/7077.

**Closed by Kobzol** 2021-04-20 16:49 UTC
