### ISSUE TITLE
Good code red when using globals initialized by lazy_static! inside of a function

### ISSUE THREAD

**Issue by pkolaczk** [intellij-rust/intellij-rust#8606] opened 2022-02-25 10:00 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.165.4438-213
* **Rust toolchain version:** 1.58.1, 1.60.beta1
* **IDE name and version:** IntelliJ IDEA 2021.3.2 (Community Edition)
* **Operating system:** Ubuntu 21.10

Macro expansion set to "Use new engine"

## Problem description

The plugin reports a type-mismatch when using a static variable declared through a lazy_static! macro inside a function.
Moving the lazy_static! block to the top level (so it is not nested in a function) fixes the problem and the types suddenly match properly.

## Steps to reproduce

```rust
pub trait ReportReader {
    fn read_header(&mut self) -> io::Result<ReportHeader>;
}

struct TextReportReader<R: BufRead> { ... }

impl<R: BufRead> TextReportReader<R> {
   fn read_extract(&mut self, regex: &Regex, msg: &str) -> io::Result<Vec<String>> { ... }
}

impl<R: BufRead + Send + 'static> ReportReader for TextReportReader<R> {

    fn read_header(&mut self) -> io::Result<ReportHeader> {
        lazy_static! {
            static ref VERSION_RE: Regex = Regex::new(r"^# ([0-9]+\.[0-9]+\.[0-9]+)").unwrap();
        }

        let version = self.read_extract(&VERSION_RE, "Malformed version value")?
       //  &VERSION_RE underlined red: mismatched types [E0308] expected `&Regex`, found `&VERSION_RE` 
```

However,  this code typechecks properly:
```rust
lazy_static! {
    static ref VERSION_RE: Regex = Regex::new(r"^# ([0-9]+\.[0-9]+\.[0-9]+)").unwrap();
}

impl<R: BufRead + Send + 'static> ReportReader for TextReportReader<R> {

    fn read_header(&mut self) -> io::Result<ReportHeader> { 
        let version = self.read_extract(&VERSION_RE, "Malformed version value")?
```

**Comment by dima74** [comment] 2022-07-22 23:54
Minimal reproduction

```rust
use lazy_static::lazy_static;
use regex::Regex;

fn main() {
    lazy_static! { static ref FOO: Regex = Regex::new("x").unwrap(); }
    func(&FOO);
}

fn func(_: &Regex) {}
```

**Comment by dima74** [comment] 2022-10-10 18:31
Duplicate of #8223

**Closed by dima74** 2022-10-10 18:31 UTC
Labels: bug, subsystem::macros, subsystem::highlighting
