### ISSUE TITLE
Plugin does not use the right cfg attribs when checking code

### ISSUE THREAD

**Issue by tobia** [intellij-rust/intellij-rust#3430] opened 2019-02-21 17:58 UTC
## Environment

* **Intellij-Rust plugin version:** v0.2.92.2116-183
* **Rust toolchain version:** 1.32.0 (8610973aa 2019-01-02)
* **IDE name and version:** IntelliJ IDEA 2018.3.4
* **Operating system:** GNU/Linux x86_64 (Ubuntu 18.04.2)

## Problem description

Trying to implement the [Layout](https://github.com/maps4print/azul/blob/a7d953d7b623d793c0b280f381c7a1cecf100bb6/azul/src/traits.rs#L11) trait from Azul, the plugin gives a E0050 error, claiming that the declaration in trait Layout has 0 parameters. The plugin is clearly reading the `#[cfg(test)]` declaration, instead of the `#[cfg(not(test))]` one, even though the code being compiled is not a test.

```
pub trait Layout {
    #[cfg(not(test))]
    fn layout(&self, window_id: LayoutInfo<Self>) -> Dom<Self> where Self: Sized;
    #[cfg(test)]
    fn layout(&self) -> Dom<Self> where Self: Sized;
}
```

## Steps to reproduce

Setup a new project with the [Azul dependencies](https://github.com/maps4print/azul/wiki/Installation) and copy & paste the [sample Hello World code](https://github.com/maps4print/azul/wiki/Getting-Started#hello-world).

Cargo will have no issues with the code, while the plugin flags the aforementioned error.

**Comment by mchernyavsky** [comment] 2019-02-24 14:05
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/1191.
Will be fixed in https://github.com/intellij-rust/intellij-rust/pull/2166.

**Closed by mchernyavsky** 2019-02-24 14:05 UTC
Labels: duplicate, type inference & resolve
