### ISSUE TITLE
No code navigation or autocompletion with OrbTk library

### ISSUE THREAD

**Issue by XakepSDK** [intellij-rust/intellij-rust#5146] opened 2020-03-28 22:38 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.118.2171-193
* **Rust toolchain version:** 1.44.0-nightly (75208942f 2020-03-27)
* **IDE name and version:** 2019.3.4 CL-193.6494.38
* **Operating system:** Arch Linux

## Problem description
Plugin does not work properly with OrbTk, no code navigation or autocompletion
https://github.com/redox-os/orbtk
You can compile and start application from IDE, it works properly.

## Steps to reproduce
1. Add dependency
`orbtk = { git = "https://github.com/redox-os/orbtk.git", branch = "develop" }`
2. Put this example in `main.rs`
```rust
use orbtk::prelude::*;

fn main() {
    // use this only if you want to run it as web application.
    // orbtk::initialize();

    Application::new()
        .window(|ctx| {
            Window::create()
                .title("OrbTk - minimal example")
                .position((100.0, 100.0))
                .size(420.0, 730.0)
                .borderless(false)
                .child(TextBox::create().text("OrbTk").margin(4.0).build(ctx))
                .build(ctx)
        })
        .run();
}
```
3. Code completion or navigation does not work
3.1. Try to Ctrl+LMB on `::new()`, it does not work
3.2. Try to Ctrl+LMB on `.window(...)`, it does not work
3.3. etc

**Comment by DevAlone** [comment] 2020-10-07 10:04
Is there any update since March?

**Comment by vlad20012** [comment] 2020-10-07 11:11
Will be fixed with the name resolution 2.0 ([resolve-new branch](https://github.com/intellij-rust/intellij-rust/tree/diralik/resolve-new))

**Comment by vlad20012** [comment] 2020-12-12 08:46
You can try the new name resolution engine using `Use experimental name resolution engine` option in `Settings / Preferences | Languages & Frameworks | Rust settings`. It should fix the issue (but may introduce some new issues because of the experimental status of the new engine)

**Comment by qarmin** [comment] 2020-12-12 08:50
Yup, I can confirm that this is fixed when enabling this feature

**Closed** 2021-04-28 12:27 UTC
Labels: bug, name resolution 2.0, subsystem::type inference & name resolution
