### ISSUE TITLE
Build button greyed out and Ctrl-F9 no longer works

### ISSUE THREAD

**Issue by foxcob** [intellij-rust/intellij-rust#6761] opened 2021-01-30 17:57 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.139.3615-203
* **Rust toolchain version:** 1.51.0-nightly (b12290861 2021-01-29) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Linux 5.8.0-7630-generic
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
Since latest update, the "build" button and Ctrl-F9 no longer work for Rust projects.  The "run" and "debug" buttons as well as their shortcuts continue to work correctly.  This behavior is consistent across every Rust project I have opened.

## Steps to reproduce
1. Open rust project
2. Attempt to build (no longer possible)

**Comment by Undin** [comment] 2021-01-30 18:09
Duplicate of #6752
The fix will be in the next stable release next week. Or you can try the latest nightly build. See https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly how to install it

**Closed by Undin** 2021-01-30 18:09 UTC
Labels: bug, subsystem::IDE
