### ISSUE TITLE
Wrong type inferrence: the return value of `clone()` is inferred to `&mut T`, when `&mut T` is passed to it.

### ISSUE THREAD

**Issue by xxchan** [intellij-rust/intellij-rust#5884] opened 2020-08-07 15:22 UTC
## Environment

* **IntelliJ Rust plugin version: 0.3.127.3249-202**
* **Rust toolchain version: nightly-2020-06-04**
* **IDE name and version: IDEA 2020.2**
* **Operating system: macOS**

## Problem description

```rust
#[derive(Clone)]
struct T {}

impl T {
    fn foo(&self) -> Self {
        T {}
    }
}

trait Trait {
    fn bar(&self) -> Self;
}

impl Trait for T {
    fn bar(&self) -> Self {
        T {}
    }
}

fn bar() {
    let t = &mut T {};
    let t1 = t.foo();
    let t2 = t.bar();
    let t3 = t.clone();
}
```
![image](https://user-images.githubusercontent.com/37948597/89660995-b64fc880-d904-11ea-9a4d-988e6ba7e353.png)

**Comment by Undin** [comment] 2020-08-07 19:45
Fixed in #5824
Duplicate of #5575
The fix is already in nightly builds (see [instruction](https://intellij-rust.github.io/install#nightly-builds) how to use nightly builds) and it will be landed in next stable build next week

**Closed by Undin** 2020-08-07 19:45 UTC
Labels: bug, subsystem::type inference & name resolution
