### ISSUE TITLE
Rust plugin suggests `methods` from unreachable dependencies

### ISSUE THREAD

**Issue by hardskulls** [intellij-rust/intellij-rust#9892] opened 2022-12-12 18:08 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.184.5057-223
* **Rust toolchain version:** 1.65.0 (897e37553 2022-11-02) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2022.3 Community Edition (IC-223.7571.182)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled

## Problem description
Rust plugin shows methods from dependencies that are unreacheble.
If project has dependency `A` which includes dependency `B`, which is not present in `Cargo.toml` methods from `B` pop up anyway.
The result is total chaos.

## Steps to reproduce
Bug works with different crates.
For example, add `teloxide` crate and  methods from `itertools` will pop up in code completion.
It happens because `teloxide` -> `aquamarine` -> `itertools`.

![Снимок экрана (601)](https://user-images.githubusercontent.com/105431697/207120783-492b29b3-628d-4986-b710-3e8d2a8115ca.png)

**Comment by dima74** [comment] 2022-12-13 16:08
Duplicate of #9634

**Closed by dima74** 2022-12-13 16:08 UTC
