### ISSUE TITLE
Run Cargo Command: Default to running in Module

### ISSUE THREAD

**Issue by deaddowney** [intellij-rust/intellij-rust#715] opened 2016-10-06 13:19 UTC
I have a multi-module project.  When I try to run a Cargo command, it just picks the first module, not the module that the source exists in, so I need to change the value, either by creating a Run configuration, or by changing the default.  It should by default run the command in the module the source resides in.

**Comment by matklad** [comment] 2016-10-06 14:05
Do you have several Rust modules? Can you use a single module together with [workspaces](http://doc.crates.io/manifest.html#the-workspace-section)?

**Comment by deaddowney** [comment] 2016-10-07 13:31
I just have one rust module, but other (Java) modules defined.  It attempts to use the Java module to run cargo unless I go in and switch it.  It's not a dealbreaker, just something that could be improved.

**Comment by matklad** [comment] 2016-10-07 13:32
This is most definitely a bug then, thanks!

**Comment by matklad** [comment] 2016-10-13 11:19
I think this should be fixed by https://github.com/intellij-rust/intellij-rust/commit/a7e73f0df1c0653e5ce372c331e4d98681221988. 


I was unable to reproduce this exactly, because for me Rust module is selected, although it is possible to select a non-rust module as well. This commit allows selecting only Rust module.

**Closed by matklad** 2016-10-13 11:19 UTC
