### ISSUE TITLE
Can't collapse commented out code blocks

### ISSUE THREAD

**Issue by gusutabopb** [intellij-rust/intellij-rust#9784] opened 2022-11-22 03:49 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.183.5026-222
* **Rust toolchain version:** rustc 1.65.0 (897e37553 2022-11-02)
* **IDE name and version:** CLion 2022.2.4 (Build #CL-222.4345.21)
* **Operating system:** macOs Version 13.0 (22A380)

## Problem description

It's not possible to collapse commented out code blocks (including functions) when using single line comments. This is possible in other languages/Jetbrains IDEs. For languages that have multiple types of comments (single line and block), both types of comments preserve the expand/collapse functionality.

## Steps to reproduce

Example using CLion.

Original code. Notice how the `loop`/`while` block can both be expanded/collapsed:

<img width="510" alt="Screenshot 2022-11-22 at 12 15 25" src="https://user-images.githubusercontent.com/4231387/203213359-dbdf67b7-d2ba-4462-b593-32bc88f3cdd0.png">

Commenting out the `loop`/`while` blocks. In Python, the block can still be collapsed, but not in Rust.

<img width="510" alt="Screenshot 2022-11-22 at 12 15 49" src="https://user-images.githubusercontent.com/4231387/203213357-78937bfe-dd88-46e7-b767-a30a39183250.png">

Collapsed commented block in Python. Not possible in Rust.

<img width="510" alt="Screenshot 2022-11-22 at 12 15 57" src="https://user-images.githubusercontent.com/4231387/203213415-fb6a0753-e6d3-40e5-ad2b-87c8019ac2c4.png">

It is possible to collapse comments in Rust only if using **block comments**:
<img width="280" alt="Screenshot 2022-11-22 at 12 32 53" src="https://user-images.githubusercontent.com/4231387/203215419-689fbaed-41e0-4317-ae17-40623ffbffd7.png">
<img width="280" alt="Screenshot 2022-11-22 at 12 33 01" src="https://user-images.githubusercontent.com/4231387/203215426-7a32f10b-5c67-4104-9719-a265ccd405d8.png">

But IMO it should be possible when using either single-line or block comments. That's how it works in other languages. Example using C# (Rider):
<img width="414" alt="Screenshot 2022-11-22 at 12 42 39" src="https://user-images.githubusercontent.com/4231387/203215947-9c589646-fca0-45c3-aa58-99e07c156c1e.png">
<img width="414" alt="Screenshot 2022-11-22 at 12 42 18" src="https://user-images.githubusercontent.com/4231387/203215949-ec431f63-dc7e-49bb-b5ac-fa0ae501ace6.png">

In both comment types above the expand/collapse functionality is preserved. The same should be possible with IntelliJ Rust.

**Comment by neonaot** [comment] 2022-11-22 08:56
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/9784

**Closed by neonaot** 2022-11-22 08:56 UTC

**Comment by gusutabopb** [comment] 2022-11-22 09:12
@neonaot Closing an issue as duplicate of itself?

**Comment by neonaot** [comment] 2022-11-22 09:14
Only as a duplicate, comment collapse is a useful feature.

**Comment by gusutabopb** [comment] 2022-11-22 09:20
@neonaot 

> Duplicate of #9784

What issue is this is issue is supposed to be a duplicate of? #9784 is this issue. It doesn't make sense to close an issue as duplicate of itself. Was this closed because it is actually a duplicate or do you mean you closed it because of something else?

**Comment by neonaot** [comment] 2022-11-22 09:22
Oh, sorry, somehow i copied a wrong link https://github.com/intellij-rust/intellij-rust/issues/9626
