### ISSUE TITLE
IntelliJ index operation won't stop

### ISSUE THREAD

**Issue by itmuckel** [intellij-rust/intellij-rust#2323] opened 2018-02-23 20:26 UTC
I just updated to intellij-rust 0.2.0.2088 and now the indexing operation won't ever finish. 

IntelliJ stops indexing, when I remove the `target` folder, but this is no solution as I need to recompile all libs from scratch. As soon es everything is compiled again, the indexing operation kicks in and never stops. Anyone else experiencing this?

I use Windows 10, but I think I witnessed the same problem on my other machine running Ubuntu.

(Downgrading to the previous version fixes this for me temporarily.)

**Comment by vlad20012** [comment] 2018-02-23 21:09
itmuckel can you please spcify the rust project in which this bug is reproduced (if it is open-source, of course)? Or the project does not matter?

**Comment by itmuckel** [comment] 2018-02-23 22:22
You're right, I tried a different project and there it worked fine. 

The problematic project is a game I write, but I cannot release the source right now, because I don't own the rights for all the assets I use. Here are the contents of my cargo.toml (without the package section):
```toml
[profile.dev]
opt-level = 2

[dependencies.ggez]
version = "0.4.0"
features = ["cargo-resource-root"]

[dependencies]
specs = "0.10"
specs-derive = "0.1"
palette = "0.2"
rand = "0.3"
time = "0.1"
```

**Comment by vlad20012** [comment] 2018-02-24 01:28
> IntelliJ stops indexing, when I remove the target folder

And try to just remove `target` folder from indexing. It should be performed automatically, but maybe something went wrong
![image](https://user-images.githubusercontent.com/3221931/36623973-0603f97a-191b-11e8-981d-b5548dc889c5.png)

**Comment by mhogrefe** [comment] 2018-02-24 03:41
I had the same issue after upgrading to the latest version of the plugin on Mac OS - in several of my projects, but not all, the target directory was un-excluded, causing indexing to take forever. Once I found this thread and realized what the problem was, it was easy to fix.

Could this be a bug in the upgrade process?

**Comment by itmuckel** [comment] 2018-02-24 08:41
Oh man, that did it! 😄  
Thanks a lot!

**Comment by JakubOnderka** [comment] 2018-02-24 16:12
I have the same problem on Windows 10 and macOS with latest plugin (0.2.0.2088) and latest PyCharm (2017.3.3)

**Comment by mhogrefe** [comment] 2018-02-24 17:43
I spoke too quickly. Marking target as included fixed one project for me, but another still had the same problem. I ultimately installed the previous version of the plugin, 0.2.0.2087, and that worked for me.

**Comment by sfleischman105** [comment] 2018-02-25 10:27
Experiencing this issue as well, and only seemed to happen when I upgraded nightly Rust. Indexing runs forever, or more so runs and then "completes", and then restarts Indexing immediately. 

I'm currently on rust version `1.26.0-nightly (28a1e4ffe 2018-02-24)`, while IntelliJ is on version `2017.3.4`.

**Comment by insanitybit** [comment] 2018-02-25 18:06
Same issue here. I've marked the target folder as excluded. I've removed caches. I've performed a complete uninstall (removing all files related that I could). I've reinstalled + the plugin. Still happens.

I see in the little indexing panel that it is looking in the target directory of a dependency. I've pulled that specific dependency in by path:

Like so:
`graph-service={path="../graph-service"}`

This is the *only* dependency I have in the entire project.

FWIW that path is itself an intellij project, if that helps. This is on Ubuntu 16.10 with the latest intellij + rust plugin.

**Comment by insanitybit** [comment] 2018-02-25 18:21
OK, I did manage to solve this... I'm not sure exactly how but it should be one of the two things I tried.

First, I updated my rust versions (rustup update). I don' thtink this helped, but I stupidly didn't check before performing what I suspect was the real fix.

*I ran `cargo clean` in the `graph-service` project directory* - as in, I went to the folder where my dependency was and I ran `cargo clean`.

Indexing has completed.

So perhaps dependencies that are linked in and contain /target/ paths are causing this error.

**Comment by golddranks** [comment] 2018-02-27 10:13
The same thing happened to me after update; it tried to index `target`, spending infinite amount of time. Manually excluding the target directory fixed the problem. Thanks!

**Closed** 2018-03-06 18:48 UTC

**Comment by zhaohansprt** [comment] 2018-03-07 07:30
I meet this issue too , the Indexing never completes  using the Feb 21, 2018 version plugin

**Comment by mithereal** [comment] 2018-08-29 19:17
this is the reason i quit supporting this company, there is no reason to do this, ide is an overbloated piece of crap, indexing would halt me from developing, on avg in an 8 hour day i would get 4-6 hours of work done. i do not pay to get my time stolen

**Comment by ortem** [comment] 2018-08-30 10:25
@mithereal  Sorry to hear that. We are working on performance. Could you please provide the configuration of your computer and your `idea.log`? Also, you can try invalidating caches (`File/Invalidate caches, Restart`).

P.S. The plugin is available for IntelliJ IDEA Community Edition, so you actually can use it for free!

**Comment by nednoodlehead** [comment] 2022-09-26 01:58
I had something similar, it was produced by making a new rust project via the GUI that Pycharm gives you, and pasting in a fair bit code (115 lines). It was solved by deleting and re-making the repo, this time waiting until all of the background stuff finishes.
