### ISSUE TITLE
Long delays when typing, Goto Definition, etc.

### ISSUE THREAD

**Issue by nathanaeljones** [intellij-rust/intellij-rust#1650] opened 2017-08-23 22:24 UTC
I'm using the latest build of intellij-rust and rust nightly 2017-06-11 on https://github.com/imazen/imageflow

Since switching to a workspace-wide module (#1506), I've seen significantly reduced performance with delays of up to 8 seconds when typing (before characters appear), up to 15 seconds for Goto definition (but can be as low as 200ms). Slow performance for certain operations on certain symbols is consistent - i.e, a 6-second goto def will remain ~6-seconds no matter how many times I do it.

I didn't see guidance on what kind of information I should gather - how can I help shed light on this kind of problem?

**Comment by matklad** [comment] 2017-08-24 09:06
A thread dump or a CPU snapshot would be useful:

https://intellij-support.jetbrains.com/hc/en-us/articles/206544899-Getting-a-thread-dump-when-IDE-hangs-and-doesn-t-respond

https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems

What version of IntelliJ Rust are you using? Am I correct that together with switching to a single module layout, you've updated to the latest IntelliJ alpha as well? 

You can try a previous version of the plugin: https://plugins.jetbrains.com/plugin/8182-rust. It should work with single module layout just fine, but it'll add the libraries to xml.

**Comment by matklad** [comment] 2017-08-24 15:24
I've looked a bit at it today, but I fail to reproduce the performance degradation unfortunately. I've used the build from the master branch of the plugin on Linux.

**Comment by Alex-PK** [comment] 2017-08-24 16:07
I am having very slow responses (5-10 seconds) on auto-complete (ctrl-space) and on syntax checking, on OSX with the latest plugin release.

I don't know if the thread dump would be useful in this case, as editing doesn't slow down, but I can try to get one if needed.

Should I open a separate issue?

**Comment by mkaput** [comment] 2017-08-24 16:24
I think this may be related to some dependencies, like win crate. I forgot to post issue, but recently I was playing with gtk-rs and had similar problems. Probably even hello world example was causing the issue

**Comment by matklad** [comment] 2017-08-25 15:53
>I don't know if the thread dump would be useful in this case, as editing doesn't slow down, but I can try to get one if needed.

The CPU snapshot would certainly help though! Could you point to the repository where it happens?

So far, I was unable to reproduce this problem locally (with imageflow), but I am optimistic that eventually I'll hit something reproducible :) 

I've pushed some perf improvements today, they'll be in the nightly and [master](https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_CurrentIdea_TestsRust/.lastSuccessful/intellij-rust-0.1.0.%7Bbuild.number%7D.zip) builds, but looks like the problem here is more like a bug, rather then general slowness...

**Comment by nathanaeljones** [comment] 2017-08-25 19:48
I discovered that these issues occur far more frequently if IntelliJ has been running for hours. Should we customize the maximum heap size?

**Comment by nathanaeljones** [comment] 2017-08-25 19:57
Also, for those on Linux, using the Toolbox: ` find ~/ -name "idea.sh" 2>/dev/null -exec sed -i 's/IS_EAP="false"/IS_EAP="true"/g' {} +` enables EAP mode for all IntelliJ IDEA instances so you can enable CPU profiling and capture memory snapshots.

**Comment by vlad20012** [comment] 2017-09-08 11:53
Is it fixed now?

**Comment by Alex-PK** [comment] 2017-09-08 12:04
My side of the problem seems fixed with the latest release. Auto-complete suggestions come up in 1-2 seconds max, now.

Thanks!

I'm not using workspaces, currently, so I can't comment on the original request.

**Closed** 2017-09-13 14:17 UTC
