### ISSUE TITLE
Syntax highlighting/code completion not working for (some) tokio modules

### ISSUE THREAD

**Issue by YenForYang** [intellij-rust/intellij-rust#4706] opened 2019-11-29 21:18 UTC
## Environment

* **IntelliJ Rust plugin version:**
0.2.110.2150-193 (also tried 192)
* **Rust toolchain version:**
1.39.0
* **IDE name and version:**
Clion 2019.3, also tested 2019.2.5
* **Operating system:**
Windows 10 Version 1909, also tested MacOS 10.14.6

## Problem description

This problem is possibly very similar to #4627 but with `tokio` instead of `async_std`...something to do with macro resolution probably.
The main reason I'm posting this is because I've found a (rather obvious) *very fragile* **unsafe** workaround to mitigate the pain of
not having proper code analysis (in CLion) temporarily. 

The issue is described best by some code:

```rust
use tokio::net::TcpStream; // 
              //  ^^^^^^ Lack of color here, can't Cmd/Ctrl-B here.

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
  let tcp = TcpStream::connect("420.4.2.0:4204").await?;
         // ^^^^^^^^^^^^^^^^^^ Unresolved reference: `TcpStream`
```

## Steps to reproduce

In `Cargo.toml`, add:

```toml
[dependencies.tokio]
version = "0.2.2"
features = [ "full" ]
```
(I added "full" to enable all possible features, just to make sure the issue isn't caused by a feature not being enabled)

## Steps to hack around

What we do here is basically trade a real eye for 2 fake ones:

From `tokio-0.2.2/src/net/mod.rs`, note lines 28-32:
```rust
cfg_tcp! {  
    pub mod tcp;  
    pub use tcp::listener::TcpListener;  
    pub use tcp::stream::TcpStream;  
}
```
Well, `cfg_tcp!` causes the issue...so I deemed it necessary to hardcode:
```rust
// cfg_tcp! {  
    pub mod tcp;  
    pub use tcp::listener::TcpListener;  
    pub use tcp::stream::TcpStream;  
// }
```

Maybe the plugin could do something like this behind the scenes as a temporary hack to get things working; just throwing out ideas because I've heard that this issue has been around for quite awhile.

**Comment by ZOXEXIVO** [comment] 2019-12-03 22:38
Same problem with 

`use async_std::net::{TcpListener, TcpStream};`

![image](https://user-images.githubusercontent.com/14014921/70095769-9f026200-1636-11ea-9c18-404338219b7a.png)

**Comment by ice1000** [comment] 2019-12-04 21:35
> IDE name and version: Rider

Missing version

**Comment by ZOXEXIVO** [comment] 2019-12-04 22:53
Latest 
![image](https://user-images.githubusercontent.com/14014921/70188571-16e98e80-1702-11ea-8574-81740f833347.png)

**Comment by Undin** [comment] 2019-12-05 07:30
@YenForYang thanks for the report and suggestion.
As stated in https://github.com/intellij-rust/intellij-rust/issues/4627#issuecomment-554634530 - we've already discussed possible solution

**Comment by sgrust01** [comment] 2019-12-15 15:10
@YenForYang Thanks for the hack.. IMHO - Learning Tokio  without IDE support for beginners like me is quite hard  :smiley: .. i was able to hack util & io too with your tip... 
Cheers :+1:

**Comment by Sherlock-Holo** [comment] 2019-12-18 16:18
clion 2019.3.1 with rust plugin 0.2.112.2148-193 has this problem too

**Comment by Kubikx** [comment] 2020-01-18 12:08
0.2.113.2150-193 still an issue :(

**Comment by lforeverhao** [comment] 2020-01-31 18:09
IntelliJ IDEA 2019.3.2 (Community Edition)

0.2.114.2151-193

Still an issue

**Comment by Undin** [comment] 2020-02-07 14:12
It's fixed in #4914 and will be landed in the next release (I hope).
I close this issue as a duplicate of #4627 because they have the same reason

**Closed by Undin** 2020-02-07 14:12 UTC
Labels: bug, subsystem:macros, subsystem:type inference & resolve

**Comment by Sherlock-Holo** [comment] 2020-02-08 03:42
@Undin is it a nightly build for use this fix？

**Comment by Undin** [comment] 2020-02-08 06:57
@Sherlock-Holo yep.
Note, it should work correctly only with new experimental macro expansion engine (see #3628)

**Comment by Sherlock-Holo** [comment] 2020-02-08 07:55
I install nightly plugin and it works well now, thanks for your job.

Arseniy Pendryak <notifications@github.com> 于2020年2月8日周六 下午2:57写道：

**Comment by shibang** [comment] 2020-04-04 06:27
The problem still exists
CLion 2019.3.5
Rust plugin: 0.2.119.2172-193

**Comment by Undin** [comment] 2020-04-04 07:09
@shibang did you enable new macro expansion engine (see #3628)?

**Comment by shibang** [comment] 2020-04-04 07:13
> @shibang did you enable new macro expansion engine (see #3628)?

It works! Thank you!

**Comment by SonicZentropy** [comment] 2020-04-16 06:09
Just chiming in to say I arrived here from Google having the same issue and the new macro expansion engine also fixed mine, excellent work guys!  Thank you so much for making such a fantastic IDE constantly better
