### ISSUE TITLE
Support debugging Rust on Windows with Visual C++ Toolchain using CLion 

### ISSUE THREAD

**Issue by smj389** [intellij-rust/intellij-rust#4618] opened 2019-11-10 21:42 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.109.2144-193
* **Rust toolchain version:** 1.40.0-nightly (2477e2493 2019-11-04) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2019.3 EAP (CL-193.5096.27)
* **Operating system:** Windows 10 10.0

**Comment by Undin** [comment] 2019-11-11 05:21
Duplicate of #4104

**Closed by Undin** 2019-11-11 05:21 UTC
Labels: debugger, duplicate, feature
