### ISSUE TITLE
Fails to parse slice match

### ISSUE THREAD

**Issue by ctron** [intellij-rust/intellij-rust#6481] opened 2020-12-04 12:55 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.136.3514-203
* **Rust toolchain version:** 1.47.0 (18bf6b4f0 2020-10-07) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3 (CL-203.5981.166)
* **Operating system:** Linux 5.9.10-200.fc33.x86_64
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description

It fails to parse slice match:

## Steps to reproduce

~~~rust
fn control_credentials(
    credentials: Vec<Credential>,
    id: &str,
) -> Result<Option<Credential>, ServiceError> {
    match credentials.as_slice() {
        [] => {
            Ok(None)
        }
        [cred] => Ok(Some(cred.clone())),
        [_, ..] => {
            Err(ServiceError::InvalidState)
        }
    }
}
~~~

Results in:

![image](https://user-images.githubusercontent.com/202474/101166290-53630980-3638-11eb-8833-d63e796dec9a.png)

While the compiles just fine.

**Comment by Undin** [comment] 2020-12-04 13:07
Duplicate of #5786

**Closed by Undin** 2020-12-04 13:07 UTC
Labels: bug, rust

**Comment by Undin** [comment] 2020-12-04 13:10
@ctron Thanks for the feedback!
As a workaround, you can add `,` after
```rust
[] => {
    Ok(None)
}
```

**Comment by ctron** [comment] 2020-12-04 16:23
Thanks for the tip. Unfortunately, that gets cleaned up right away by `rustfmt` :grinning:
