### ISSUE TITLE
Build button grayed out

### ISSUE THREAD

**Issue by mahkoh** [intellij-rust/intellij-rust#6770] opened 2021-02-01 01:05 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.139.3615-203
* **Rust toolchain version:** 1.49.0 (e1884a8e3 2020-12-29) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Linux 5.9.13-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Since updating to CLion 2020.3.2, the build button is grayed out. Ctrl-F9 has no effect. Running tests etc. works as expected. The update to CLion 2020.3.2 might have coincided with other changes but I'm not aware of any.

## Steps to reproduce

Open a project and look at the build button.

![2021-02-01-02:03:14](https://user-images.githubusercontent.com/1882250/106404087-c8cd3980-6431-11eb-9b6a-717ba8ddcb14.png)

**Comment by Undin** [comment] 2021-02-01 05:45
Duplicate of #6752
The fix will be in the next stable release this week. Or you can try the latest nightly build. See https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly how to install it

**Closed by Undin** 2021-02-01 05:45 UTC
Labels: bug, duplicate, subsystem::IDE
