### ISSUE TITLE
Not work well with tokio in clion

### ISSUE THREAD

**Issue by ufosky** [intellij-rust/intellij-rust#4903] opened 2020-01-31 12:23 UTC
I just open the tokio project and select an example file like `hello_world.rs`, it cannot find `TcpStream` in the editor, but build success with the source:
```rust
//! Hello world server.
//!
//! A simple client that opens a TCP stream, writes "hello world\n", and closes
//! the connection.
//!
//! You can test this out by running:
//!
//!     ncat -l 6142
//!
//! And then in another terminal run:
//!
//!     cargo run --example hello_world

#![warn(rust_2018_idioms)]

use tokio::io::AsyncWriteExt;
use tokio::net::TcpStream;

use std::error::Error;

#[tokio::main]
pub async fn main() -> Result<(), Box<dyn Error>> {
    // Open a TCP stream to the socket address.
    //
    // Note that this is the Tokio TcpStream, which is fully async.
    let mut stream = TcpStream::connect("127.0.0.1:6142").await?;
    println!("created stream");

    let result = stream.write(b"hello world\n").await;
    println!("wrote to stream; success={:?}", result.is_ok());

    Ok(())
}
```
![image](https://user-images.githubusercontent.com/801838/73538891-20277b00-4467-11ea-9473-cd6102ea0248.png)

I use Clion 2019.3.2 and Rust plugin 0.2.114.2151-193

**Comment by lancelote** [comment] 2020-01-31 12:26
That's probably #4706

**Comment by Undin** [comment] 2020-01-31 12:28
Duplicate of #4706

**Closed by Undin** 2020-01-31 12:28 UTC
Labels: bug, subsystem:code insight, subsystem:macros
