### ISSUE TITLE
missing autocomplete function suggestion on int checked_sub

### ISSUE THREAD

**Issue by ta32** [intellij-rust/intellij-rust#5035] opened 2020-03-01 04:37 UTC
## Environment
* **IntelliJ Rust plugin version:** 0.2.116.2163-193
* **Rust toolchain version:** 1.38.0 (625451e37 2019-09-23) x86_64-pc-windows-gnu
* **IDE name and version:** CLion 2019.3.4 (CL-193.6494.38)
* **Operating system:** Windows 10 10.0

## Problem description
missing autocomplete prompts

## Steps to reproduce
```rust
let small_mass :usize = 1;
small_mass.checked_sub(2).unwrap_or(0)
```
when .is pressed after small_mass there is no suggestion for **'checked_sub'** its not in the list. After i manually enter it there are no more suggestions - eg i had to manually enter unwrap_or

What does this plugin use for the auto-complete is it using some kind of completion service provided by the rust language or did you implement it yourself? 

Also this is not the first time this has happened, there were other examples but if forgot. Would it be possible to create a list of things that are missing instead of raising an issue for each one?

**Comment by Undin** [comment] 2020-03-01 08:38
It's because `checked_sub` method and its friends are generated by [macros](https://github.com/rust-lang/rust/blob/master/src/libcore/num/mod.rs#L4860-L4864) in stdlib.
Supporting methods generated by macros is an experimental feature right now. Try to enable experimental macro expansion engine (see #3628 for more details). It should solve your issue

> Also this is not the first time this has happened, there were other examples but if forgot. Would it be possible to create a list of things that are missing instead of raising an issue for each one?

If it's more convenient for you - welcome! But don't forget to check if an item can be resolved/completed when experimental macro engine is enabled

**Comment by Undin** [comment] 2020-03-01 08:38
Duplicate of #3087

**Closed by Undin** 2020-03-01 08:38 UTC
Labels: subsystem:macros, subsystem:type inference & resolve
