### ISSUE TITLE
Add macros into completion list

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1275] opened 2017-05-27 11:57 UTC

**Comment by farodin91** [comment] 2017-06-01 17:31
@matklad I added an `getVariants` to RsMacroReferenceImpl but i didn't get any completion. What i have to do?

**Comment by farodin91** [comment] 2017-06-01 19:28
I will change macro invocation as an extension RsPath.

**Comment by matklad** [comment] 2017-06-03 08:45
@farodin91 I am not actually sure how to implement completion for macros properly.

The problem is, macros use name resolution algorithm different from anything else in Rust, and this algorithm is IDE-hostile. rustc thinks that `macro` is defined if it was defined before, in the parsing order, but there is no such thing as parsing order in the IDE. 

As a first step, I think we can implement completion/name resolution for locally (= in this file) defined macros. To do this, we should feed macro definitions to `processor` in the `NameResolution.kt`.

The next step would be to compute for each crate the set of exportable macros defined in this crate by looping through macros in the index and checking if they are `#[macro_export]`.

**Comment by farodin91** [comment] 2017-06-03 09:15
@matklad #1314

**Comment by farodin91** [comment] 2017-06-03 10:46
Handling of macro_export would be cool to handle this with annotators or?

**Comment by farodin91** [comment] 2017-07-15 21:22
Fixed by #1467

**Closed** 2017-07-19 08:12 UTC
Labels: E-hard
