### ISSUE TITLE
'static lifetime for associated constants has unfixable spellcheck warning

### ISSUE THREAD

**Issue by seanpianka** [intellij-rust/intellij-rust#5850] opened 2020-08-01 03:03 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.127.3249-202
* **Rust toolchain version:** rustc 1.44.0-nightly (f509b26a7 2020-03-18)
* **IDE name and version:** CLion 2020.2 #CL-202
* **Operating system:** macOS Catalina 10.15.4

## Problem description
If the lifetime of an associated constant is `'static`, it's spellchecked and a warning is produced about a spelling error for "'static".

## Steps to reproduce
```rust
struct Struct;

impl Struct {
    const C: &'static str = "";
}
```

**Comment by Undin** [comment] 2020-08-01 07:40
Duplicate of #5551

**Closed by Undin** 2020-08-01 07:40 UTC
Labels: bug, subsystem::code insight
