### ISSUE TITLE
chain_error support?

### ISSUE THREAD

**Issue by avkonst** [intellij-rust/intellij-rust#2615] opened 2018-06-27 05:05 UTC
I understand that Advanced Macro Support feature has been merged to master. I use the latest published version of the plugin but chain_err still produces `<unknown>` result type. I have enabled macro expansion feature in the settings. I wonder what is not right? Asking again, because [this](https://github.com/intellij-rust/intellij-rust/pull/2331#issuecomment-391914435) was left unanswered.

**Comment by Undin** [comment] 2018-06-27 10:29
@avkonst Sorry that we missed your question
Yes, expansion of declarative macros is already in master and the latest versions of plugin have this feature

> I use the latest published version of the plugin but chain_err still produces <unknown> result type

Could you provide a code example (or you project if it's possible of course) when type inference doesn't work for items generated by macro?

**Comment by avkonst** [comment] 2018-06-27 22:34
Here is the screenshot:

![image](https://user-images.githubusercontent.com/3971413/42003289-cd4c16f2-7abe-11e8-8665-1381a0d3573e.png)

**Comment by avkonst** [comment] 2018-06-27 22:36
Here is the source code project:

[test_chain_err.zip](https://github.com/intellij-rust/intellij-rust/files/2143185/test_chain_err.zip)

**Comment by Undin** [comment] 2018-06-27 22:40
@avkonst Thanks

**Comment by Undin** [comment] 2018-06-27 23:04
@avkonst Currently, we don't take into account impls generated by macros => we don't know about `ChainedError` trait impl for the corresponding error type and its method => can't find `chain_err` method and can't infer result type
We know about it and try to solve it in the nearest future but can't provide any time estimations because it has some technical problems

Duplicate of #2458

**Closed by Undin** 2018-06-27 23:04 UTC
Labels: bug, macros
