### ISSUE TITLE
Type checker prompt error mismatch incorrectly.

### ISSUE THREAD

**Issue by dowenliu-xyz** [intellij-rust/intellij-rust#8106] opened 2021-11-14 05:25 UTC
I'm learning Rust, and when I open the websocket-server example of smol, the clion/rust-plugin prompt
```
mismatched types [E0308]
expected `Poll<Result<(), Error>>`, found `Poll<std::io::error::Result<()>>` 
```
But the code is correct, since, the code compiles and works fine. Maybe it's a type checker bug。

## Environment

* **IntelliJ Rust plugin version:** 0.4.159.4232-212
* **Rust toolchain version:** rustup 1.24.3 (2021-05-31) / stable-x86_64-apple-darwin rustc / 1.56.0 (09c42c458 2021-10-18)
* **IDE name and version:** CLion 2021.2.3 Build #CL-212.5457.51, built on October 14, 2021
* **Operating system:** macOS 10.15.7

## Steps to reproduce

Check out code of smol: 
```
git clone https://github.com/smol-rs/smol.git
```
Then open the code with clion
```
clion ./smol
```
In Clion , open file `examples/websocket-server.rs`, line 104.

**Comment by Maksim20023** [comment] 2023-07-27 17:37
Hi! I’m closing this ticket because the issue does not reproduce in the current environment (CLion 2023.2 Build #CL-232.8660.186, Rust plugin 0.4.199.5415-232). If this issue still reproduces for you, please reopen the ticket.

**Closed by Maksim20023** 2023-07-27 17:37 UTC
Labels: subsystem::type inference & name resolution, bug
