### ISSUE TITLE
Some methods from transitive dependencies are not being resolved

### ISSUE THREAD

**Issue by Exidex** [intellij-rust/intellij-rust#5487] opened 2020-06-02 20:25 UTC
## Environment

CLion 2020.1.1
Build #CL-201.7223.86, built on April 29, 2020
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.6.7-1-manjaro
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: String Manipulation, org.toml.lang, org.rust.lang
Current Desktop: GNOME

## Problem description
![image](https://user-images.githubusercontent.com/16986685/83565343-8c51e280-a51e-11ea-8b6d-28836143e48c.png)

Both `Result`s returned from `Module::new()` and `instantiate()` are from `anyhow` crate.
But one from `instantiate()` is not being resolved and all references to `anyhow` module in source file with declaration of `instantiate()` are not resolved, while references in source file with `Module::new()` are good. 

Code fragment compiles successfully

Adding `anyhow` crate to `Cargo.toml` doesn't help

Possibly related to https://github.com/intellij-rust/intellij-rust/issues/3798

## Steps to reproduce
Cargo.toml
```toml
[dependencies]
wasmtime = "0.16.0"
```
bin.rs
```rust
fn main() {
    let store = wasmtime::Store::default();
    let linker = wasmtime::Linker::new(&store);
    let module = wasmtime::Module::new(&store, "(module (func))").unwrap();

    linker.instantiate(&module).unwrap();
}
```

**Comment by Undin** [comment] 2020-07-03 08:28
Looks like the cause of the issue is name resolution for anyhow crate (see #4544)
In was fixed in #5603 and the latest stable release contains this fix. Now it works for me as expected
So I think it can be closed

**Closed by Undin** 2020-07-03 08:28 UTC
Labels: bug, subsystem::type inference & name resolution
