### ISSUE TITLE
Reformat Code moves comments to a new line

### ISSUE THREAD

**Issue by atanas-w** [intellij-rust/intellij-rust#8367] opened 2022-01-06 21:16 UTC
## Environment

* **IntelliJ Rust plugin version: 0.4.162.4321-212  (the bug was present with previous versions as well)**
* **Rust toolchain version: 1.59.0-nightly (the bug was present with previous versions as well)**
* **IDE name and version: IntelliJ IDEA Ultimate 2021.2.4  (the bug was present with 2021.2.3 as well)**
* **Operating system: Win 10**

## Problem description

Reformat in some cases moves/wraps comments to a new line

## Steps to reproduce

```rust
pub struct Abc {
    pub first: i32, // asdf
    pub second: bool,
}
```
Run "Code > Reformat Code" (or the shortcut Ctrl+Alt+L). The comment is moved to a new line:

```rust
pub struct Abc {
    pub first: i32, 
    // asdf
    pub second: bool,
}
```

![image](https://user-images.githubusercontent.com/31915500/148453174-9f8b4f62-8b13-471d-bff6-7ef79b6e38ae.png)

**Comment by dima74** [comment] 2022-01-11 07:16
Duplicate of #3657

**Closed by dima74** 2022-01-11 07:16 UTC
Labels: bug, subsystem::fmt
