### ISSUE TITLE
Available feature-gated code is invisible to the plugin

### ISSUE THREAD

**Issue by MSxDOS** [intellij-rust/intellij-rust#4809] opened 2019-12-31 23:32 UTC
Starting with [this](https://intellij-rust.github.io/2019/12/02/changelog-111.html) version (I think?) the plugin no longer sees, for example, some feature-gated modules in `winapi` crate that are automatically enabled by its build script unless I explicitly enable them in Cargo.toml of my main project.
Unless it's a bug, is there a way to switch this behavior back to what it was before? If not then please either add on option to or revert this change permanently because it's quite annoying.

**Comment by Undin** [comment] 2020-01-01 20:00
@MSxDOS Thanks for the report!
You can disable `cfg` evaluation while code analysis via `org.rust.lang.cfg.attributes` option in `Experimental Features` dialog (invoke `Help | Find Action` and type `Experimental Features`).
FYI, #4734 will fix your issue without disabling `cfg` evaluation

**Comment by Undin** [comment] 2020-01-01 20:02
Duplicate of #4631

**Closed by Undin** 2020-01-01 20:02 UTC
Labels: bug, cfg
