### ISSUE TITLE
Can't create rust project from within PhpStorm

### ISSUE THREAD

**Issue by konstin** [intellij-rust/intellij-rust#593] opened 2016-08-10 21:52 UTC
I'm using up to date version of PhpStorm and the rust plugin. Though `File` -> `New Project` doesn't show an option to create a rust project:

![screenshot](https://cloud.githubusercontent.com/assets/6826232/17572539/5a558be6-5f55-11e6-9adf-ec89243bd65c.png)

**Comment by matklad** [comment] 2016-08-11 05:18
Yep, this is the duplicate of #557. Creating projects currently works only in IntelliJ IDE, for other IDEs you have to create projects from the command line using `cargo new`. Sorry for the misleading changelog!

**Closed by matklad** 2016-08-11 05:18 UTC
