### ISSUE TITLE
Support for implicit named arguments for formatting macros

### ISSUE THREAD

**Issue by atanas-w** [intellij-rust/intellij-rust#8341] opened 2021-12-28 08:11 UTC
## Environment

* **IntelliJ Rust plugin version:**
* **Rust toolchain version:**
* **IDE name and version:**
* **Operating system:**

## Problem description

The [implicit named arguments for formatting macros](https://caniuse.rs/features/format_args_capture) feature is now available in Rust 1.58 Beta and allows writing code like this:

```rust
let msg = "here";
let s = format!("Abc {msg}");
println!("Hi t{msg}");
println!("{s}");
```

This is what that code snippet looks like now:

![RustFormatStr](https://user-images.githubusercontent.com/31915500/147543820-958e220b-548f-4b60-85ce-3e025bdfa7ea.png)

Please add support for implicit named arguments.

**Comment by Undin** [comment] 2022-01-05 09:36
Duplicate of #7338

**Closed** 2022-01-10 12:10 UTC
Labels: subsystem::code insight, bug
