### ISSUE TITLE
Square brackets shown as &#60; ... &#62; symbols on tooltips

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#5639] opened 2020-06-23 06:57 UTC
![image](https://user-images.githubusercontent.com/873919/85370414-5ad5a100-b537-11ea-96b2-36c6a1e488d6.png)

0.2.125.3177-202-nightly

CLion 2020.2 EAP
Build #CL-202.5792.50, built on June 19, 2020
CLion EAP User
Expiration date: July 19, 2020
Runtime version: 11.0.7+10-b944.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=580
Non-Bundled Plugins: org.jetbrains.plugins.rest, org.toml.lang, org.rust.lang, com.intellij.clion-swift

**Comment by Undin** [comment] 2020-06-23 06:58
Duplicate of #5598

**Closed by Undin** 2020-06-23 06:58 UTC
