### ISSUE TITLE
Custom macros usage highlighting

### ISSUE THREAD

**Issue by Keats** [intellij-rust/intellij-rust#544] opened 2016-07-22 15:00 UTC
I'm currently using [pest](https://github.com/dragostis/pest) and it currently only highlights the rust keywords, not the function call etc.

See https://github.com/Keats/tera/blob/master/src/parser.rs#L131-L352 for an example of code that github (and sublime) highlights correctly.

In my pycharm it looks like the following:

![2016-07-22-155859_1154x639_scrot](https://cloud.githubusercontent.com/assets/680355/17061202/4aaa02b0-5025-11e6-8c6b-90a7a9e512e4.png)

Highlighting works like a charm everywhere else

**Comment by matklad** [comment] 2016-07-22 15:09
Macros are tough unfortunately. It's difficult to determine if `foo()` is a function call or not, if it is inside a macro. To do so, we need to implement macro matching algorithm. 

Github and sublime work because they highlight based on regular expressions and not on the accurate parse trees. It is way more robust, but also way less powerful.

Closing as a duplicate of #229

**Closed by matklad** 2016-07-22 15:09 UTC

**Comment by Keats** [comment] 2016-07-22 15:10
Ah cool thanks, I saw that issue but it wasn't clear which kind of support it was for

**Comment by matklad** [comment] 2016-07-22 15:16
See: https://github.com/intellij-rust/intellij-rust/issues/545
