### ISSUE TITLE
Substitute type parameters with actual types in parameter hints

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#6656] opened 2021-01-13 09:10 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3 (CL-203.5981.166)
* **Operating system:** macOS 10.16
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
A type parameter should be substituted with an actual type when showing `Parameter info` (cmd+P). Currently, it shows unsubstituted generic type parameters instead.
<img width="482" alt="Screenshot 2021-01-13 at 12 05 02" src="https://user-images.githubusercontent.com/4854600/104430504-cea0cf00-5597-11eb-8b9c-7a818ca10e6d.png">

The implementation is located in `org.rust.ide.hints.parameter.RsParameterInfoHandler`.

## Steps to reproduce
```Rust
use std::collections::HashMap;

fn main() {
    let mut hm: HashMap<i32, &str> = HashMap::new();
    hm.insert(/* cmd+P */);
}
```

**Comment by Undin** [comment] 2021-01-13 09:41
Duplicate of #4308

**Comment by ortem** [comment] 2021-01-13 10:13
@Undin I think there should be two separate issues for `Parameter Info` and parameter hints (currently, both of them are about `Parameter info`)

**Closed** 2021-01-13 10:15 UTC
Labels: E-easy, improvement, subsystem::code insight

**Comment by ortem** [comment] 2021-01-13 10:17
There is confusion between _parameter hints_ and _parameter info_, so I changed the description of the existing issue.
(this one was reopened accidentally)
