### ISSUE TITLE
False positive: dyn trait when referring Self`

### ISSUE THREAD

**Issue by 95th** [intellij-rust/intellij-rust#4230] opened 2019-08-06 17:43 UTC
Intellij Rust show false positive about dyn keyword in traits:

```rust
pub trait TestFuture: Future {
    fn drive<T>(&mut self, other: T) -> Drive<'_, Self, T>
    where
        T: Future,
        Self: Future + Sized,
    {
        Drive {
            driver: self,
            future: Box::pin(other),
        }
    }
}
```

![Untitled](https://user-images.githubusercontent.com/22871609/62563011-b9eae280-b89f-11e9-9bcb-113f640fd4fa.png)

**Comment by Undin** [comment] 2019-08-06 20:10
Duplicate of #4174
Fixed in #4175

**Closed by Undin** 2019-08-06 20:10 UTC

**Comment by 95th** [comment] 2019-08-09 04:43
@Undin Thanks. I updated my plugin but the issue is still happening. Is it released?

I am using IDEA community 2019.1

**Comment by Undin** [comment] 2019-08-09 04:44
Not yet. It will be released next week

**Comment by Undin** [comment] 2019-08-09 05:03
@95th Also, you can use nightly builds of the plugin. See [instruction](https://intellij-rust.github.io/install#nightly-builds) how to do it

**Comment by 95th** [comment] 2019-08-09 05:35
@Undin Thanks!
