### ISSUE TITLE
False positive error message: '_' unexpected

### ISSUE THREAD

**Issue by hahseba** [intellij-rust/intellij-rust#9382] opened 2022-09-20 14:26 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.178.4873-222
* **Rust toolchain version:** 1.63.0 (4b91a6ea7 2022-08-08) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.2.1 (CL-222.3739.54)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Lines beginning with an assignment to '_' are marked as an error, but compilation works fine afterwards.

<img width="673" alt="image" src="https://user-images.githubusercontent.com/49211026/191307299-fabeb3bd-cdd8-4b81-acc4-7112220ef1ba.png">

## Steps to reproduce
Any assignments to '_' without a preceeding let seem to trigger this error.

**Comment by afetisov** [comment] 2022-09-22 11:32
Duplicate of #9274

**Closed** 2022-09-22 11:38 UTC
Labels: bug, subsystem::highlighting
