### ISSUE TITLE
`match` with all possible values still suggest to add remaining patters.

### ISSUE THREAD

**Issue by xNxExOx** [intellij-rust/intellij-rust#7020] opened 2021-03-25 16:56 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.143.3737-203
* **Rust toolchain version:** 1.52.0-nightly (f5f33ec0e 2021-03-19) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2020.3.3 Community Edition (IC-203.7717.56)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
`match` with all possible values still suggest to add remaining patters.

## Steps to reproduce
```rust
let x = 1u8; // I have variable, but it behaves same even with constant
match x {
    0..=7 => {},
    8..=15 => {},
    16..=231 => {}
    232..=255 => {}
    //_ => {}// adding this line is suggested on the match statement
}
```

I do not think any more code base is needed.

**Comment by Undin** [comment] 2021-03-25 17:17
Duplicate of #4311

**Closed by Undin** 2021-03-25 17:17 UTC
Labels: bug, subsystem::code insight
