### ISSUE TITLE
Cannot find declaration to go to

### ISSUE THREAD

**Issue by busyluo** [intellij-rust/intellij-rust#4817] opened 2020-01-07 09:15 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.114.2822-193-nightly
* **Rust toolchain version:** 1.40.0-stable-gnu
* **IDE name and version:** CLion 2019.3.1
* **Operating system:** Windows 10 1903

## Problem description
![image](https://user-images.githubusercontent.com/16347811/71882573-afdf4f80-316f-11ea-9c09-1d8fbfb8cc38.png)

## Steps to reproduce
``` rust
use tokio::io::AsyncWriteExt;

pub async fn foo() {
    let mut stream = tokio::net::TcpStream::connect("127.0.0.1:6142").await.unwrap();
    stream.write(b"hello world\n").await;
}
```

**Comment by shellbear** [comment] 2020-03-09 13:53
I personally solved the problem by selecting the `Expand with experimental engine` in Rust language options.

<img width="999" alt="Screenshot" src="https://user-images.githubusercontent.com/20194995/76219193-be042780-6215-11ea-96dd-e539658b02e3.png">

**Comment by Undin** [comment] 2020-03-09 17:13
Duplicate of #4627

**Closed by Undin** 2020-03-09 17:13 UTC
Labels: bug, subsystem:macros, subsystem:type inference & resolve
