### ISSUE TITLE
const_generics feature error when using stabilised min_const_generics features

### ISSUE THREAD

**Issue by Juici** [intellij-rust/intellij-rust#6648] opened 2021-01-10 19:37 UTC
Plugin Version: 0.3.138.3572-203

When using the stabilised `min_const_generics` on nightly, with nightly set as the toolchain in CLion, there is an error saying to enable the `const_generics` feature.

Here's a minimal example of some code which should reproduce the error.

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c6b9329ae39a161602d7ad66cbde268a

**Comment by Undin** [comment] 2021-01-10 19:40
Duplicate of #6361

**Closed by Undin** 2021-01-10 19:40 UTC
Labels: bug, subsystem::code insight
