### ISSUE TITLE
Incorrect macro expansion error shown

### ISSUE THREAD

**Issue by robalexj** [intellij-rust/intellij-rust#10488] opened 2023-05-20 12:01 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.194.5382-231
* **Rust toolchain version:** 1.69.0 (84c898d65 2023-04-16) x86_64-apple-darwin
* **IDE name and version:** CLion 2023.1.3 (CL-231.9011.31)
* **Operating system:** macOS 13.3.1
* **Macro expansion:** enabled

## Problem description
I'm finding that a simple program to add two integers using the "checked_add" method shows as an error in CLion (screenshot attached). The program compiles and runs without error, so I think the error output is incorrect. It feels like I must be missing something, as this is a simple example.

Error output:
<img width="763" alt="rust-example" src="https://github.com/intellij-rust/intellij-rust/assets/35926762/c9752424-8145-4c24-b034-be0a843daaa9">

## Steps to reproduce
Load the below in CLion with IntelliJ Rust plugin:
main.rs
```
fn main() {
    let a: i32 = 1;
    let b: i32 = 2;
    let result = a.checked_add(b).expect("overflow!");
    println!("Result: {result}");
}
```

**Comment by Maksim20023** [comment] 2023-07-28 15:59
Hi! I'm closing this ticket because the issue is fixed (please see a fix [Pull 10688](https://github.com/intellij-rust/intellij-rust/pull/10688)). This fix is available from the Rust plugin 0.4.199.5414 version and higher. Please make sure that your installed plugin is [up-to-date](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#update). If this issue still reproduces for you, please reopen the ticket.

**Closed by Maksim20023** 2023-07-28 15:59 UTC
