### ISSUE TITLE
IDE shows that variable is unused when it passed to format functions (rust 1.58 feature)

### ISSUE THREAD

**Issue by Frago9876543210** [intellij-rust/intellij-rust#8429] opened 2022-01-18 16:58 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.163.4378-213
* **Rust toolchain version:** x86_64-pc-windows-msvc 1.60.0-nightly (1bd4fdc94 2022-01-12)
* **IDE name and version:** CLion 2021.3.2
* **Operating system:** Windows 10

## Problem description
![img](https://user-images.githubusercontent.com/13465245/149983099-037c602f-5ed0-4e25-9521-de69e668cb3a.png)

## Steps to reproduce
```rust
fn main() {
    let x = 123;
    println!("{x}");
}
```

**Comment by Undin** [comment] 2022-01-18 17:27
Duplicate of #8417

**Closed by Undin** 2022-01-18 17:27 UTC
Labels: subsystem::code insight, bug
