### ISSUE TITLE
Could not auto complete std::os::unix in macos

### ISSUE THREAD

**Issue by swordow** [intellij-rust/intellij-rust#5607] opened 2020-06-19 05:06 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.124.3162-201
* **Rust toolchain version:** 1.44.1
* **IDE name and version:** IntelliJ IDEA 2020.1.2 (Community Edition) Build #IC-201.7846.76, built on June 1, 2020

* **Operating system:** macOS 10.15.4

## Problem description
Could not auto complete std::os::unix in macos
unix is missed, only macos avaiable..

## Steps to reproduce
![image](https://user-images.githubusercontent.com/7107003/85098460-5fdfdb00-b22d-11ea-92fe-acb983a254cd.png)

**Comment by Kobzol** [comment] 2020-06-19 06:04
Related: https://github.com/intellij-rust/intellij-rust/issues/2846, https://github.com/intellij-rust/intellij-rust/issues/5188

**Comment by swordow** [comment] 2020-06-19 07:12
> Related: #2846, #5188

In my case, there is some different with #5188, my target os is macos with toolchain x86_64-apple-darwin, and of course macos is unix like system, the ide  should  contain unix mod. The target in [build] i could not set any other toolchain which does not work on macos....

**Comment by Undin** [comment] 2020-06-19 07:15
Duplicate of #3957

**Closed by Undin** 2020-06-19 07:15 UTC
Labels: feature, subsystem::cfg
