### ISSUE TITLE
Losing color code & intellisens

### ISSUE THREAD

**Issue by arn-the-long-beard** [intellij-rust/intellij-rust#6865] opened 2021-02-18 13:12 UTC
Hello guys :wink: 

Yesterday I did update Rust on my machine to use 1.50.0 and I lost my intellisens and color code and ability to click on a Type or method and go the source library.

## Environment

* **IntelliJ Rust plugin version:** 0.3.141.3674-203
* **Rust toolchain version:** null
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Linux 5.4.0-65-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Do not see most of the colors.
Intellisense seems ddisable for most cases.
Do not see documentation popping up from libraries.

![cannot_navigate](https://user-images.githubusercontent.com/30114057/108364581-860fad80-71f6-11eb-8d85-a69773e68b68.png)

I cannot click on my methods in this screenshot. And the doc does not pop up neither.

All experimental features are activated and I could see colors even in macro uses yesterday.

I also see the key word `async` colorless and when I hover it, it says "this feature is only available in Edition 2018"

## Steps to reproduce

Update to Rust 1.50.0

Thank you guys for help !

**Comment by Undin** [comment] 2021-02-18 22:04
@arn-the-long-beard Thanks for the report!
Looks like something wrong with project model structure in your project.
Could you check Cargo tool window and invoke `Refresh` action from it? Also, it would be great to get logs. You can find them via `Help | Show Log in %your file manager name%`
![image](https://user-images.githubusercontent.com/2539310/108427485-496fa080-724e-11eb-830b-ab9d97118329.png)

**Comment by arn-the-long-beard** [comment] 2021-02-19 10:34
Hi, Thank you so much for your message !

The `Refresh` still continue to fail

![cargo_is_failing](https://user-images.githubusercontent.com/30114057/108492515-8f0b8800-72a5-11eb-8362-6196bd7df454.png)

[idea.log](https://github.com/intellij-rust/intellij-rust/files/6009278/idea.log)


I can see a lot of issues in the log it seems.

**Comment by Undin** [comment] 2021-02-19 14:06
@arn-the-long-beard unfortunately, it's still not clear where the problem. I see only some warning from Crate local index but it seems it's a separate problem and it's unlikely a course of your issue.
Could you attach all your logs? `Help | Collect Logs and Diagnostic Data` action should help you

**Comment by DzenanJupic** [comment] 2021-02-19 19:54
@arn-the-long-beard I also ran into a similar situation a few times. For me, the solution always was to invalidate the cache and restart the IDE. To invalidate the cache just click `Shift` two times in a row and search for `Invalidate Caches / Restart ...`.

Maybe it helps :)

**Comment by arn-the-long-beard** [comment] 2021-02-22 08:39
Hey, I tried to invalidate the cache. It does not work  neither.

Even modules inside my app or libraries are not detected as well .

![modules_not_working](https://user-images.githubusercontent.com/30114057/108683405-db4b0800-74f1-11eb-91b7-ff06dd9eabbe.png)

**Comment by Undin** [comment] 2021-02-22 08:52
@arn-the-long-beard it seems that the problem not with settings but with the loading of project model that why I asked to share full logs via `Help | Collect Logs and Diagnostic Data` action

But according to the latest screenshot, I suppose that `org.rust.cargo.fetch.actual.stdlib.metadata` experimental feature is enabled for you and your issue is the same as #6603.

The proper way to fix it just to remove `vendor` directory that you can find on your screenshot. But it would be great to try to refresh project model (as described in https://github.com/intellij-rust/intellij-rust/issues/6865#issuecomment-781664437) and collect full logs before removing to ensure that it was the same issue

**Comment by arn-the-long-beard** [comment] 2021-02-22 09:02
1 -  Ok, here is the file 
[clion-logs-20210222-095906.zip](https://github.com/intellij-rust/intellij-rust/files/6020730/clion-logs-20210222-095906.zip)

> But it would be great to try to refresh project model (as described in #6865 (comment)) 

2 - Yes I tried but it did not work ^^

3 - I try to remove the `vendor` directory

**Comment by Undin** [comment] 2021-02-22 09:09
And according to logs the issue the same as #6603. It was fixed in #6609 so after removing `vendor` dir it shouldn't appear again

**Comment by Undin** [comment] 2021-02-22 09:10
Duplicate of #6603

**Closed by Undin** 2021-02-22 09:10 UTC

**Comment by arn-the-long-beard** [comment] 2021-02-22 09:27
Thank you so much for the help !!!! :smile:
