### ISSUE TITLE
Completion issue: no method proposed sometimes (e.g. in the crate rayon)

### ISSUE THREAD

**Issue by JamesMenetrey** [intellij-rust/intellij-rust#4475] opened 2019-09-30 22:23 UTC
## Environment
- **IntelliJ Rust plugin version**: 0.2.106.2135-192
- **Rust toolchain version**: stable-x86_64-pc-windows-gnu rustc 1.38.0 (625451e37 2019-09-23)
- **IDE name and version**: CLion 2019.2.3
- **Operating system**: Windows 10 Pro x64 1906

## Problem description
The autocompletion sometimes does not yield any result. This example demonstrates a concrete scenario using the crate `rayon`. The function `par_iter()` does not propose any suggestion, while the code is working. The screenshot below details the issue:

![issue](https://bitbucket.org/ZenLulz/rust-no-autocompletion-rayon/raw/822f34c3f114159188ed54c0acae7621bb1237b3/issue.png "")

## Steps to reproduce
Clone `https://ZenLulz@bitbucket.org/ZenLulz/rust-no-autocompletion-rayon.git`. Open the project in the environment defined above. Write a dot (.) after the `par_iter()` function, in `main.rs`. Notice that no autocompletion is given.

Sample code:
```Rust
use rayon::prelude::*;
fn main() {
    let v = vec![1,2,3];
    let x = v.par_iter()./*caret*/ // no completion for `map`
}
```

**Comment by ZenLulz** [comment] 2019-09-30 22:33
Just tested on macOS using **stable-x86_64-apple_darwin rustc 1.38 (625451e37 2019-09-23)** and I can reproduce the issue.

**Comment by lancelote** [comment] 2019-12-22 10:15
Got stumble across this as well. My example https://gitlab.com/lancelote/learning-rust/blob/ab08dae9dcde7548a18cb6fb9acb1df297bb5f42/chapter6/src/bin/parallel_barycenter.rs#L35

**Comment by LoganDark** [comment] 2020-08-13 15:29
This happens for me as well!

**Comment by Silentdoer** [comment] 2020-09-16 00:33
Any update on this? @vlad20012

**Comment by AqlaSolutions** [comment] 2020-12-21 16:11
Wow, it's been a year since issue creation and this is still not fixed!

**Comment by seanpianka** [comment] 2020-12-29 23:02
Someone has to actually spend time and effort to fix this :)

**Comment by cgburgess** [comment] 2021-01-02 22:16
This seems like a regression because I remember working on a project a long time ago and not having this problem. As someone who relies on the type hints all the time, this is a bummer. 

Does anyone know where you would even start to try and fix this? I have no experience with this project.

**Comment by AndreKR** [comment] 2021-01-03 07:35
@cgburgess The first step would be to set up the plugin for development, as described in [CONTRIBUTING.md](https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md). Check out [ARCHITECTURE.md](https://github.com/intellij-rust/intellij-rust/blob/master/ARCHITECTURE.md) as well.

The next step I guess would be poking around with the debugger, seeing how normally types are represented and then checking what the rayon types are missing.

**Comment by andrewgazelka** [comment] 2021-02-15 18:57
Possible duplicate of #4277

**Comment by Alfred-Mountfield** [comment] 2021-03-16 14:00
This problem also affects other parts of intellisense, any of the contents of the closures within the operators like `map`, `for_each`, etc. after the par_iter aren't picked up, meaning refactoring misses them, and things like ctrl+click fail to find usages of functions.

**Closed** 2021-11-09 18:16 UTC
Labels: subsystem::type inference & name resolution, bug
