### ISSUE TITLE
Look for rust src in .cargo

### ISSUE THREAD

**Issue by mfarrugi** [intellij-rust/intellij-rust#572] opened 2016-08-01 23:37 UTC
And whatever other places make sense

**Comment by matklad** [comment] 2016-08-01 23:40
The problem is, there are currently no places which make sense :) 

Correct me if I am wrong, but there seems to be zero "official" ways to download rust sources besides just downloading an archive from the rust-lang.org. And in this case, the user can save it anywhere, and `.cargo` is as good a place as any other.

**Comment by mfarrugi** [comment] 2016-08-02 00:30
My most recent install of rustup seems to have placed sources under `~/.cargo/rust-source/src/`. Not 100% sure that was just running the installer, though.

**Comment by Furyhunter** [comment] 2016-08-02 02:29
Well, considering Intellij-Rust doesn't even support rustup yet...

**Comment by matklad** [comment] 2016-08-02 07:26
>My most recent install of rustup seems to have placed sources under ~/.cargo/rust-source/src/. Not 100% sure that was just running the installer, though.

Are you sure about this? Perhaps this wasn't rustupt? It should be able to do a similar thing soon, but I've just tried the fresh rustup and haven't seen `.cargo/rust-source`. Also it would be suspicious if rustup installed sources in `.cargo` and not in `.multirast/toolchains/nightly-x86_64-unknown-linux-gnu`.

**Comment by mfarrugi** [comment] 2016-08-02 14:24
It looks like I misattributed it's presence to recently installing rustup. The instructions for installing something else must have had me clone the source. (Though I'm clearly surprised nothing packages the source.)

This can be closed or sit and wait on one of the many issues open elsewhere for distributing sources.

**Comment by matklad** [comment] 2016-08-02 14:25
Let's close this for now: I am keeping an eye on stdlib distribution issues :)

**Closed by matklad** 2016-08-02 14:25 UTC
