### ISSUE TITLE
 unresolved reference: task::sleep with async_std

### ISSUE THREAD

**Issue by L1AN0** [intellij-rust/intellij-rust#4616] opened 2019-11-10 16:44 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.109.2149-192
* **Rust toolchain version:** 1.40.0
* **IDE name and version:** CLion 2019.2.5  Build #CL-192.7142.39, built on October 30, 2019
* **Operating system:** 5.3.8-arch1-1 x86_64 GNU/Linux

## Problem description

`async_std` https://docs.rs/async-std/0.99.12,

Experimental macro engine is enabled.

`async_std` includes many members in `task` module, but cannot be resolved by intellij rust (for example, unresolved reference: `task::sleep`).

## Steps to reproduce

```rust
use std::time::Duration;
use async_std::task;
use futures::executor::block_on;
use futures::future::join_all;
use futures::task::SpawnExt;

async fn hello_world(n: u32) {
    task::sleep(Duration::from_secs(5)).await;
    println!("hello, world {}", n);
}

async fn async_main() {
    let mut futures = Vec::new();
    for i in 0..20 {
        futures.push(hello_world(i));
    }
    join_all(futures).await;
}

fn main() {
    let tp = futures::executor::ThreadPoolBuilder::new()
        .pool_size(8).create().unwrap();
    let handle = tp.spawn_with_handle(async_main()).unwrap();
    dbg!(block_on(handle));
}
```

**Comment by daharon** [comment] 2019-11-16 11:26
Possible that this is a duplicate of #4614?

**Comment by vlad20012** [comment] 2019-11-16 12:43
Duplicate of #4627

**Closed** 2019-11-25 20:02 UTC
Labels: bug, macros, type inference & resolve
