### ISSUE TITLE
Fails to refactor items generated by macro

### ISSUE THREAD

**Issue by PizzaCrust** [intellij-rust/intellij-rust#6619] opened 2021-01-04 17:22 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.51.0-nightly (fde692739 2021-01-02) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.3.1 (CL-203.6682.181)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
When attempting to refactor `A` to a different name, it fails to refactor. (it says that it failed to refactor a random rs file, im presuming it's the result of macro expansion)
```rust
macro_rules! create_struct {
    ($name:ident) => {
        struct $name;
    };
}

create_struct!(A);

fn a(_: A) {}
```
I don't know if this is intended or not, but it seems to be a bug.

## Steps to reproduce
1. Place the aforementioned code in the editor
2. Attempt to refactor A to a different name

**Comment by Undin** [comment] 2021-01-04 18:56
Duplicate of #5740

**Closed by Undin** 2021-01-04 18:56 UTC
Labels: subsystem::macros, subsystem::refactoring
