### ISSUE TITLE
Cannot debug with MSVC toolchain

### ISSUE THREAD

**Issue by rez23** [intellij-rust/intellij-rust#8645] opened 2022-03-08 20:01 UTC
Hello I can't debug using MSVC rust toolchain (I tried with all 3 channel).  If I set breakpoint in my code I get  the following error: "The breakpoint will not currently be hit. No executable code is associated with this line."

## Environment

* **IntelliJ Rust plugin version:** 0.4.166.4477-213-beta
* **Rust toolchain version:** null
* **IDE name and version:** CLion 2021.3.3 (CL-213.6777.58)
* **Operating system:** Windows 11 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Steps to reproduce
Run debug with MSVC rust toolchain and LLDB 

EDIT
This seems a problem with last CLion lldb. No problem with the new EAP (2022) and with the previous version.

**Comment by Undin** [comment] 2022-03-10 07:56
Thanks for the report!
It's a known problem. The reason is changes in debugging info generated by the latest compiler. It's already fixed in the latest CLion 2022.1 EAP. Also, as a workaround, you can use Rust 1.58

**Comment by Undin** [comment] 2022-03-10 07:56
Duplicate of #8526

**Closed by Undin** 2022-03-10 07:56 UTC
Labels: subsystem::debugger, bug
