### ISSUE TITLE
Breakpoints in Windows stop in incorrect file

### ISSUE THREAD

**Issue by drglove** [intellij-rust/intellij-rust#6161] opened 2020-09-26 03:31 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.131.3366-202
* **Rust toolchain version:** 1.46.0 and 1.47.0
* **IDE name and version:** CLion 2020.2.3 Build #CL-202.7319.72, built on September 17, 2020
* **Operating system:** Windows 10 Pro 1909 x64
* **Compiler:** MSVC via Visual Studio Community 2019 16.7.4

## Problem description
When I set a breakpoint in my Rust project, debugged via clion,  the breakpoint gets hit in another file of the same name (but at a different path) and at the same numbered line. I've also included a link to a video demonstrating the behaviour here: [breakpoint issue video](https://youtu.be/fxeEqSvffEE)

e.g. I have a few `mod.rs` files in my project. My directory structure resembles this:
```
- src
-- main.rs
-- testmod1
--- mod.rs
-- testmod2
--- mod.rs
```

If I put a breakpoint in `testmod2\mod.rs` at line 2, the debugger will also break if `testmod1\mod.rs:2` is hit.

Some things worth noting that I tried to bypass the issue, with no good results:
- I was on the stable Rust 1.46.0 toolchain, but tried the 1.47.0 beta instead.
- Reinstalled the Rust plugin
- Reinstalled rust via rustup
- Reinstalled clion
- Destroyed the clion-specific parts of the project, and re-created it
- Updated Visual Studio 2019
- Specified the Visual Studio bundled LLDB clang-cl.exe instead of the automatically detected cl.exe compilers
- Disabled the renderers in the _Data Views > Rust_ tab.
- Disabled the _Data Views > Show values_ inline option.

Also worth noting is that I do not have this problem on OSX, where I also develop with clion. This only seems to happen to me on Windows, where I am trying to use MSVC.

## Steps to reproduce
1. Configure a project as such (or clone my project from https://github.com/drglove/clion-rust-breakpoint-repro):
- Create a project with the already mentioned directory structure.
- Declare these functions
`main.rs`:
```Rust
mod testmod1;
mod testmod2;

fn main() {
    testmod1::breakpoint_one();
    testmod2::breakpoint_two();
}
```

`testmod1\mod.rs`:
```Rust
pub fn breakpoint_one() -> u32 {
    let x = 1;
    x
}
```

`testmod2\mod.rs`:
```Rust
pub fn breakpoint_two() -> u32 {
    let y = 100;
    y
}
```
2. Put a breakpoint in `testmod2\mod.rs:2` (or any line that overlaps with `testmod1\mod.rs`)
3. Debug the application in clion
4. Note that a supposed breakpoint at `testmod1\mod.rs:2` is hit.

**Comment by rod-salazar** [comment] 2020-12-14 08:56
My only workaround to get debugging working in this case with CLion is to use rust nightly's "breakpoint" api. https://doc.rust-lang.org/std/intrinsics/fn.breakpoint.html

**Comment by drglove** [comment] 2021-03-14 20:47
Any chance this can get some attention? The workaround above does the trick, but is clunky to use. The debugger is fairly useless with this bug in my use case.

**Comment by ortem** [comment] 2021-03-15 07:58
@drglove Thank you for the detailed description and the example project! I've reproduced this issue on my machine and will try to investigate it soon.

Note, vanilla LLDB does not support debugging Rust when using the MSVC toolchain. So we maintain [our own fork of LLDB with MSVC support](https://blog.jetbrains.com/clion/2019/06/clion-2019-2-eap-msvc-debugger-unused-includes-check-and-more/#msvc_debug) to provide this very experimental feature. That's why debugging on macOS (or even on Windows with GNU toolchain) is more stable.

**Comment by AdamLeyshon** [comment] 2021-07-21 07:51
I thought I was going absolutely mad!

Setting breakpoints in a `mod.rs` when you have a dozen or so crates makes debugging almost impossible.

Using `nightly` isn't possible for us due to tight restrictions on the rust version we must use.

Switching to GNU/MinGW toolchain away from MSVC on Windows fixes the problem as mentioned.

**Comment by drglove** [comment] 2021-08-10 07:24
This does not seem to be an issue for me after updating CLion and the Rust plugin. Woohoo!


- IntelliJ Rust plugin version: 0.4.152.4026-212
- Rust toolchain version: 1.54.0
- IDE name and version: CLion 2021.2 Build #CL-212.4746.93, built on July 17, 2021
- Operating system: Windows 10 Pro 21H1 x64 (OS build 19043.1110)
- Compiler: MSVC via Visual Studio Community 2019 16.10.4

**Comment by ortem** [comment] 2021-08-11 10:39
@drglove Glad to hear that, thank you for noticing us! LLDB bundled with CLion was updated to version 12 recently ([blog post](https://blog.jetbrains.com/clion/2021/07/clion-2021-2-eap-profiling-wsl-cmake-presets-lldb-12/)) so updating to CLion 2021.2 could have helped to solve the issue indeed.

@AdamLeyshon Could you please update your IDE and try debugging with MSVC toolchain again?

**Comment by ortem** [comment] 2021-11-01 12:52
Hopefully, this issue is not relevant anymore, so I close it. Feel free to reopen if there are cases when the debugger still stops in incorrect files on Windows with MSVC toolchain.

**Closed by ortem** 2021-11-01 12:52 UTC
Labels: subsystem::debugger, bug
