### ISSUE TITLE
code completion does not work for os specific std-namespaces

### ISSUE THREAD

**Issue by Beiri22** [intellij-rust/intellij-rust#6385] opened 2020-11-12 07:54 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.134.3455-203
* **Rust toolchain version:** stable 1.47
* **IDE name and version:** CLion 2020.03 EAP
* **Operating system:** Manjaro

## Problem description
Code completion does not work for os specific std-namespaces like
```use std::os::unix::process::CommandExt;```
The Namespace std::os::raw is the only one shown, but there are more

## Steps to reproduce

try the example above. The struct exists and works, but the completion stops.

**Comment by Undin** [comment] 2020-11-12 08:30
Duplicate of #3957

**Closed by Undin** 2020-11-12 08:30 UTC
Labels: bug, subsystem::type inference & name resolution, subsystem::сompletion
