### ISSUE TITLE
An error occurred when... 0 is in a file or something?

### ISSUE THREAD

**Issue by HTG-YT** [intellij-rust/intellij-rust#6811] opened 2021-02-07 02:51 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.141.3653-211-nightly
* **Rust toolchain version:** 1.52.0-nightly (a73c2e555 2021-02-06) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.1 EAP (CL-211.4961.39)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

An error cocurred when reading a file with `0` in it...?

```
java.lang.AssertionError: `0` is not a string literal
	at org.rust.ide.injected.RsStringLiteralEscaperKt.escaperForLiteral(RsStringLiteralEscaper.kt:26)
	at org.rust.lang.core.psi.ext.RsLitExprMixin.createLiteralTextEscaper(RsLitExpr.kt:65)
	at com.intellij.ws.inspection.HttpUrlsUsageInspection.findLinkLiteral(HttpUrlsUsageInspection.kt:95)
	at com.intellij.ws.inspection.HttpUrlsUsageInspection.access$findLinkLiteral(HttpUrlsUsageInspection.kt:17)
	at com.intellij.ws.inspection.HttpUrlsUsageInspection$MyVisitor.visitElement(HttpUrlsUsageInspection.kt:66)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.rust.lang.core.psi.impl.RsExprImpl.accept(RsExprImpl.java:33)
	at org.rust.lang.core.psi.impl.RsLitExprImpl.accept(RsLitExprImpl.java:33)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:315)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:281)
	at com.intellij.codeInspection.ex.InspectionEventsKt.reportWhenInspectionFinished(inspectionEvents.kt:9)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:276)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:272)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:272)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1114)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:612)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by Undin** [comment] 2021-02-07 06:03
Duplicate of #6754

**Closed by Undin** 2021-02-07 06:03 UTC
Labels: bug, subsystem::code insight

**Comment by HTG-YT** [comment] 2021-02-07 07:06
I have already disabled it... Hm
