### ISSUE TITLE
Liveness analysis seems to fail on variables passed to `anyhow!`

### ISSUE THREAD

**Issue by matschaffer** [intellij-rust/intellij-rust#5692] opened 2020-07-03 00:27 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.125.3191-201
* **Rust toolchain version:** rustup 1.21.1 (7832b2ebe 2019-12-20)
* **IDE name and version:**
* **Operating system:**

IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on June 1, 2020
Licensed to Mat Schaffer
Subscription is active until January 15, 2021
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: PlantUML integration, org.jetbrains.plugins.hocon, com.intellij.plugins.watcher, org.intellij.plugins.hcl, com.tang, name.kropp.intellij.makefile, org.jetbrains.plugins.go, Pythonid, org.jetbrains.plugins.ruby, org.jetbrains.kotlin, org.intellij.scala, com.jetbrains.php, ru.adelf.idea.dotenv, org.toml.lang, org.rust.lang

## Problem description

Liveness check seems to get lost when passing to `anyhow!`

Seems like it might bear some relation to https://github.com/intellij-rust/intellij-rust/issues/4544

## Steps to reproduce

Just an extracted code sample for now

```
use anyhow::{anyhow, Context, Result as AnyResult};

...

            let err = std::process::Command::new(name)
                .args(args)
                .exec();

            // exec either never returns or returns and error
            return Err(anyhow!("Exec failed: {}", err));
```

![cloud_–_lib_rs__cloud_](https://user-images.githubusercontent.com/690/86419779-48b1ea80-bd0f-11ea-9062-7d4466acdf51.png)

The IDE seems to claim `err` is unused, but it's getting passed to `anyhow!` in the next statement.

**Comment by Undin** [comment] 2020-07-03 07:19
@matschaffer try new expansion macro engine, it should solve your issue. See #3628 for details

**Comment by Undin** [comment] 2020-07-03 07:20
Duplicate of #5627

**Closed by Undin** 2020-07-03 07:20 UTC
Labels: bug, subsystem::code insight, subsystem::macros

**Comment by matschaffer** [comment] 2020-07-03 08:51
So far so good. Thanks!
