### ISSUE TITLE
TY does not work after clone()

### ISSUE THREAD

**Issue by AtomicInteger** [intellij-rust/intellij-rust#2514] opened 2018-05-04 15:58 UTC
When we are doing `.clone()` after data container unwrapping, type inference does not work.
Tested on: `Vec<>`, `Box<>`, `Rc<>`, `RefCell<>` and `Arc<>`.
Example:
```rust
struct Foo {
    bar: Box<i32>
}

impl Foo {
    fn test(&self) {
        let b = self.bar.as_ref().clone();
        b // variable b: <unknown>
    }
}
```
System info:
OS: Windows 7
intellij-rust version: 0.2.0.2093-181
IDE: IntelliJ IDEA Community Edition 2018.1.3 EAP(Build 181.4892.5)
rustup: 1.11.0 (e751ff9f8 2018-02-13)
rustc: 1.27.0-nightly (ac3c2288f 2018-04-18)
Toolchain: nightly-x86_64-pc-windows-msvc (default)

**Comment by e-oz** [comment] 2018-05-11 14:48
simple `to_owned` doesn't work.

**Comment by e-oz** [comment] 2018-05-14 19:26
I think it's duplicate of https://github.com/intellij-rust/intellij-rust/issues/2482

**Closed** 2018-06-19 21:15 UTC
Labels: bug, type inference & resolve
