### ISSUE TITLE
Windows: Use rust toolchain from linux subsystem

### ISSUE THREAD

**Issue by philippkeller** [intellij-rust/intellij-rust#1239] opened 2017-05-15 19:50 UTC
Is there a way to use the rust toolchain from the linux subsystem (aka bash) on Windows?

On cmd.exe I can write `bash -c ~/.cargo/bin/rustc` and this works. So on the *Toolchain location* setting on an Intellij project I tried `$(bash -c ~/.cargo/bin/)` but without luck, because I think it only accepts a directory and not a command. Is there a way to set commands for `rustc` and `cargo`?

What I try to achieve is to develop on Windows' IntelliJ while compiling/linking to a linux target, all without needing to set up a cross compiler environment (which I'm also open up to do but [didn't receive any feedback](https://github.com/japaric/rust-cross/issues/33) so far)

**Comment by alygin** [comment] 2017-05-17 04:12
Looks like a duplicate of #1171.

**Closed** 2017-07-12 05:54 UTC
