### ISSUE TITLE
False positive cannot move

### ISSUE THREAD

**Issue by frqc** [intellij-rust/intellij-rust#5923] opened 2020-08-12 23:34 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.128.3278-202
* **Rust toolchain version:** 1.45.2
* **IDE name and version:** CLion 2020.2
* **Operating system:** Mac OS 10.15.6

## Problem description

False positive error report for "cannot move". 

![Screen Shot 2020-08-12 at 4 29 47 PM](https://user-images.githubusercontent.com/14215563/90078233-0ccc5680-dcb9-11ea-9524-90cceefe0319.png)

New to nalgebra and ndarray, not really sure which part goes wrong. The program itself can compile and run as expected using cargo cli. 

## Steps to reproduce

```
[dependencies]
ndarray = "0.13.1"
nalgebra = "0.21"
```

main.rs

```
use nalgebra::Point3;
use ndarray::Array2;

struct MyPt {
    pub real_pt: Point3<f32>
}

fn main() {

    let mut pts: Vec<MyPt> = Vec::new();
    pts.push(MyPt { real_pt: Point3::new(0.0, 0.0, 0.0) });
    pts.push(MyPt { real_pt: Point3::new(1.0, 0.0, 0.0) });
    pts.push(MyPt { real_pt: Point3::new(2.0, 0.0, 0.0) });


    let row:usize = 1;
    let column:usize = 3;

    let mut new_pts = Vec::new();
    let matrix = Array2::from_shape_vec((row, column), pts).unwrap();
    for i in 0..row {
        for j in 0..column {
            let pt = matrix.get((i, j)).unwrap();
            new_pts.push(pt.real_pt);
        }
    }
}

```

**Comment by ortem** [comment] 2020-09-04 14:28
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/3987.
You can [disable](https://www.jetbrains.com/help/idea/disabling-and-enabling-inspections.html) this inspection for projects that use `nalgebra` if such false positives are annoying.

**Closed by ortem** 2020-09-04 14:28 UTC
Labels: bug, subsystem::code insight
