### ISSUE TITLE
enable org.rust.cargo.evaluate.build.scripts features will cause code parse failed

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#5005] opened 2020-02-22 07:03 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.117.2862-193-nightly
* **Rust toolchain version:** 1.43.0-nightly (e02974078 2020-02-18)
* **IDE name and version:** clion 2019.3.4
* **Operating system:** Archlinux

## Problem description
when enable experimental feature `org.rust.cargo.evaluate.build.scripts`, if codes has some problem such as some method doesn't complete, rust plugin will parse codes failed, such as can't analyze `async` keyword

## Steps to reproduce
1. enable experimental feature `org.rust.cargo.evaluate.build.scripts`
2. open a project which doesn't finish and has some problem such as `cargo check` will fail
3. rust plugin will parse codes failed

**Comment by Sherlock-Holo** [comment] 2020-02-22 07:04
the expend declare marcos use experimental engine

**Comment by Undin** [comment] 2020-05-25 09:18
I think it's the same as #5016 and it's already fixed in #5341

**Comment by Undin** [comment] 2020-05-25 09:18
Duplicate of #5016

**Closed by Undin** 2020-05-25 09:18 UTC
Labels: bug, duplicate, subsystem::tools
