### ISSUE TITLE
No autocomplete for crate items when macro with crate's name is imported

### ISSUE THREAD

**Issue by asv1** [intellij-rust/intellij-rust#4749] opened 2019-12-13 18:40 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.111.2147-193
* **Rust toolchain version:** 1.39
* **IDE name and version:** PyCharm 2019.3
* **Operating system:** Windows 10

## Steps to reproduce
```rust
use anyhow::anyhow;

// anyhow crate contains anyhow! macro
// when macro is imported, there no autocomplete for crate 'anyhow' items

fn main() {
    test(); //no autocomplete when macro is imported
}

fn test() -> anyhow::Result<u32> {
    Ok(2)
}
```

**Comment by Undin** [comment] 2019-12-13 19:36
Duplicate of #4509

**Closed by Undin** 2019-12-13 19:36 UTC
Labels: bug, duplicate, type inference & resolve
