### ISSUE TITLE
type error for shift operators when lhs and rhs are of different types

### ISSUE THREAD

**Issue by haraldmaida** [intellij-rust/intellij-rust#5555] opened 2020-06-11 19:05 UTC
## Problem description

I get a type mismatch error for shift operators (std::ops::Shl, std::opsShr) when the left-hand-side and right-hand-side of the operators are not of the same type.

## Steps to reproduce

```rust
fn shl(n: u8) -> u32 {
    1 << n
}

fn shr(n: u8) -> u32 {
    !1 >> n
}
```
both function give the error:

mismatched types [E0308] expected `u32`, found `u8`

same problem for any other type combination where lhs and rhs are not of same type.

## Environment

* **IntelliJ Rust plugin version: 0.2.123.3132-201**
* **Rust toolchain version: stable 1.44.0**
* **IDE name and version: IntelliJ IDEA Ultimate 2020.1.2**
* **Operating system: Windows 10 Pro 2004**

**Comment by Undin** [comment] 2020-06-11 20:54
Try new macro expansion engine. See #3628 for details

**Comment by Undin** [comment] 2020-06-11 20:54
Duplicate of #5346

**Closed by Undin** 2020-06-11 20:54 UTC
Labels: bug, subsystem::macros, subsystem::type inference & resolve

**Comment by haraldmaida** [comment] 2020-06-12 15:59
Thanks for the very quick response! I switched to the new macro expansion engine. This solves the problem.
