### ISSUE TITLE
'Self convention' inspection is wrong

### ISSUE THREAD

**Issue by mahkoh** [intellij-rust/intellij-rust#7696] opened 2021-08-17 14:35 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4056-212
* **Rust toolchain version:** 1.54.0 (a178d0322 2021-07-26) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.2 (CL-212.4746.93)
* **Operating system:** Linux 5.13.8-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

![2021-08-17-163118_911x89_scrot](https://user-images.githubusercontent.com/1882250/129745804-8761300c-3011-4126-80db-2590035cb0e6.png)

https://doc.rust-lang.org/stable/std/?search=get_mut

## Steps to reproduce

See above.

```rust
struct X {}

impl X {
    fn get_mut_something<T: 'static>(&mut self) -> i32{
        return 566;
    }
}
```

**Comment by Kobzol** [comment] 2021-08-18 07:29
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/7475. Should be fixed by https://github.com/intellij-rust/intellij-rust/pull/7557.

**Closed by Kobzol** 2021-08-18 07:29 UTC
Labels: subsystem::code insight, duplicate
