### ISSUE TITLE
std::os::windows not displayed in completion popup

### ISSUE THREAD

**Issue by Slimig** [intellij-rust/intellij-rust#6244] opened 2020-10-12 15:24 UTC
## Environment

* **IntelliJ Rust plugin version: 0.3.131.3366-201**
* **Rust toolchain version: 1.47.0**
* **IDE name and version: IntelliJ IDEA 2020.1.1 (Community Edition)**
* **Operating system: Windows 10**

## Problem description
When I am typing std::os it only shows raw as completion
![Screenshot_542 1](https://user-images.githubusercontent.com/41162644/95763716-b5923480-0caf-11eb-84ee-7192449f3edf.png)

**Comment by Undin** [comment] 2020-10-12 15:35
Duplicate of #5881

**Closed by Undin** 2020-10-12 15:35 UTC
Labels: subsystem::type inference & name resolution
