### ISSUE TITLE
Follow relative Markdown reference links in stdlib documentation

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#667] opened 2016-09-14 00:16 UTC
Currently the Rust stdlib documentation uses a lot of relative references in the Markdown comments.  The fact that `intellij-rust` recognizes that they are links and tries to resolve them is very promising, but currently they do not resolve correctly.

If we consider [`Box`](https://doc.rust-lang.org/std/boxed/struct.Box.html), note the relative path `../../std/boxed/index.html`. 

``` rust
/// A pointer type for heap allocation.
///
/// See the [module-level documentation](../../std/boxed/index.html) for more.
#[lang = "owned_box"]
#[stable(feature = "rust1", since = "1.0.0")]
pub struct Box<T: ?Sized>(Unique<T>);
```

![box-doc](https://cloud.githubusercontent.com/assets/10340167/18495745/5951a8de-79ee-11e6-800f-b3dfffde5735.png)

Clinking the link results in:

![box-link-error](https://cloud.githubusercontent.com/assets/10340167/18495748/6186093c-79ee-11e6-8633-6d62a891cdd7.png)

 Could this somehow be translated into:
- `https://doc.rust-lang.org/std/boxed/index.html`

I think this could be a powerful tool, especially for those new to Rust and browsing documentation as they develop.

**Comment by mkaput** [comment] 2016-09-14 07:39
Unfortunately, we don't do any detection, we only highlight them :( The problem is, rustdoc links haven't been standardised yet afaik.

**Comment by Kobzol** [comment] 2020-05-14 15:02
@Undin it seems to me that stdlib links (both relative and absolute) work in quick documentation. Is this issue resolved or is the plan to also support them in normal documentation comments?

**Comment by Undin** [comment] 2020-05-14 15:57
@Kobzol we still can't resolve some links. For example, you can check `Eq` link in `HashMap` documentation
In general, the plugin can't resolve relative links when both documentation owner and link target are re-exported and link uses path between reexported names
But it's a more narrow thing so I think we cal close this issue and open another one with more specific problem

**Comment by Undin** [comment] 2020-05-14 16:37
In general, link resolution works. Known bug is filed in #5374

**Closed by Undin** 2020-05-14 16:37 UTC
Labels: bug, subsystem::qdoc
