### ISSUE TITLE
Context actions import displays all options same

### ISSUE THREAD

**Issue by AnickaBurova** [intellij-rust/intellij-rust#7609] opened 2021-07-29 07:40 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.151.3997-212
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.2 (CL-212.4746.93)
* **Operating system:** Linux 5.13.5-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
All suggestions in "import" from "context actions" are displayed as same, but when actually choosing one, they give different "use ...".

## Steps to reproduce
Have multiple types of a same name. (like Duration in std::time, tokio::time...)

![image](https://user-images.githubusercontent.com/7688984/127451164-b0ddcea0-2837-4c7d-ad7b-032c35a1bbc0.png)

**Comment by vlad20012** [comment] 2021-08-03 12:33
I can't reproduce
![image](https://user-images.githubusercontent.com/3221931/128016086-32165d49-4218-4918-a1ff-62ddc520d7c6.png)

Could you please list your `Cargo.toml`  dependencies?

**Comment by vtimonin** [comment] 2021-08-03 13:04
No, try to fix an import error, not use autocomplete.

I can reproduce it with parking_lot import:
![image](https://user-images.githubusercontent.com/6225825/128019860-fc88e3f3-e63b-4d89-be3b-936999d15b40.png)

Error:
![image](https://user-images.githubusercontent.com/6225825/128020236-f6277df2-1afe-4452-9a16-050c064e7232.png)

**Comment by vlad20012** [comment] 2021-08-03 13:07
I've reproduced. Thanks!

![image](https://user-images.githubusercontent.com/3221931/128020679-e6fb1caf-421d-4aa5-8cad-15320e10431e.png)

**Comment by vlad20012** [comment] 2021-08-03 13:25
This regressed in 2021.2 IDEs. Still works in 2021.1

**Comment by vlad20012** [comment] 2021-08-03 14:10
@vtimonin, there is a workaround. Press Ctrl + Shift + A, type "Registry...", find there `psi.element.list.cell.renderer.background` key and uncheck the checkbox next to it

**Comment by vtimonin** [comment] 2021-08-03 15:59
Yes, it did the trick, thanks!

**Comment by 0x7FFFFFFFFFFFFFFF** [comment] 2021-08-09 14:47
> @vtimonin, there is a workaround. Press Ctrl + Shift + A, type "Registry...", find there `psi.element.list.cell.renderer.background` key and uncheck the checkbox next to it

This trick is so useful. Why not make it default unchecked?

**Comment by vlad20012** [comment] 2021-08-10 12:40
The issue is fixed in the nightly plugin. You can try it now (see [instructions](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly))

Please, don't forget to change `psi.element.list.cell.renderer.background` registry option to the default value after that.

@AnickaBurova, @vtimonin, @0x7FFFFFFFFFFFFFFF, @magnusja, @terbshaeusser

**Closed by vlad20012** 2021-08-10 12:40 UTC
Labels: bug, subsystem::code insight::auto import
