### ISSUE TITLE
`#![cfg(target_os="android")]` breaks type hints

### ISSUE THREAD

**Issue by cherryleafroad** [intellij-rust/intellij-rust#7085] opened 2021-04-10 00:32 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.144.3766-211
* **Rust toolchain version:** 1.53.0-nightly (07e0e2ec2 2021-03-24) x86_64-pc-windows-msvc
* **IDE name and version:** PyCharm 2021.1 Professional Edition (PY-211.6693.115)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
If you put `#![cfg(target_os="android")]` at the top of the file, then all type hints in the file break and won't come back. Only a restart (and removing the line) fixes it.

From what I can tell `#![cfg(target_os="windows")]` doesn't break it. I only tested these 2 however

## Steps to reproduce
- Put `#![cfg(target_os="android")]` at the top of the file (or equivalent, I believe it will happen with any similar line.
- Type hints stop working.
- Only way to solve it is to restart the IDE and make sure the line is gone (or commented)

**Comment by Undin** [comment] 2021-04-12 09:59
@cherryleafroad Thanks for the report!
I suppose your issue consists of two different ones:
- a bug with addition/removing file-level cfg attributes. It's already reported in #7039.
- absence of some code insight features for `cfg(target_os="android")` - currently, the plugin evaluates cfg attributes based only on cfg options of your host system (that's why everything works with `#![cfg(target_os="windows")]`). See #5183

So I close the issue since it's a duplicate of known issues

**Closed by Undin** 2021-04-12 09:59 UTC
Labels: bug, subsystem::cfg
