### ISSUE TITLE
Debugging broken for 2021.3.3 and 2022.1 EAP

### ISSUE THREAD

**Issue by ralfbiedert** [intellij-rust/intellij-rust#8558] opened 2022-02-14 15:04 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.165.4438-221
* **Rust toolchain version:** 1.60.0-nightly (1e12aef3f 2022-02-13) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.1 EAP (CL-221.4165.77)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Since today's update debug breakpoints don't seem to work anymore. For example. when running a unit test via the drop down

![image](https://user-images.githubusercontent.com/301288/153888537-69b492c1-a084-4f00-9aab-23570db81fbe.png)

the break point gets ignored and the test just runs normally:

![image](https://user-images.githubusercontent.com/301288/153888684-392ea49f-5e7f-4586-8889-5e3b50ceadfe.png)

I could reproduce this with

- 2022.1 EAP
- 2021.3.3
- Rust Nightly (latest)
- Rust Nightly (2022-01-01)

**Comment by Undin** [comment] 2022-02-14 15:08
Duplicate of #8526

**Closed by Undin** 2022-02-14 15:08 UTC
Labels: subsystem::debugger, bug
