### ISSUE TITLE
Autocomplete not working with struct fields on some packages 

### ISSUE THREAD

**Issue by likeabbas** [intellij-rust/intellij-rust#8380] opened 2022-01-09 21:41 UTC
I am still this issue where struct fields associated with Impls aren't being highlighted for cargo packages like `nalgebra`

The example I'm working with is [Vector3](https://docs.rs/nalgebra/0.10.1/nalgebra/struct.Vector3.html) where I'm trying to access the `x`, `y`, and `z` fields. 

* rust version 1.60.0-nightly (a7e2e3396 2022-01-08)
* CLion rust plugin  0.4.163.4354-213-nightly
* CLion 2021.3.2 Build #CL-213.6461.75
* MacOs Catalina 10.15.7 
<img width="407" alt="Screen Shot 2022-01-09 at 4 37 19 PM" src="https://user-images.githubusercontent.com/6827281/148702002-456d63a5-aff4-48a1-bdcd-ad2e581ea023.png">

_Originally posted by @likeabbas in https://github.com/intellij-rust/intellij-rust/issues/4277#issuecomment-1008429102_

**Comment by dima74** [comment] 2022-09-07 01:07
@likeabbas do you still experience the problem? Looks like it was fixed some time ago

**Comment by likeabbas** [comment] 2022-09-07 17:58
@dima74 still exists, and others see it

https://github.com/intellij-rust/intellij-rust/issues/9324

**Comment by dima74** [comment] 2022-09-07 18:43
@likeabbas Yeah we definitely have some other bugs like #9324, #7281, etc. I mean do you still experience this particular bug described in this issue? I can't reproduce it with latest plugin version

**Comment by likeabbas** [comment] 2022-09-07 18:47
@dima74 I just updated the plugin and now this bug seems fixed! Thank you.

**Comment by dima74** [comment] 2022-09-07 19:38
Nice, I will close this issue then, please subscribe to #9324 and #7281 for updates

**Closed by dima74** 2022-09-07 19:38 UTC
Labels: bug, subsystem::сompletion
