### ISSUE TITLE
code completion for external crate does not work

### ISSUE THREAD

**Issue by kgignatyev** [intellij-rust/intellij-rust#5268] opened 2020-04-21 14:16 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.120.2202-201
* **Rust toolchain version:** 1.44.0-nightly (dbf8b6bf1 2020-04-19) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.1 Ultimate Edition (IU-201.6668.121)
* **Operating system:** macOS 10.14.6

## Problem description

code completion does not work for external crates, only some standard methods show up, see problem.png in the archive

## Steps to reproduce

open archive as project and try to see methods of client or builder from reqwest crate
[problem.zip](https://github.com/intellij-rust/intellij-rust/files/4510520/problem.zip)

**Comment by Undin** [comment] 2020-04-27 07:14
Try to enable new macro expansion engine (see #3628 for details).

Duplicate of #4679

**Closed by Undin** 2020-04-27 07:14 UTC
Labels: bug, duplicate, subsystem::macros, subsystem::type inference & resolve
