### ISSUE TITLE
Some types do not autocomplete when autocomplete otherwise works

### ISSUE THREAD

**Issue by jen20** [intellij-rust/intellij-rust#4421] opened 2019-09-22 14:22 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.105.2133-192
* **Rust toolchain version:** 1.39.0-nightly (eceec57f7 2019-09-18)
* **IDE name and version:** CLion 2019.2.2 Build #CL-192.6603.37
* **Operating system:** Windows or MacOS X

## Problem description

The use of certain crates fails to provide autocompletion or inline type annotation hints for some of their types. Autocomplete works with some other types in those crates, and with those from other crates and the standard library.

## Steps to reproduce

`Cargo.toml`:

```toml
[package]
name = "threading-spike4"
version = "0.1.0"
authors = ["Test"]
edition = "2018"

[dependencies]
tokio = "0.2.0-alpha.5"
```

`main.rs`:

```rust
use tokio::runtime::Builder;

fn main() {
    // "Builder" provides no completion options for most functions, and no type hint is displayed
    let runtime = Builder::new().build().unwrap();
    runtime.block_on(async {});
}
```

As can be seen in the following screenshot, there is also no type annotation hints on the `runtime` variable.

![image](https://user-images.githubusercontent.com/548524/65389301-bd9dd000-dd4c-11e9-8b51-885ee503aec2.png)

**Comment by ufoscout** [comment] 2019-12-31 09:45
The same issue is present with reqwest 0.10.
Could this be due to the autocomplete not taking into account the features of a dependency?

**Comment by nrailgun** [comment] 2020-01-26 16:08
same problem.

**Comment by gerritsangel** [comment] 2020-02-20 13:05
This has definetely to do with the features. For example, using the blocking API from reqwest 0.10.0 has no autocompletion.

If you change

```rust
#[cfg(feature = "blocking")]
pub mod blocking;
```

to
```rust
pub mod blocking;
```

and remove the 
```rust
if_hyper! {
}
```

macro in it's lib.rs, the autocompletion works without problems.

**Comment by Undin** [comment] 2020-02-20 13:42
What version of plugin do you use?
With latest stable version it works out the box for me

**Comment by Undin** [comment] 2020-02-20 13:48
It's fixed in #4914 and build with the fix is already published.
I close this issue as a duplicate of #4627 because they have the same reason

**Closed by Undin** 2020-02-20 13:48 UTC
Labels: bug, subsystem:macros, subsystem:type inference & resolve

**Comment by gerritsangel** [comment] 2020-02-20 14:02
Hi,

I'm using Clion with 2019.3 with IntelliJ Rust 0.2.116.2163-193.

The trick was to use the new experimental engine. I thought it was only for speed, but also gives new features :) Thanks!

**Comment by ufoscout** [comment] 2020-02-20 14:04
It still fails for me.

Intellij Community 2019.3.3
Rust plugin 0.2.116.2163-193
Rustc 1.41.0

![Screenshot_20200220_150023](https://user-images.githubusercontent.com/960885/74940798-43a06e80-53f2-11ea-97db-704b8a260f70.png)

**Comment by Undin** [comment] 2020-02-20 14:16
@ufoscout is experimental macro expansion engine enabled?
If no, see #3628 for more details

**Comment by ufoscout** [comment] 2020-02-20 14:18
I confirm that the experimental engine fixes the issue for me too

**Comment by Undin** [comment] 2020-02-20 14:20
@gerritsangel @ufoscout Great!
