### ISSUE TITLE
Malformed URL: psi_element://crate/path/to/element/index.html when click link on doc comment

### ISSUE THREAD

**Issue by anatawa12** [intellij-rust/intellij-rust#8533] opened 2022-02-09 09:04 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.164.4409-213
* **Rust toolchain version:** 1.57.0 (f1edd0429 2021-11-29) aarch64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.1 EAP Ultimate Edition (IU-221.3427.89)
* **Operating system:** macOS 12.1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

When I click `` [`format::strftime` module](../format/strftime/index.html)``, `Browser Error` `Malformed URL: psi_element://chrono/naive/format/strftime/index.html` was happened.

I think IDE should open `src/format/strftime.rs`.

## Steps to reproduce

1. create crate that depends on `chrono` 0.4 I'm using 0.4.19.
2. go to document comment of `chrono::datetime::NaiveDateTime::format`
3. click `` `format::strftime` module``

![image](https://user-images.githubusercontent.com/22656849/153161550-ff8d03d2-0cb8-40e3-a535-a46b0b1c1de4.png)
![image](https://user-images.githubusercontent.com/22656849/153161619-065d0d74-30ff-4e57-b21f-fb9f514866b1.png)

**Comment by neonaot** [comment] 2022-02-09 09:28
duplicate of https://github.com/intellij-rust/intellij-rust/issues/8179

**Closed by neonaot** 2022-02-09 09:28 UTC
