### ISSUE TITLE
Fail with maud html template engine

### ISSUE THREAD

**Issue by Yuri6037** [intellij-rust/intellij-rust#8245] opened 2021-12-09 12:18 UTC
## Environment

* **IntelliJ Rust plugin version: 0.4.161.4292-212**
* **Rust toolchain version: rustc 1.56.1 (59eed8a2a 2021-11-01)**
* **IDE name and version: CLion 2021.2.2**
* **Operating system: Pop!_OS 21.04 (Ubuntu derivative)**

## Problem description

False E0308 (expected `Markup` found `()`)

## Steps to reproduce

In your Cargo.toml put `maud = "0.23.0"` in `[dependencies]` section.

```rust
use maud::{html, Markup};

fn html() -> Markup
{
    html! {
        div .msg {

        }
    }
}
```

You can test by `cargo build` and you'll see it builds fine, so this is only IDEA failing to build it.

**Comment by vlad20012** [comment] 2021-12-10 09:59
Try to enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` experimental feature via the corresponding dialog. To open the dialog, just invoke `Help | Find Action` action and type `Experimental features`

**Comment by Yuri6037** [comment] 2021-12-11 15:45
Just tried now that I have a bit a spare time and apart from heating up a bit the CPU when opening the IDE it didn't do much the false error is still here.

**Comment by x4m3** [comment] 2022-02-07 01:26
I had the same bug as @Yuri6037, in the `Experiemental features` I enabled `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc`, deleted the `target/` folder of my project, closed and reopened the project in clion and it worked.

thanks for the tip @vlad20012, do you know if/when those features will be enabled by default?

**Comment by Maksim20023** [comment] 2023-07-26 18:23
I'm closing this ticket because the issue does not reproduce in the current environment (CLion 2023.2 Build #CL-232.8660.186, Rust plugin 0.4.199.5415-232).
If this issue still reproduces for you, please reopen the ticket.

**Closed by Maksim20023** 2023-07-26 18:23 UTC
