### ISSUE TITLE
Unresolved reference for {i,u}{8,16,32,64}::MAX constants

### ISSUE THREAD

**Issue by Mottl** [intellij-rust/intellij-rust#10672] opened 2023-07-12 07:22 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.198.5409-231
* **Rust toolchain version:** rustc 1.70.0 (90c541806 2023-05-31)
* **IDE name and version:** CLion 2023.1.4
* **Operating system:** macOS Monterey

## Problem description
`i64::MAX` and other `{i,u}{8,16,32,64}::MAX` constants are marked as `Unresolved reference: MAX`

## Steps to reproduce
<img width="400" alt="screenshot" src="https://github.com/intellij-rust/intellij-rust/assets/4404433/1a1ded65-680a-45d5-840a-8f00c30b1323">

**Comment by Maksim20023** [comment] 2023-07-12 13:33
Hi! Thank you for reaching us. This issue is already known to us and your ticket duplicates an existing one: [GitHub 10499](https://github.com/intellij-rust/intellij-rust/issues/10499) Unfortunately, I currently don't have  information about ETA for this issue.
When we have any new information about this issue, we will add a reply to GitHub 10499 ticket.

**Comment by Maksim20023** [comment] 2023-07-12 13:35
Duplicate of #10499

**Comment by Maksim20023** [comment] 2023-07-25 10:25
Hi! I'm closing this ticket because the issue is fixed (please see a fix [Pull 10688](https://github.com/intellij-rust/intellij-rust/pull/10688)). This fix is included in the Rust plugin 0.4.199.5414 version. Please make sure that your installed plugin is [up-to-date](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#update).  If this issue still reproduces for you, please reopen the ticket.

**Closed by Maksim20023** 2023-07-25 10:25 UTC
