### ISSUE TITLE
Red underline despite working program

### ISSUE THREAD

**Issue by kebiro** [intellij-rust/intellij-rust#7822] opened 2021-09-09 23:58 UTC
## Environment

* **IntelliJ Rust plugin version:**
* 0.3.140.3644-202
* **Rust toolchain version:**
* 1.51.0
* **IDE name and version:**
* IntelliJ Idea 2020.2.1 (Community Edition)
* **Operating system:**
* Windows 10

## Problem description

IDE claims errors (code is underlined red), but executing the program actually works.

Related issue: https://github.com/intellij-rust/intellij-rust/issues/7820
- Invalidating the cache and restarting the IDE did not change anything

## Steps to reproduce

This is the file in question, it's from a tutorial. I fear you may have to clone the whole repo in case the descriptions and screenshots down below don't suffice:
https://github.com/sotrh/learn-wgpu/blob/master/code/intermediate/tutorial11-normals/src/model.rs

Relevant code sections are in-between lines 190 and 250:
```Rust
let pos0: cgmath::Vector3<_> = v0.position.into();
let pos1: cgmath::Vector3<_> = v1.position.into();
let pos2: cgmath::Vector3<_> = v2.position.into();

let uv0: cgmath::Vector2<_> = v0.tex_coords.into();
let uv1: cgmath::Vector2<_> = v1.tex_coords.into();
let uv2: cgmath::Vector2<_> = v2.tex_coords.into();

// Calculate the edges of the triangle
let delta_pos1 = pos1 - pos0;
let delta_pos2 = pos2 - pos0; // pos0 underlined red: "Use of moved value"

// This will give us a direction to calculate the
// tangent and bitangent
let delta_uv1 = uv1 - uv0;
let delta_uv2 = uv2 - uv0; // uv0 underlined red: "Use of moved value"
```

```Rust
// The argument to Vector3::from() is underlined red: 
//    "mismatched types [E0308] expected `Vector3<<unknown>>`, found `[f32; 3]` "
vertices[c[0] as usize].tangent = (tangent + cgmath::Vector3::from(vertices[c[0] as usize].tangent)).into();
```

Screenshot:
![image](https://user-images.githubusercontent.com/10946640/132776504-edd3120e-8964-4a8e-8d2a-0d0ae8af3f80.png)

![image](https://user-images.githubusercontent.com/10946640/132776478-355ba327-36fb-426f-b3ae-f80fafa50373.png)

**Comment by Maksim20023** [comment] 2023-07-26 18:36
Hi! I’m closing this ticket because the issue does not reproduce in the current environment (IntelliJ IDEA 2023.2 Build #IU-232.8660.185, Rust plugin 0.4.199.5415-232). If this issue still reproduces for you, please reopen the ticket.

**Closed by Maksim20023** 2023-07-26 18:36 UTC
Labels: subsystem::type inference & name resolution, subsystem::code insight, bug
