### ISSUE TITLE
Filter out code based on feature flags in Cargo.toml

### ISSUE THREAD

**Issue by alexschrod** [intellij-rust/intellij-rust#4395] opened 2019-09-16 11:18 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.106.2736-192-nightly
* **Rust toolchain version:** 1.36.0
* **IDE name and version:** IntelliJ IDEA 2019.2.2 (Community Edition)
* **Operating system:** Windows 10 Home

## Problem description
Some crates come with feature flags that let you enable and disable features (including entire parts of the crate) and that let you pick different versions of features. IntelliJ-Rust seems to completely ignore these flags, and ends up showing no errors when you are using features that in reality are guarded behind feature flags you have not enabled.

## Steps to reproduce
One crate that illustrates these issues well is the `sdl2` crate.

### Struct with different implementations depending on feature flag
For its `Texture` struct, it has two different versions, depending on whether you are using the `unsafe_textures` flag or not:
```rust
#[cfg(feature = "unsafe_textures")]
pub struct Texture { ... }
#[cfg(not(feature = "unsafe_textures"))]
pub struct Texture<'r> { ... }
```

This causes the IntelliJ-Rust plugin to be unable to handle the `Texture` struct at all. When you try to navigate to it, it asks you to pick which one you mean: 
![image](https://user-images.githubusercontent.com/767490/64953097-41a21480-d882-11e9-9ac6-9708c9873980.png)
and if you use it anywhere, you won't be told that the `Texture` struct has been inferred:
![image](https://user-images.githubusercontent.com/767490/64953202-8168fc00-d882-11e9-86eb-2e18fd1b6b2c.png)
(notice the missing `: Texture` annotation on the `let texture = ...` line.)

And obviously, no code completion help whatsoever, either:
![image](https://user-images.githubusercontent.com/767490/64953270-b6754e80-d882-11e9-9804-39f2fa810bfc.png)

### Optional module which gets enabled or disabled depending on the presence of a feature flag
The sdl2 crate has multiple optional dependencies on SDL2 features, for instance, there's a `ttf` flag that enables or disables the support for TrueType fonts. In its lib.rs, it has this little line:
```rust
#[cfg(feature = "ttf")]
pub mod ttf;
```

Does removing that feature from Cargo.toml cause IntelliJ-Rust to show errors wherever `sdl2::ttf` items are being used? Nope! It looks like everything is a-ok:
![image](https://user-images.githubusercontent.com/767490/64953763-f426a700-d883-11e9-8541-5a13c8766682.png)
This code should be littered with errors about using things that don't exist. Why isn't IntelliJ figuratively screaming at me here?

**Comment by Undin** [comment] 2019-09-16 21:44
Duplicate of #1191

**Closed by Undin** 2019-09-16 21:44 UTC
Labels: cfg, duplicate, feature

**Comment by alexschrod** [comment] 2019-09-17 07:32
@Undin Thanks, I tried looking for dupes before submitting this, but since that one didn't have "feature" and/or "flag(s)" in it, I didn't find it.

**Comment by vlad20012** [comment] 2019-09-17 10:45
@alexschrod We have a very early experimental for cfg attributes. You can try ctrl+shift+A "Registry..." and check there "rust.cfg.attributes.enabled"
![image](https://user-images.githubusercontent.com/3221931/65034982-ce1b0880-d950-11e9-8aae-78326e32c6f9.png)

Currently, we don't take into account features enabled in Cargo.toml, but consider all features as enabled. It should solve the issue with `sdl2`, because `#[cfg(not(feature = "..."))]` will be excluded from the name resolution.

**Comment by alexschrod** [comment] 2019-09-17 16:22
@vlad20012 Nice, that does indeed "solve" my problem for now. Thanks for the tip!
