### ISSUE TITLE
Rider - installing plugin removes main Debugger view from settings

### ISSUE THREAD

**Issue by Eragra3** [intellij-rust/intellij-rust#8729] opened 2022-04-07 11:06 UTC
## Environment

* **IntelliJ Rust plugin version:** `0.4.167.4525-213`
* **Rust toolchain version:** `stable-x86_64-pc-windows-msvc 1.57.0`
* **IDE name and version:** `Rider 2021.3.3`
* **Operating system:** `Windows 10 Enterprise`

## Problem description
Installing Rust plugin removes main `Debugger` view from Rider settings.

## Steps to reproduce

1. Install Rust plugin
2. Go to `Settings` -> `Build, Execution, Deployment` -> `Debugger`

Without plugin:
![without_rust](https://user-images.githubusercontent.com/9082983/162185171-17c7c3a0-8f88-48be-a00b-da85ad7e00d1.png)

With plugin:
![with_rust](https://user-images.githubusercontent.com/9082983/162185196-2ecda469-8add-4b17-b162-6facf66dc417.png)

The issue is quite annoying, because I have to switch plugin on and off depending on wheter I'm doing C# or Rust.
I suspect Rider has slightly different debugger settings hierarchy?

**Comment by Eragra3** [comment] 2022-04-07 11:08
It also seems to reset all debugger settings, so I have to set it again.

**Comment by Undin** [comment] 2022-04-07 11:25
Duplicate of #8622
Fixed in #8666

The fix is already available in [nightly](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly) and will be published in stable build next week

**Closed by Undin** 2022-04-07 11:25 UTC
Labels: subsystem::debugger, bug

**Comment by Eragra3** [comment] 2022-04-07 11:31
Thanks, sorry I was only looking for open issues.
