### ISSUE TITLE
Fails to parse nested touples

### ISSUE THREAD

**Issue by ctron** [intellij-rust/intellij-rust#6263] opened 2020-10-16 06:37 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.132.3395-202
* **Rust toolchain version:** 1.47.0 (18bf6b4f0 2020-10-07) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.2.3 (CL-202.7319.72)
* **Operating system:** Linux 5.8.11-200.fc32.x86_64

## Problem description

The following code is valid Rust, and works:

~~~rust
pub struct Bar(pub i32);
pub struct Foo(pub Bar);

fn main() {

  let foo = Foo(Bar(42));
  let x = foo.0.0;

  println!("{}", x);

}
~~~

However, the IntelliJ shows an error:

![image](https://user-images.githubusercontent.com/202474/96221310-a8fd2d00-0f8a-11eb-8c7d-4e6682d49cb9.png)

## Steps to reproduce

Use the code above.

**Comment by vlad20012** [comment] 2020-10-16 06:43
The issue is fixed in the nightly plugin. You can try it now (see [instructions](https://intellij-rust.github.io/install.html))

**Closed by vlad20012** 2020-10-16 06:43 UTC
