### ISSUE TITLE
False positive Display missing error on closures

### ISSUE THREAD

**Issue by LucaPaterlini** [intellij-rust/intellij-rust#10087] opened 2023-02-06 13:59 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.187.5175-223
* **Rust toolchain version:** 1.67.0 (fc594f156 2023-01-24) aarch64-apple-darwin
* **IDE name and version:** GoLand 2022.3.2 (GO-223.8617.58)
* **Operating system:** macOS 13.2
* **Macro expansion:** enabled

## Problem description

// this code actually runs but the ide show simple_closure underscored with red with the following error
/// `()` doesn't implement `Display` (required by {})
fn main(){
    let simple_closure = | x|{x};
    println!("hello {}",simple_closure(5))
}

## Steps to reproduce
1. create a new project in rust
2. copy paste the 2 lines mentioned in the main

**Comment by neonaot** [comment] 2023-02-08 13:02
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/6548

**Closed by neonaot** 2023-02-08 13:02 UTC
