### ISSUE TITLE
Importing items as `_` reports error "identifier expected"

### ISSUE THREAD

**Issue by rakenodiax** [intellij-rust/intellij-rust#3469] opened 2019-03-03 11:46 UTC
## Environment

* **Intellij-Rust plugin version:** `v0.2.92.2116-183`
* **Rust toolchain version:** rustc 1.33.0 (2aa4c46cf 2019-02-28)
* **IDE name and version:** IntelliJ IDEA Community Edition IntelliJ IDEA 2018.3.5 (Community Edition), Build #IC-183.5912.21, built on February 26, 2019
* **Operating system:** macOS 10.13.6

## Problem description
Rust 1.33.0 now supports importing an item as `_`: [changelog](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1330-2019-02-28).

### Expected behavior
Import an item (usually a trait) into scope without an error.

### Observed behavior
`use module::identifier as _;` is marked as an error: "identifier expected, got '_'"

## Steps to reproduce
```rust
pub mod foo {
    pub struct Bar;
}

use foo::Bar as _;
```

**Comment by mchernyavsky** [comment] 2019-03-13 18:19
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/2496.

**Closed by mchernyavsky** 2019-03-13 18:19 UTC
Labels: duplicate, feature, rust
