### ISSUE TITLE
Impossible to work with deep level of conditions

### ISSUE THREAD

**Issue by e-oz** [intellij-rust/intellij-rust#230] opened 2016-02-01 22:23 UTC
Try to write code like this:
https://gist.github.com/e-oz/74fb35b442062c3bc08a

in middle of this code IDE will be unresponsive. Only editable without plugin.

**Comment by matklad** [comment] 2016-02-01 22:58
Looks like something wrong with our parser. Quick profiling shows that `com.intellij.lang.parser.GeneratedParserUtilBase.ErrorState#addExpected` is the culprit. Somehow it is called repeatedly and with `list.size` of about 10000, and it is `O(N^2)` in the length of the `list`.

**Comment by himikof** [comment] 2016-02-01 23:05
I looked into this a bit.
The problem is the rust parser and the unfinished `if` at the line 20. The parser spends LOTS of time in `GeneratedParserUtilBase.reportError`, building huge error strings.
The error building/reporting is called many times from different nesting levels. Interestingly enough, in my testing removing even one level of nesting in the code hides the problem almost completely.

**Comment by alexeykudinkin** [comment] 2016-02-01 23:15
Ouch, @e-oz thanks for the pointing on this! That's happens due to the fact that we're poorly recovering in some cases, and that's one is especially striking.

**Comment by alexeykudinkin** [comment] 2016-02-03 00:57
Should be fixed by `d5b478d`

**Closed by alexeykudinkin** 2016-02-03 00:57 UTC
Labels: fixed
