### ISSUE TITLE
Better generated impls for Debug/Display

### ISSUE THREAD

**Issue by aldanor** [intellij-rust/intellij-rust#5400] opened 2020-05-19 00:18 UTC
(Apologies if this has already been mentioned, but I couldn't find related issues)

Currently, if you have `Debug` or `Display` in scope, and you try to generate a skeleton trait impl for them, you get something like this:

```rust
impl Display for Foo {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        unimplemented!()
    }
}
```

Note that `Formatter` and `Result` must come from `std::fmt` and neither of them is in scope (in fact, in this particular example, intellij-rust tries to guess it wrong and pulls `use static_assertions::_core::fmt::Formatter` into scope).

So you have to go back and fix it manually, the same way every time, so it looks like this:

```rust
use std::fmt::{self, Display};

impl Display for Foo {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        unimplemented!()
    }
}
```

Given that `Debug` / `Display` are so commonly used, could these be special-cased so we get nicer skeleton impls?

**Comment by Kobzol** [comment] 2020-05-19 12:27
I think that this is the same problem as in this issue: https://github.com/intellij-rust/intellij-rust/issues/4979

**Comment by aldanor** [comment] 2020-05-19 12:41
@Kobzol Yea, it's the same one.

I was just wondering if it makes sense to special-case some traits like `Debug` / `Display` (not a whole lot of them suffer from the same problem in the stdlib) since they are so commonly used, and something like the above would get generated.

**Comment by Kobzol** [comment] 2020-12-09 08:49
Closing as a duplicate of https://github.com/intellij-rust/intellij-rust/issues/4979. Probably `Debug`/`Display` will not be special-cased and hopefully the main issue will be solved eventually.

**Closed by Kobzol** 2020-12-09 08:49 UTC
Labels: bug, duplicate, subsystem::refactoring
