### ISSUE TITLE
Unresolved reference `None`

### ISSUE THREAD

**Issue by JakubOnderka** [intellij-rust/intellij-rust#2361] opened 2018-03-09 17:20 UTC
In this code:

```rust
struct Node<'a> {
    depth: u32,
    zero: Option<&'a Node<'a>>,
    one: Option<&'a Node<'a>>,
    value: Option<u32>,
}

impl<'a> Node<'a> {
    pub fn new() -> Self {
        Self {
            depth: 0,
            zero: None,
            one: None,
            value: None,
        }
    }
}

fn main() {
    let root = Node::new();
    println!("{}", root.value.is_some());
}
```

None in `new` function are marked as Unresolved, but `cargo check` show just warnings for never used fields.

<img width="368" alt="unresolver reference" src="https://user-images.githubusercontent.com/163343/37220287-7410b6fa-23c6-11e8-81dd-b82a5a402980.png">

**Comment by Undin** [comment] 2018-03-09 18:18
It's interesting bug)
Real problem is that type of `Self` is not inferred, it doesn't allow to make correct resolve and finally `Unresolved reference` inspection highlight `None`

Workaround: use struct name instead of `Self` in constructor
```rust
Node {
    depth: 0,
    zero: None,
    one: None,
    value: None,
}
```

**Comment by kumbayo** [comment] 2018-03-10 17:43
This is likely the same problem as #1992

**Comment by Undin** [comment] 2018-03-10 17:46
@kumbayo Yep, you are definitely right! I forgot about that issue.

**Comment by Undin** [comment] 2018-03-10 17:46
Duplicate of #1992

**Comment by Undin** [comment] 2018-03-17 13:46
Found out that this bug is not duplicate of #1992 
So I reopen it

**Comment by ForsakenHarmony** [comment] 2018-03-21 22:43
seems like they are connected but not the same

**Closed** 2018-04-05 10:10 UTC
Labels: bug, type inference & resolve
