### ISSUE TITLE
unable to resolve reference for traits with async_trait attribute using * import

### ISSUE THREAD

**Issue by Sibz** [intellij-rust/intellij-rust#9141] opened 2022-08-01 06:05 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.177.4785-222-nightly
* **Rust toolchain version:** 1.61.0-nightly (3c17c84a3 2022-03-21) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.2 (CL-222.3345.126)
* **Operating system:** Windows 11 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
The Tr trait is in the super module, and that is included using `*`, however clion says it's unresolved
![image](https://user-images.githubusercontent.com/12050358/182082251-defb00a3-ec75-42b7-b38b-4f688ca7824f.png)
putting direct import `super::Tr;` works

Also broken when importing else where:
![image](https://user-images.githubusercontent.com/12050358/182082472-20914b65-4947-4a54-ac70-bce50a1e5efc.png)

## Steps to reproduce
code:
```rust
mod test_it
{
    
    #[async_trait::async_trait(?Send)]
    pub trait Tr: Sized + 'static
    {
        async fn ab();
    }
}
use test_it::*;
pub struct Ba;
impl Tr for Ba
{
}
```

**Comment by dima74** [comment] 2022-08-01 11:55
I guess it is a duplicate of #8768 and will be fixed by #9080

**Closed** 2022-08-08 07:08 UTC
Labels: subsystem::type inference & name resolution, bug, subsystem::macros
