### ISSUE TITLE
the trait bound `Self: std::marker::Sized` is not satisfied [E0277] false positive

### ISSUE THREAD

**Issue by lovasoa** [intellij-rust/intellij-rust#6991] opened 2021-03-19 09:05 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.143.3737-203
* **Rust toolchain version:** 1.50
* **IDE name and version:** IntelliJ

## Problem description

The following code raises an error when it shouldn't: 

<img width="772" alt="image" src="https://user-images.githubusercontent.com/552629/111756159-31fdf480-889a-11eb-8a42-59f41694307d.png">

The plugin ignores the where clause and thinks that `Self` is not sized

## Steps to reproduce

```rust
trait T {
    fn f(self) -> Self
    where
        Self: Sized,
    {
        self
    }
}
```

**Comment by qiujiangkun** [comment] 2021-07-08 16:09
I have met the same problem recently.

**Comment by Seeker14491** [comment] 2021-07-22 23:53
This looks like a duplicate of #2530.

**Comment by qiujiangkun** [comment] 2021-07-23 16:23
It appears in the latest version. Maybe someone can do a bisection?

**Comment by afetisov** [comment] 2021-11-29 14:23
Surprisingly, the bug doesn't happen if Self isn't the last generic parameter:

```rust
trait T {
    fn f(self) -> Foo<Self, u32> // no error
        where
            Self: Sized,
    {
        Foo(self, 0)
    }
}

struct Foo<A, B>(A, B);
```

```rust
trait T {
    fn f(self) -> Foo<u32, Self, u32> // no error
        where
            Self: Sized,
    {
        Foo(0, self, 0)
    }
}

struct Foo<A, B, C>(A, B, C);
```

But if Self is last, the error triggers:
```rust
trait T {
    fn f(self) -> Foo<u32, u32, Self> // error E0277
        where
            Self: Sized,
    {
        Foo(0, 0, self)
    }
}

struct Foo<A, B, C>(A, B, C);
```

**Closed** 2021-12-13 17:38 UTC
Labels: subsystem::type inference & name resolution, subsystem::code insight, bug
