### ISSUE TITLE
Wrong inferred return type for warp filter when futures::StreamExt is imported

### ISSUE THREAD

**Issue by msdinit** [intellij-rust/intellij-rust#5721] opened 2020-07-10 15:37 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.125.3191-201
* **IDE name and version:** CLion 2020.1.2

## Problem description
Wrong inferred return type for the `test` function below. Interestingly, type inference is only wrong when `use futures::StreamExt;` is present - when I delete that import, code no longer highlighted as returning wrong type.

The error is:
```
mismatched types [E0308] expected `BoxedFilter<(())>`, found `Pin<Box<dyn Stream<Item=<unknown>>+Send>>` 
```

## Steps to reproduce
Uncomment the first line and IDE immediately highlights function body with error that return type is wrong.
Comment it out again, and function body is no longer highlighted
```rust
// use futures::StreamExt;
use warp::Filter;
use warp::filters::BoxedFilter;

pub fn test() -> BoxedFilter<((), )> {
    warp::any()
        .and_then(
            || async move {
                Err(warp::reject::not_found())
            })
        .boxed()
}

fn main() {}
```

**Comment by Maksim20023** [comment] 2023-07-27 17:32
Hi! I’m closing this ticket because the issue does not reproduce in the current environment (CLion 2023.2 Build #CL-232.8660.186, Rust plugin 0.4.199.5415-232). If this issue still reproduces for you, please reopen the ticket.

**Closed by Maksim20023** 2023-07-27 17:32 UTC
Labels: subsystem::type inference & name resolution, bug
