### ISSUE TITLE
Unable to download debugger

### ISSUE THREAD

**Issue by deimosfr** [intellij-rust/intellij-rust#6142] opened 2020-09-21 07:22 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.130.3337-202
* **Rust toolchain version:** 1.46.0
* **IDE name and version:** Intellij IDEA ultimate 2020.2
* **Operating system:** Arch Linux

## Problem description

While trying to run in debug mode, it asks me to download the debugger. I got a window saying:
```
Unable to run debugger
Debugger is not loaded yet
```
I have a button "Download" and when I click on it, I got this stacktrace:

```
2020-09-21 07:06:16,519 [  34286]  ERROR - pplication.impl.LaterInvocator - Total weight must be a positive number: 0 
java.lang.IllegalArgumentException: Total weight must be a positive number: 0
	at com.intellij.util.progress.ConcurrentTasksProgressManager.<init>(ConcurrentTasksProgressManager.java:24)
	at com.intellij.util.download.impl.FileDownloaderImpl.download(FileDownloaderImpl.java:201)
	at org.rust.debugger.RsDebuggerToolchainService.downloadAndUnarchive(RsDebuggerToolchainService.kt:146)
	at org.rust.debugger.RsDebuggerToolchainService.downloadDebuggerSynchronously(RsDebuggerToolchainService.kt:95)
	at org.rust.debugger.RsDebuggerToolchainService.access$downloadDebuggerSynchronously(RsDebuggerToolchainService.kt:34)
	at org.rust.debugger.RsDebuggerToolchainService$downloadDebugger$result$1.compute(RsDebuggerToolchainService.kt:67)
	at org.rust.debugger.RsDebuggerToolchainService$downloadDebugger$result$1.compute(RsDebuggerToolchainService.kt:34)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:490)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:652)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:649)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:649)
	at java.lang.Thread.run(Thread.java:748)
2020-09-21 07:06:16,522 [  34289]  ERROR - pplication.impl.LaterInvocator - IntelliJ IDEA 2020.2.2  Build #IU-202.7319.50 
2020-09-21 07:06:16,522 [  34289]  ERROR - pplication.impl.LaterInvocator - JDK: 1.8.0_265; VM: OpenJDK 64-Bit Server VM; Vendor: Oracle Corporation 
2020-09-21 07:06:16,522 [  34289]  ERROR - pplication.impl.LaterInvocator - OS: Linux 
2020-09-21 07:06:16,523 [  34290]  ERROR - pplication.impl.LaterInvocator - Plugin to blame: Rust version: 0.3.130.3337-202 
2020-09-21 07:06:16,523 [  34290]  ERROR - pplication.impl.LaterInvocator - Last Action: Debug 
2020-09-21 08:18:15,731 [4353498]   WARN - com.intellij.util.xmlb.Binding - no accessors for org.jetbrains.kotlin.idea.core.script.configuration.utils.ScriptClassRootsStorage 
2020-09-21 09:13:55,335 [7693102]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting 
2020-09-21 09:15:14,121 [7771888]   WARN - tions.ex.ConfigurableCardPanel - auto-dispose 'Plugins' id=preferences.pluginManager 
```
I tried to:
* Réinstall intellij
* Reset settings
* Reinstall plugins
* Disable all of them and only keep Rust
* Changing runtime java version to 11 and 14

No chance to make it works, it looks like the Download button to get the debugger is silently failing.

## Steps to reproduce

With any kind of codebase, I got this issue. It's only related to Rust debugger, I don't encounter this issue with other languages.

**Comment by Undin** [comment] 2020-09-21 07:27
I suppose it's a duplicate of #5915.
The fix is already in nightly builds (see [instruction](https://intellij-rust.github.io/install#nightly-builds) how to install it). Stable version will be published soon

**Closed by Undin** 2020-09-21 07:27 UTC

**Comment by Undin** [comment] 2020-09-21 09:15
@deimosfr As a workaround, try to delete whole lldb directory. You can find it in settings (see https://github.com/intellij-rust/intellij-rust/issues/5915#issuecomment-691947160)

**Comment by deimosfr** [comment] 2020-09-21 09:55
You're right, it's the same issue, using the nightly build fixed it
