### ISSUE TITLE
Importing items works incorrectly.

### ISSUE THREAD

**Issue by hardskulls** [intellij-rust/intellij-rust#9893] opened 2022-12-12 18:55 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.184.5057-223
* **Rust toolchain version:** 1.65.0 (897e37553 2022-11-02) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2022.3 Community Edition (IC-223.7571.182)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled

## Problem description
Intellij Idea doesn't see sertain items in dependencies.
It happens sometimes with `proc macros` when imported `macro` shows in white, and code completion doesn't see its methods.
Now it's even worse because it doesn't see certain functions in `axum::routing`.
And even when they are imported, they don't show up in code completion.

## Steps to reproduce
Add `axum` crate, import `get` and `post` or `put` or similar funcs. `get` import will work correctly, unlike other imports.

![Снимок экрана (602)](https://user-images.githubusercontent.com/105431697/207130121-d2cffb08-9b8b-41ac-919b-f3b77f65e972.png)

**Comment by dima74** [comment] 2022-12-13 16:06
Duplicate of #8589
See https://github.com/intellij-rust/intellij-rust/issues/8589#issuecomment-1087535689 for details

**Closed by dima74** 2022-12-13 16:06 UTC
Labels: subsystem::type inference & name resolution, bug, subsystem::proc-macros
