### ISSUE TITLE
Public constant i32::MAX is incorrectly detected as private

### ISSUE THREAD

**Issue by ThanePatrol** [intellij-rust/intellij-rust#10483] opened 2023-05-19 01:12 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.194.5382-231
* **Rust toolchain version:** 1.71.0-nightly (e9e1bbc7a 2023-05-17) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2023.1.2 Ultimate Edition (IU-231.9011.34)
* **Operating system:** Linux 6.2.6-76060206-generic
* **Macro expansion:** enabled

## Problem description
Constant of `i32::MAX` is incorrectly detected as private, error cites [E0603](https://doc.rust-lang.org/error_codes/E0603.html) 

## Steps to reproduce
Use `i32::MAX` anywhere in code base

![image](https://github.com/intellij-rust/intellij-rust/assets/23148089/1af85b89-00fc-428b-83f6-044ad28bf098)

**Comment by Stargateur** [comment] 2023-05-21 23:22
[Error i8::MAX - Constant `MAX` is private [E0603]](https://stackoverflow.com/questions/76302213/error-i8max-constant-max-is-private-e0603)

**Comment by my4ng** [comment] 2023-05-25 10:31
Similar issue with `i32::leading_zeros` (error code [0624]).
Possibly related: #10493

**Comment by luhanzhen** [comment] 2023-07-12 02:54
i also find this bug,  finally i instead i32::MAX by 2_147_483_647i32

**Comment by pront** [comment] 2023-07-12 14:29
Also a bug on `CL-231.9161.40, JRE 17.0.7+10-b829.16x64 JetBrains s.r.o., OS Mac OS X(aarch64) v13.4.1`

**Comment by Maksim20023** [comment] 2023-07-12 15:14
Hi! Thank you all for reaching us. This issue is already known to us: [#10499](https://github.com/intellij-rust/intellij-rust/issues/10499) Unfortunately, we currently don't have information about ETA for this issue.
When we have any new information about this issue, we will add a reply to GitHub 10499 ticket.

**Comment by Maksim20023** [comment] 2023-07-25 10:26
Hi! I'm closing this ticket because the issue is fixed (please see a fix [Pull 10688](https://github.com/intellij-rust/intellij-rust/pull/10688)). This fix is included in the Rust plugin 0.4.199.5414 version. Please make sure that your installed plugin is [up-to-date](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#update).  If this issue still reproduces for you, please reopen the ticket.

**Closed by Maksim20023** 2023-07-25 10:26 UTC
