### ISSUE TITLE
It seems that intellij-rust cannot show  completion list while traits are implemented by procedural derive.

### ISSUE THREAD

**Issue by mokeyish** [intellij-rust/intellij-rust#2442] opened 2018-04-07 02:30 UTC
The example [hello-world-derive](https://doc.rust-lang.org/book/first-edition/procedural-macros.html) cannot show  completion list.
Is it has build intermediate code for completion list？

**Comment by Undin** [comment] 2020-02-13 08:51
Duplicate of #1786

**Closed** 2020-02-13 08:51 UTC
Labels: duplicate, subsystem:macros
