### ISSUE TITLE
Debug: variable value incorrect

### ISSUE THREAD

**Issue by mylvghb** [intellij-rust/intellij-rust#8893] opened 2022-06-01 08:12 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.171.4656-221
* **Rust toolchain version:** 1.61.0 (fe5b13d68 2022-05-18) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.1.1 (CL-221.5591.52)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
![image](https://user-images.githubusercontent.com/35945793/171358626-f1142a18-bffc-433c-80b8-0b91300a5b4a.png)

**Comment by Undin** [comment] 2022-06-01 09:06
Duplicate of #6296

**Closed by Undin** 2022-06-01 09:06 UTC
Labels: subsystem::debugger, bug
