### ISSUE TITLE
Unable to cmd-click in to futures-preview crate

### ISSUE THREAD

**Issue by xrl** [intellij-rust/intellij-rust#2800] opened 2018-08-27 02:20 UTC
## Environment

* **Intellij-Rust plugin version:** `0.2.0.2103-182`
* **Rust toolchain version:** `rustc 1.30.0-nightly (33b923fd4 2018-08-18)`
* **IDE name and version:** IntelliJ community, 2018.2
* **Operating system:** OS X 10.13.6

## Problem description

I am using the `futures-preview` crate, listed in my crate's depdencies:

```
futures-preview = { git = "https://github.com/rust-lang-nursery/futures-rs.git" }
```

and in my code it's included as:

```
use futures::stream::{ repeat, StreamExt };
```

but I can't cmd-click to jump to any of the parts of that import, none of the modules or explicit imports. I'm pretty sure this is because of the obscure futures-preview crate using a library rename: https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-core/Cargo.toml#L17

where it renames itself like this:

```
[lib]
name = "futures_core"
```

I bet the rust plugin doesn't know how to connect the use statement to the crate with a different name.

## Steps to reproduce

```
#![feature(async_await,futures_api,await_macro)]
use futures::stream::{ repeat, StreamExt };
use futures_core::stream::StreamObj;

struct Response<'a, T> {
    stream: StreamObj<'a, T>
}

async fn do_stuff() {
    let mut s = repeat(10).map(|v| v+1).chunks(100);
    let mut response_a_tron = Response {
        stream: StreamObj::new(&mut s)
    };
    while let Some(item) = await!(response_a_tron.stream.next()) {
        assert_eq!(item.len(), 100)
    };
}

pub fn main() {
    fahrenheit::run(do_stuff());
}
```

```
cargo-features = ["edition"]

[package]
edition = "2018"
name = "freightlines"
version = "0.1.0"
authors = ["Xavier Lange <xrlange@gmail.com>"]


[dependencies]
futures-preview = { git = "https://github.com/rust-lang-nursery/futures-rs.git" }
futures-core-preview = { git = "https://github.com/rust-lang-nursery/futures-rs.git" }
fahrenheit = "4.5.1"
```

that'll be enough to recreate it.

**Comment by Undin** [comment] 2018-08-27 06:13
Yeah, it's expected because support of 2018 edition is in progress and name resolution without `extern crate` items isn't implemented yet. You can see progress in [this](https://github.com/intellij-rust/intellij-rust/issues/2622) issue

Duplicate of #2547

**Closed by Undin** 2018-08-27 06:13 UTC
Labels: feature, rust, rust 2018, type inference & resolve
