### ISSUE TITLE
Unresolved reference when using seed::button

### ISSUE THREAD

**Issue by peacememories** [intellij-rust/intellij-rust#5314] opened 2020-04-30 13:09 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.121.3059-201-stable
* **Rust toolchain version:**  1.43.0 
* **IDE name and version:** CLion 2020.1.1
* **Operating system:** macOS 10.15.4

## Problem description

When using the `button!` macro from [seed](https://crates.io/crates/seed) v0.6.0 it is marked as `Unresolved reference` even though the code builds. The `iframe!` macro on the other hand works as expected.
The macro was originally imported using `use seed::{prelude::*, *};`, but using `use seed::button;` does not change the behavior

## Steps to reproduce

```rust
use seed::button;

fn main() {
    let test = button![];
}
```

**Comment by Undin** [comment] 2020-05-01 20:46
`button` macro is generated by [another macro](https://github.com/seed-rs/seed/blob/master/src/shortcuts.rs#L143-L179). Right now it's not supported by the plugin

**Comment by dima74** [comment] 2020-12-29 17:27
Fixed with [new name resolution](https://github.com/intellij-rust/intellij-rust/issues/6217) engine [enabled](https://github.com/intellij-rust/intellij-rust/pull/6378)

Duplicate of #4811

**Closed by dima74** 2020-12-29 17:27 UTC
Labels: subsystem::macros, subsystem::type inference & name resolution
