### ISSUE TITLE
Plugin NPE

### ISSUE THREAD

**Issue by ice1000** [intellij-rust/intellij-rust#4417] opened 2019-09-21 21:54 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.106.2743-193-nightly
* **Rust toolchain version:** 1.37.0 (eae3437df 2019-08-13) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2019.3 EAP (CL-193.3519.24)
* **Operating system:** Windows 10 10.0

## Problem description

```
java.lang.NullPointerException
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:98)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at org.rust.cargo.runconfig.buildtool.CargoBuildEventsConverter.getFilePosition(CargoBuildEventsConverter.kt:268)
	at org.rust.cargo.runconfig.buildtool.CargoBuildEventsConverter.tryHandleRustcMessage(CargoBuildEventsConverter.kt:91)
	at org.rust.cargo.runconfig.buildtool.CargoBuildEventsConverter.parse(CargoBuildEventsConverter.kt:54)
	at com.intellij.build.output.BuildOutputInstantReaderImpl$createReadJob$1.invokeSuspend(BuildOutputInstantReaderImpl.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by mchernyavsky** [comment] 2019-09-23 10:34
Can you reproduce this? Looks like `file_name` from
https://github.com/intellij-rust/intellij-rust/blob/28a7ad908f813c8591250c5148efb6863ae35d69/src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildEventsConverter.kt#L268
is null, but it shouldn't happen according to the [documentation](https://doc.rust-lang.org/nightly/nightly-rustc/syntax/json/struct.DiagnosticSpan.html#structfield.file_name) (`file_name` is a `String`, not an `Option<String>`).

**Comment by ice1000** [comment] 2019-09-23 12:43
I'm not sure what is the cause. I'll repost once I've found another reproduction.

**Comment by mchernyavsky** [comment] 2020-05-12 07:40
Fixed in https://github.com/intellij-rust/intellij-rust/pull/4638.

**Closed by mchernyavsky** 2020-05-12 07:40 UTC
Labels: bug, subsystem::tools
