### ISSUE TITLE
Imports with multiple choices are indistinguishable 

### ISSUE THREAD

**Issue by mahkoh** [intellij-rust/intellij-rust#7683] opened 2021-08-15 08:59 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.152.4026-212
* **Rust toolchain version:** 1.54.0 (a178d0322 2021-07-26) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.2 (CL-212.4746.93)
* **Operating system:** Linux 5.13.8-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

![2021-08-15-105706_510x304_scrot](https://user-images.githubusercontent.com/1882250/129472982-917347d4-f2e6-49c9-9daa-a89fb08fe415.png)

## Steps to reproduce

Add `gtk4` to a project and use the following code:

```rust
fn main() {
    let mut app = gtk4::Application::builder().build();

    gtk4::Window::builder().application(&app).build();

    app.run();
}
```

**Comment by Undin** [comment] 2021-08-15 09:05
Duplicate of #7609

**Closed by Undin** 2021-08-15 09:05 UTC
Labels: bug, subsystem::code insight::auto import
