### ISSUE TITLE
spell check is wrong

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#5831] opened 2020-07-30 15:23 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.128.3254-202-nightly
* **Rust toolchain version:** rustc 1.45.0 (5c1f21c3b 2020-07-13)
* **IDE name and version:** clion 2020.2
* **Operating system:** Arch Linux

## Problem description
wrong type check, clion report `typo: in word 'static`

![image](https://user-images.githubusercontent.com/10096425/88941513-aceaae80-d2bb-11ea-8089-d32f57c54306.png)

**Comment by Undin** [comment] 2020-07-30 15:40
Duplicate of #5551

**Closed by Undin** 2020-07-30 15:40 UTC
