### ISSUE TITLE
Zooming out problem

### ISSUE THREAD

**Issue by teivah** [intellij-rust/intellij-rust#5562] opened 2020-06-12 16:56 UTC
Zooming out on a Rust code does not reduce the size of the font for the infered types. Here is an example with a code zoomed to 50%:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/934784/84527556-6b3b7f80-acde-11ea-8cb8-ba543bfc4565.png">

**Comment by Stzx** [comment] 2020-06-13 02:44
Duplicate of #5480

**Comment by Undin** [comment] 2020-06-13 07:14
@teivah inlay hints rendering is platform feature so this bug is platform bug
Looks like it's duplicate of https://youtrack.jetbrains.com/issue/IDEA-232560

**Comment by teivah** [comment] 2020-06-13 08:51
Is there a way to disable it? It's really annoying

**Comment by Undin** [comment] 2020-06-13 08:57
@teivah Are you about type hints?

**Comment by Undin** [comment] 2020-06-13 09:04
If yes, then there are `Preferences | Editor | Inlay Hints` settings. Also, you can disable particular hint type in an editor itself, just `Right click` on hint and press `Disable %name% hints type`

**Comment by teivah** [comment] 2020-06-13 09:05
Thanks.
Yet, it's sad, I have to disable a feature that I love simply because the application is bugged.

**Comment by teivah** [comment] 2020-06-15 06:42
Btw, it's not the platform. I have the ultimate edition and with Java, I don't have this bug.
Hence, can we please reopen the ticket?

**Comment by Undin** [comment] 2020-06-15 14:00
@ortem Could you take a look?

**Comment by teivah** [comment] 2020-06-15 14:04
Thank you @Undin 
Btw, here is a proof in a Java code for example:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/934784/84666817-d923b900-af21-11ea-8a10-f0b7ff743e17.png">
The `defaultValue` fits the zoom.

**Comment by Undin** [comment] 2020-06-15 14:48
Interesting fact: our parameter hints are also scaled properly, but type hints not
![image](https://user-images.githubusercontent.com/2539310/84671684-5524fd80-af30-11ea-9291-76b526dfa8b6.png)

**Comment by ortem** [comment] 2020-06-16 09:14
@teivah There are two kinds of inlay hints in our IDEs: plain hints (like parameter name hints) and interactive hints (like our type hints). Interactive hints can be collapsible and clickable (with `Ctrl` or `cmd` pressed), while plain hints consist of just plain text.

Zooming problem concerns only interactive hints (i.e. not parameter hints on your screenshot) and you can face it even in Java code with `Method chains` hints:
<img width="521" alt="Screenshot 2020-06-16 at 12 02 58" src="https://user-images.githubusercontent.com/4854600/84754686-6706af00-afc9-11ea-9170-b676b99283f8.png">

**Closed by ortem** 2020-06-16 09:14 UTC
Labels: bug, subsystem::hints
