### ISSUE TITLE
Problem with auto-completing impl of Debug

### ISSUE THREAD

**Issue by MightyPork** [intellij-rust/intellij-rust#6946] opened 2021-03-10 16:38 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.142.3705-203
* **Rust toolchain version:** 1.50.0 (cb75ad5db 2021-02-10) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Linux 5.10.21-1-lts
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description

When you manually implement `Debug`, the generated method always needs manual fixing. This is not specific to Debug.

The problem seems to be with type aliases used in the original signature

## Steps to reproduce

```rust
use std::fmt::Debug;

struct Foo;

impl Debug for Foo {   // Warn: not all trait methods implemented
}
```

-> Implement members

```rust
use std::fmt::{Debug, Formatter};

struct Foo;

impl Debug for Foo {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        unimplemented!()
    }
}
```

I've seen this not even importing Formatter, maybe it got partly fixed recently. `Result` is still wrong, though:

You need to change `Result` to `fmt::Result` and import `fmt`.

Fixed code:

```rust
use std::fmt::{Debug, Formatter};
use std::fmt;

struct Foo;

impl Debug for Foo {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        unimplemented!()
    }
}
```

**Comment by Undin** [comment] 2021-03-12 07:27
Duplicate of #6340

**Closed by Undin** 2021-03-12 07:27 UTC
Labels: bug, subsystem::code insight
