### ISSUE TITLE
Resolve trait method for type aliases

### ISSUE THREAD

**Issue by technic** [intellij-rust/intellij-rust#3322] opened 2019-02-01 18:01 UTC
## Environment

* **Intellij-Rust plugin version:** v0.2.91.2115-183
* **Rust toolchain version:** rustc 1.32.0 (9fda7c223 2019-01-16)
* **IDE name and version:** 
PyCharm 2018.3.4 (Community Edition)
Build #PC-183.5429.31, built on January 29, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

* **Operating system:** Windows 10, Build 14393

## Problem description

IDE doesn't know about trait functions implemented for the aliased type. Both go to declaration and drop-down auto-completion don't work. See example below:

![image](https://user-images.githubusercontent.com/1092613/52140391-fae50e80-2652-11e9-9f8c-b298d6a24712.png)

## Steps to reproduce

Raw code:
```rust
trait FooBar {
    fn baz(&self);
}

impl FooBar for i32 {
    fn baz(&self) {
        unimplemented!()
    }
}

type Alias = i64;

impl FooBar for Alias {
    fn baz(&self) {
        unimplemented!()
    }
}

pub fn qqq() {
    let x: i32 = 3;
    x.baz();  // <-- Method baz() resolved
    let y: i64 = 3;
    y.baz();  // <-- Method baz() unknown
    let z: Alias = 4;
    z.baz();  // <-- Method baz() unknown
}
```

**Comment by technic** [comment] 2019-02-05 22:07
Small update on this
if I replace `impl FooBar for Alias` by `impl FooBar for 64` it works well.

**Comment by Undin** [comment] 2019-09-14 07:57
Duplicate of #2778

**Closed by Undin** 2019-09-14 07:57 UTC
Labels: E-hard, type inference & resolve
