### ISSUE TITLE
Parser error when types with constant generic parameters inside another generic type

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#8077] opened 2021-11-06 00:41 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.158.4203-212
* **Rust toolchain version:** 1.57.0-nightly (d7c97a02d 2021-10-12) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** Linux 5.13.19-2-manjaro
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
```rust

#[repr(C)]
pub struct FixedBuffer<const SIZE: usize> {
    len: usize,
    content: [u8; SIZE],
}
struct Tcp {
    pool: shared_arena::Arena<FixedBuffer<1600>>,
    read_buffer: Option<()>,
}

```
![image](https://user-images.githubusercontent.com/33482468/140591918-670069d6-071d-4964-8985-9324f24eecb1.png)
![image](https://user-images.githubusercontent.com/33482468/140591935-54adb050-99de-465f-af37-c358ff15e3ff.png)
![image](https://user-images.githubusercontent.com/33482468/140591949-b0f96187-4c37-4e9f-9c19-cc48557e8f8a.png)

**Comment by Undin** [comment] 2021-11-06 08:42
Duplicate of #7919
Fixed in #7963

**Closed by Undin** 2021-11-06 08:42 UTC
Labels: bug
