### ISSUE TITLE
Build toolbar button not working

### ISSUE THREAD

**Issue by MightyPork** [intellij-rust/intellij-rust#5295] opened 2020-04-28 07:19 UTC
## Environment

plugin version 0.2.121.3059-201-stable

IDE
```
CLion 2020.1
Build #CL-201.6668.126, built on April 9, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.6.7-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 4
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, cidr.max.intellisense.file.length=2000000
Non-Bundled Plugins: mobi.hsz.idea.gitignore, awesome.console, color.scheme.Dark Blue Theme, color.scheme.Tempo-theme, color.scheme.Wombat, com.etienne.toggleinclude, com.github.tom-power.close-tab-left-right, com.jetbrains.plugins.ini4idea, com.markskelton.one-dark-theme, com.widerwille.afterglow, krasa.IdeaIconPack, name.kropp.intellij.makefile, org.toml.lang, org.rust.lang, rs.pest
Current Desktop: KDE
```

## Problem description
I can't discount the possibility that it is some configuration error on my side or a CLion bug, but since a week or so, the Build toolbar button stopped working with Rust. I can click it but absolutely nothing happens.

I have to create a separate Run configuration with `cargo build` and use its "run" toolbar button instead, if I want to build only.

Note: Sometimes the build button starts working after first using the Run button in the session.

![Screenshot_20200428_091509](https://user-images.githubusercontent.com/2041118/80458403-034cf780-8931-11ea-8778-dbf40e5c56dc.png)

here is the configuration:
![Screenshot_20200428_091523](https://user-images.githubusercontent.com/2041118/80458415-0942d880-8931-11ea-8f21-f5c084d0954c.png)

**Comment by Undin** [comment] 2020-04-28 07:30
@MightyPork Could you provide logs please (see [instruction](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)) ?

I suppose that it's the same as #5287 but without logs I can not say for sure

**Comment by MightyPork** [comment] 2020-04-28 07:32
see if this helps [clion-logs-20200428-093117.zip](https://github.com/intellij-rust/intellij-rust/files/4544034/clion-logs-20200428-093117.zip)

**Comment by Undin** [comment] 2020-04-28 07:39
Yep, it's the same issue. So it's already fixed and the fix will be landed with next stable release.
I see two options to avoid it right now:
* use the latest nightly build. See https://intellij-rust.github.io/install#nightly-builds
* enable build tool window. Enable `org.rust.cargo.build.tool.window` in `Experimental Features` settings. You can find experimental features panel via `Help | Find Action` action

**Comment by Undin** [comment] 2020-04-28 07:40
Duplicate of #5287

**Closed by Undin** 2020-04-28 07:40 UTC
Labels: bug, subsystem::IDE

**Comment by MightyPork** [comment] 2020-04-28 07:56
OK, thanks. The build window feature is interesting, first time I tried it

**Comment by Undin** [comment] 2020-04-28 08:02
@MightyPork We are going to make it default option eventually because it produces more structured output. Right now we have some issues on Windows that's why we haven't made it default yet. Don't hesitate to share your feedback, it will help us to polish this feature
