### ISSUE TITLE
Clion/Rust Plugin do not recognize generic parameter names when auto completing in impl block

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#7756] opened 2021-08-30 09:50 UTC
## Environment

* **IntelliJ Rust plugin version:**
* **Rust toolchain version:**
* **IDE name and version:** CLion 2021.1.3
* **Operating system:** Windows 10

## Problem description

When implementing for a struct that takes generic type parameters, the IDE does not recognize the name of the generic type as a viable auto-complete option in an impl block.

A simple example using a binary search tree:

Struct with Generics:

```
pub struct BinarySearchTree<Key, Value>{

pub root: Node<Key, Value>,

}
```
In the impl block, the IDE attempts to auto-import a different value than the generic parameter name. This is really annoying because it requires either hitting the escape key, which also brings you to normal mode if you are using the ideaVim extension, or requires going back and cleaning up the auto complete statement.

![image](https://user-images.githubusercontent.com/37836437/131321194-946df573-8bf9-43da-8ea7-e4998150d63f.png)

Submitted to CLion tracker as https://youtrack.jetbrains.com/issue/CPP-26364

**Comment by Undin** [comment] 2021-08-30 09:51
Duplicate of #7750

**Closed by Undin** 2021-08-30 09:51 UTC

**Comment by maxim-banaev** [comment] 2021-08-30 09:53
@Undin sorry for that!

**Comment by Undin** [comment] 2021-08-30 09:56
@maxim-banaev no problem!
