### ISSUE TITLE
i32 primitive type missing methods completion in IDEA

### ISSUE THREAD

**Issue by nicolasm** [intellij-rust/intellij-rust#10493] opened 2023-05-22 06:35 UTC
## Environment

* Rust plugin version: 0.4.194.5382-231
* stable-x86_64-unknown-linux-gnu , rustc 1.69.0 (84c898d65 2023-04-16)
* IntelliJ 2023.1.2
* Arch Linux

## Problem description
Hi,
I have noticed some methods are missing in IDEA completion list.
For example is_positive() does not show up for the i32 primitive type.

It seems that only methods implemented from Traits are appearing in the list.

Thanks for your help.

## Steps to reproduce

```rust
let my_int: i32 = 10;
// You have to type is_positive() manually, it does not appear in the completion list.
println!("{}", my_int.is_positive());
```

![image](https://github.com/intellij-rust/intellij-rust/assets/331702/e1f3f600-7c9d-42d7-a39f-575c21e07e52)

**Comment by Maksim20023** [comment] 2023-07-28 16:00
Hi! I'm closing this ticket because the issue is fixed (please see a fix [Pull 10688](https://github.com/intellij-rust/intellij-rust/pull/10688)). This fix is available from the Rust plugin 0.4.199.5414 version and higher. Please make sure that your installed plugin is [up-to-date](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#update). If this issue still reproduces for you, please reopen the ticket.

**Closed by Maksim20023** 2023-07-28 16:00 UTC
