### ISSUE TITLE
feature(custom_test_frameworks) not supported

### ISSUE THREAD

**Issue by Luis-Hebendanz** [intellij-rust/intellij-rust#6758] opened 2021-01-30 00:31 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.139.3615-202
* **Rust toolchain version:** 1.51.0-nightly (a2f8f6281 2021-01-27) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2020.2.1 Community Edition (IC-202.6948.69)
* **Operating system:** Linux 5.4.93
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

A function named `test_main` that is generated automatically by the rust compiler is annotated as an error and hinders running the project. 

## Steps to reproduce

Checkout https://github.com/Luis-Hebendanz/svm_kernel and open it in idea. Go to `src/main` at line number 47.
There you can see the `unresolved reference` error of the `test_main` function that gets generated at compile time.

To have a better explanation how this works: https://github.com/rust-lang/rfcs/blob/master/text/2318-custom-test-frameworks.md

**Comment by Undin** [comment] 2021-01-30 11:11
Duplicate of #5351

**Closed by Undin** 2021-01-30 11:11 UTC
Labels: bug, subsystem::code insight
