### ISSUE TITLE
xml-rs macros not expanded properly

### ISSUE THREAD

**Issue by AndreKR** [intellij-rust/intellij-rust#6136] opened 2020-09-19 09:12 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.132.3360-202-nightly
* **Rust toolchain version:** nightly-x86_64-pc-windows-gnu
* **IDE name and version:** CLion 2020.2.1
* **Operating system:** Windows 7 Pro

## Problem description
The macro-generated methods of `xml-rs`'s `EmitterConfig` are not autocompleted/recognized.

## Steps to reproduce
```yaml
[dependencies]
xml-rs = "*"
```

```rust
use xml::EmitterConfig;

fn main() {
	let mut v = Vec::new();
	let mut xmlwriter = EmitterConfig::new().perform_indent(true).create_writer(&mut v);
}
```

You see that there is a method `perform_indent()`. This method is created by a [macro](https://github.com/netvl/xml-rs/blob/master/src/macros.rs) called [here](https://github.com/netvl/xml-rs/blob/master/src/writer/config.rs#L147-L157).

## Expected result

`perform_indent()` should be autocompleted.

## Actual result:

Only the field is autocompleted:

![image](https://user-images.githubusercontent.com/1188538/93663448-6c601380-fa68-11ea-991d-62906b66eb32.png)

Also:

![image](https://user-images.githubusercontent.com/1188538/93663521-ebede280-fa68-11ea-852f-a13301707161.png)

(But maybe that's expected because the methods don't really exist.)

**Comment by vlad20012** [comment] 2020-09-19 11:00
It's probably because of [`#![macro_use]`](https://github.com/netvl/xml-rs/blob/master/src/macros.rs#L1) inside the module file instead of typical `#[macro_use]` on the module declaration. 

I guess this case will be supported with `name resolution 2.0`

**Comment by dima74** [comment] 2020-12-30 12:10
Duplicate of #6486

**Closed** 2020-12-30 12:10 UTC
Labels: bug, name resolution 2.0, subsystem::macros
