### ISSUE TITLE
anyhow::Result is marked as unresolved while compiling successfully

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#5630] opened 2020-06-22 14:51 UTC
![image](https://user-images.githubusercontent.com/873919/85301582-aabd5500-b4b0-11ea-900e-2dbf83c0fa8a.png)

Plugin version 0.2.124.3162-202

CLion 2020.2 EAP
Build #CL-202.5792.50, built on June 19, 2020
CLion EAP User
Expiration date: July 19, 2020
Runtime version: 11.0.7+10-b944.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 8
Registry: run.processes.with.pty=TRUE, debugger.valueTooltipAutoShowOnSelection=true, ide.tooltip.initialDelay=580
Non-Bundled Plugins: org.toml.lang, org.rust.lang

**Comment by Undin** [comment] 2020-06-22 14:55
I believe that it's duplicate of #4544
It's already fixed in #5603
You can try the latest [nightly](https://intellij-rust.github.io/install#nightly-builds) build or wait for next release

**Closed by Undin** 2020-06-22 14:55 UTC
Labels: bug, subsystem::type inference & name resolution

**Comment by vasily-kirichenko** [comment] 2020-06-22 15:01
Thank you, it is fixed in the latest nightly build.
