### ISSUE TITLE
Code completion improvement

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [intellij-rust/intellij-rust#6475] opened 2020-12-03 10:35 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.136.3514-203
* **Rust toolchain version:** 1.47.0 (18bf6b4f0 2020-10-07) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2020.3 Ultimate Edition (IU-203.5981.155)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
This is the current IntelliJ Rust plugin code completion behavior: 
![completion](https://user-images.githubusercontent.com/39968/100997582-62dd4680-3595-11eb-9679-8583dd319a39.gif)

Is it possible to give users a setting to add `use` statement to the parent module instead of the specific method? For this example, the expected code after completion would be:

```rust
use std::env;

fn main() {
    env::args()
}
```

This is also the suggested best practice by the Rust book. Below is an excerpt from the Rust book chapter 12.1.

> Notice that the std::env::args function is nested in two levels of modules. As we discussed in Chapter 7, in cases where the desired function is nested in more than one module, it’s conventional to bring the parent module into scope rather than the function. By doing so, we can easily use other functions from std::env. It’s also less ambiguous than adding use std::env::args and then calling the function with just args, because args might easily be mistaken for a function that’s defined in the current module.

**Comment by Undin** [comment] 2020-12-03 20:08
Duplicate of #4781

**Closed by Undin** 2020-12-03 20:08 UTC
Labels: improvement, subsystem::сompletion
