### ISSUE TITLE
"add remaining patterns" does not take into account "use as"

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#5000] opened 2020-02-20 21:16 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.116.2155-201
* **Rust toolchain version:** stable-x86_64-apple-darwin rustc 1.41.0 (5e1a79984 2020-01-27)
* **IDE name and version:** CL-201.4865.10
* **Operating system:** Mac OS 10.15.2

## Problem description

I'm using a "use as" to import a type using a different name.
E.g. `use tungstenite::protocol::Message as WsMessage;`

Whenever I have a `match` statement and I use clion to _"add remaining patterns"_, the patterns populated use the original name (in this case Message) and not my _"as"_ name (in my case WsMessage).

Submitted to CLion tracker https://youtrack.jetbrains.com/issue/CPP-19153

**Comment by Undin** [comment] 2020-03-02 12:26
Duplicate of #4105

**Closed by Undin** 2020-03-02 12:26 UTC
Labels: bug, subsystem:code insight
