### ISSUE TITLE
Resolving of #[cfg]-ed items from other crates on Windows is incorrect

### ISSUE THREAD

**Issue by ohadravid** [intellij-rust/intellij-rust#3751] opened 2019-04-23 15:55 UTC
## Environment

* **Intellij-Rust plugin version:** 0.2.96.2122-191
* **Rust toolchain version:** 1.35 (nightly)
* **IDE name and version:** CLion 2019.1.2 Build #CL-191.6707.69
* **Operating system:** Windows 10

## Problem description
When using an external crate which has both `#[cfg(windows)]` and `#[cfg(posix)]`,
the code analysis will use the posix impl, even when working in windows.

In the example below, the `widestring` crate defines something like:
```
#[cfg(not(windows))]
pub type WideString = UCString<u32>;

#[cfg(windows)]
pub type WideString = UCString<u16>;
```

But the IDE will think (wrongly) that we are going to get the `<u32>` version of the type.

## Steps to reproduce
Create a small project with the following files:

`Cargo.toml`:
```
[package]
name = "playground"
version = "0.1.3"
edition = "2018"

[dependencies]
widestring = "0.4"
```

`main.rs`:
```
use widestring::WideCString;

fn main() {
    // Both have wrong type inference.
    let a = WideCString::from_str("").unwrap();
    let slice = a.as_slice();

    // Shown as error.
    let slice: &[u16] = a.as_slice();
}
```

The code will build with no error under windows, but the IDE strongly disagree:
![image](https://user-images.githubusercontent.com/2358365/56595837-a6b54f00-65ef-11e9-9579-3eb06bd52f0a.png)

`cargo build` output:
```
   Compiling playground v0.1.3 (C:\workspace\playground)
warning: unused variable: `slice`
..

warning: unused variable: `slice`
...

    Finished dev [unoptimized + debuginfo] target(s) in 1.04s
```

(Jump to definition also jumps to the posix impl)

**Comment by vlad20012** [comment] 2019-04-27 12:19
Unfortunately, we totally don't support `cfg` attributes for now

**Comment by mchernyavsky** [comment] 2019-04-27 12:23
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/1191.
Will be fixed in https://github.com/intellij-rust/intellij-rust/pull/2166.

**Closed by mchernyavsky** 2019-04-27 12:23 UTC
Labels: duplicate, improvement, type inference & resolve

**Comment by Undin** [comment] 2019-10-15 07:19
@ohadravid we decided to split cfg attributes support into parts and now the plugin has initial support of cfg attributes.
The current set of supported features is quite small (full set can be found in #4488) but it includes `windows` option so it should fix your issue.
At this moment, you can enable this feature manually via `Help | Find Action | Experimental Features | org.rust.lang.cfg.attributes` option with latest plugin version. Also, it will be enabled by default in next release (approximately next week)
Don't hesitate to share your feedback - it will help us to polish this feature
