### ISSUE TITLE
mismatched types Cow<str> -> &str

### ISSUE THREAD

**Issue by alexxbb** [intellij-rust/intellij-rust#8300] opened 2021-12-17 21:24 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.161.4292-213
* **Rust toolchain version:** 1.57.0 (f1edd0429 2021-11-29) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.3 (CL-213.5744.254)
* **Operating system:** Windows 11 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

```rust
pub fn connect_to_pipe(pipe: &str) -> Result<Session> {
    ...
}

let file:Cow<str> = file.to_string_lossy();
connect_to_pipe(&file);

```

mismatched types [E0308]expected `&str`, found `&Cow<str>`

**Comment by Maksim20023** [comment] 2023-07-28 16:56
Hi! I’m closing this ticket because the issue does not reproduce in the current environment (CLion 2023.2 Build #CL-232.8660.186, Rust plugin 0.4.199.5415-232). If this issue still reproduces for you, please reopen the ticket.

**Closed by Maksim20023** 2023-07-28 16:56 UTC
Labels: subsystem::type inference & name resolution, bug
