### ISSUE TITLE
Exception and broken navigation after latest plugin update

### ISSUE THREAD

**Issue by stepancheg** [intellij-rust/intellij-rust#9541] opened 2022-10-14 20:29 UTC
```
2022-10-14 21:25:14,819 [13380491]   INFO - #c.i.o.a.i.PopupMenuPreloader - 17396 ms since showing to preload popup menu 'Build' at 'MainMenu' in 24 ms
2022-10-14 21:25:14,822 [13380494] SEVERE - #c.i.o.a.i.ActionUpdater - IntelliJ IDEA 2022.2.2  Build #IC-222.4167.29
2022-10-14 21:25:14,822 [13380494] SEVERE - #c.i.o.a.i.ActionUpdater - JDK: 17.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-10-14 21:25:14,822 [13380494] SEVERE - #c.i.o.a.i.ActionUpdater - OS: Mac OS X
2022-10-14 21:25:14,822 [13380494] SEVERE - #c.i.o.a.i.ActionUpdater - Plugin to blame: Rust version: 0.4.180.4932-222
2022-10-14 21:25:14,850 [13380522] SEVERE - #c.i.o.a.i.ActionUpdater - MoveAction#update@MainMenu (com.intellij.refactoring.actions.MoveAction), actionId=Move, text='Move...'
java.lang.IndexOutOfBoundsException: Sequence doesn't contain element at index 3.
	at kotlin.sequences.SequencesKt___SequencesKt$elementAt$1.invoke(_Sequences.kt:35)
	at kotlin.sequences.SequencesKt___SequencesKt$elementAt$1.invoke(_Sequences.kt:35)
	at kotlin.sequences.SequencesKt___SequencesKt.elementAtOrElse(_Sequences.kt:55)
	at kotlin.sequences.SequencesKt___SequencesKt.elementAt(_Sequences.kt:35)
	at org.rust.lang.core.resolve2.FacadeResolveKt.findItemWithMacroIndex(FacadeResolve.kt:319)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.findMacroCall-sVsatjs(MacroExpansionManager.kt:781)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.doGetExpandedFromForExpansionFile(MacroExpansionManager.kt:751)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.getExpandedFrom$lambda-1(MacroExpansionManager.kt:740)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.getExpandedFrom(MacroExpansionManager.kt:738)
	at org.rust.lang.core.macros.MacroExpansionManagerImpl.getExpandedFrom(MacroExpansionManager.kt:235)
	at org.rust.lang.core.macros.RsExpandedElementKt.getExpandedFrom(RsExpandedElement.kt:70)
	at org.rust.lang.core.macros.RsExpandedElementKt$findMacroCallExpandedFromNonRecursive$1.invoke(RsExpandedElement.kt:116)
	at org.rust.lang.core.macros.RsExpandedElementKt$findMacroCallExpandedFromNonRecursive$1.invoke(RsExpandedElement.kt:116)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:167)
	at org.rust.lang.core.macros.RsExpandedElementKt.findMacroCallExpandedFromNonRecursive(RsExpandedElement.kt:117)
	at org.rust.lang.core.macros.RsExpandedElementKt.calculateMacroExpansionDepth(RsExpandedElement.kt:107)
	at org.rust.lang.core.types.infer.TyLowering.lowerTy(TyLowering.kt:169)
	at org.rust.lang.core.types.infer.TyLowering.access$lowerTy(TyLowering.kt:38)
	at org.rust.lang.core.types.infer.TyLowering$Companion.lowerTypeReference(TyLowering.kt:276)
	at org.rust.lang.core.types.ExtensionsKt.getRawType(Extensions.kt:74)
	at org.rust.lang.core.resolve.RsCachedImplItem$typeAndGenerics$2.invoke(RsCachedImplItem.kt:50)
	at org.rust.lang.core.resolve.RsCachedImplItem$typeAndGenerics$2.invoke(RsCachedImplItem.kt:49)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.rust.lang.core.resolve.RsCachedImplItem.getTypeAndGenerics(RsCachedImplItem.kt:49)
	at org.rust.lang.core.resolve.ImplLookup.findExplicitImplsWithoutAliases(ImplLookup.kt:344)
	at org.rust.lang.core.resolve.ImplLookup.access$findExplicitImplsWithoutAliases(ImplLookup.kt:234)
	at org.rust.lang.core.resolve.ImplLookup$findExplicitImpls$1.invoke(ImplLookup.kt:336)
	at org.rust.lang.core.resolve.ImplLookup$findExplicitImpls$1.invoke(ImplLookup.kt:335)
	at org.rust.lang.core.resolve.ImplLookup.processTyFingerprintsWithAliases(ImplLookup.kt:370)
	at org.rust.lang.core.resolve.ImplLookup.findExplicitImpls(ImplLookup.kt:335)
	at org.rust.lang.core.resolve.ImplLookup.rawFindImplsAndTraits(ImplLookup.kt:315)
	at org.rust.lang.core.resolve.ImplLookup.findImplsAndTraits(ImplLookup.kt:273)
	at org.rust.lang.core.resolve.NameResolutionKt.processAssociatedItems(NameResolution.kt:1390)
	at org.rust.lang.core.resolve.NameResolutionKt.processMethodDeclarationsWithDeref(NameResolution.kt:1360)
	at org.rust.lang.core.resolve.NameResolutionKt.processMethodCallExprResolveVariants(NameResolution.kt:154)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImplKt$resolveMethodCallReferenceWithReceiverType$1.invoke(RsMethodCallReferenceImpl.kt:55)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImplKt$resolveMethodCallReferenceWithReceiverType$1.invoke(RsMethodCallReferenceImpl.kt:54)
	at org.rust.lang.core.resolve.ProcessorsKt.collectResolveVariantsAsScopeEntries(Processors.kt:188)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImplKt.resolveMethodCallReferenceWithReceiverType(RsMethodCallReferenceImpl.kt:54)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferMethodCallExprType(TypeInferenceWalker.kt:657)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferDotExprType(TypeInferenceWalker.kt:913)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:188)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType$default(TypeInferenceWalker.kt:170)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferDotExprType(TypeInferenceWalker.kt:909)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:188)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType$default(TypeInferenceWalker.kt:170)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferMatchExprType(TypeInferenceWalker.kt:951)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:195)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType$default(TypeInferenceWalker.kt:170)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.processStatement(TypeInferenceWalker.kt:163)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:117)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferTypeCoercableTo(TypeInferenceWalker.kt:111)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferFnBody(TypeInferenceWalker.kt:106)
	at org.rust.lang.core.types.infer.RsInferenceContext.infer(TypeInference.kt:214)
	at org.rust.lang.core.types.infer.TypeInferenceKt.inferTypesIn$lambda-0(TypeInference.kt:40)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at org.rust.openapiext.UtilsKt.recursionGuard(utils.kt:94)
	at org.rust.lang.core.types.infer.TypeInferenceKt.inferTypesIn(TypeInference.kt:40)
	at org.rust.lang.core.types.ExtensionsKt._get_inference_$lambda-0(Extensions.kt:111)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:110)
	at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:117)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImpl.multiResolve(RsMethodCallReferenceImpl.kt:26)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.multiResolve(RsReferenceBase.kt:30)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.resolve(RsReferenceBase.kt:27)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.resolve(RsReferenceBase.kt:22)
	at com.intellij.refactoring.move.MoveHandler.getActionName(MoveHandler.java:192)
	at com.intellij.refactoring.actions.MoveAction.getActionName(MoveAction.java:81)
	at com.intellij.refactoring.actions.BaseRefactoringAction.updateActionText(BaseRefactoringAction.java:250)
	at com.intellij.refactoring.actions.BaseRefactoringAction.update(BaseRefactoringAction.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:150)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:173)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:660)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:173)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:153)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:129)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:116)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:649)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:498)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:477)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1398)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:477)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:272)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$12(ActionUpdater.java:340)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$13(ActionUpdater.java:359)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$17(ActionUpdater.java:391)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:387)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$14(ActionUpdater.java:359)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$15(ActionUpdater.java:358)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Don't know how to reproduce. Navigation works, and then it suddenly stops working.

See a lot of exceptions like this in log. They start with different messages, for example:

```
2022-10-14 21:25:14,810 [13380482] SEVERE - #c.i.o.a.i.ActionUpdater - RenameElementAction#update@MainMenu (com.intellij.refactoring.actions.RenameElementAction), actionId=RenameElement, text='Rename...'
```

or

```
2022-10-14 21:25:14,802 [13380474] SEVERE - #c.i.o.a.i.ActionUpdater - ExternalJavaDocAction#update@MainMenu (com.intellij.ide.actions.ExternalJavaDocAction), actionId=ExternalJavaDoc, text='External Documentation'
```

but the stack trace is the same.

**Comment by Undin** [comment] 2022-10-14 20:30
Duplicate of #9533

**Closed by Undin** 2022-10-14 20:30 UTC

**Comment by vlad20012** [comment] 2022-10-15 09:20
Restart of the IDE helps in my case
