### ISSUE TITLE
Prevent auto-complete in variable declaration

### ISSUE THREAD

**Issue by DragoonKiller** [intellij-rust/intellij-rust#2891] opened 2018-10-03 15:50 UTC
![at4](https://user-images.githubusercontent.com/22642079/46421657-28818000-c765-11e8-9968-9dc635aba4c1.png)
![at1](https://user-images.githubusercontent.com/22642079/46421671-32a37e80-c765-11e8-9b6f-f2741df2a631.png)
![at](https://user-images.githubusercontent.com/22642079/46421681-346d4200-c765-11e8-9db8-217df45d2835.png)

Using : IntelliJ IDEA 2018.2.4 Community
rust plugin 0.2.0.2106-182

**Comment by vlad20012** [comment] 2018-10-08 12:15
Looks like it is expected because you can write something like
```rust
struct S { f: i32 };
let S { f: f } = S { f: 0 };
```
And so you can get completion for `S` after `let` keyword. 
But it's really looks weird. And I don't know how to make it better =/

**Comment by DragoonKiller** [comment] 2018-10-09 00:38
@vlad20012 It would be nice (for me at least) if there is an option to simply supress the auto completion where user is able to name a thing.
Besides, for pattern matching (destructuring) purpose, the first letter of struct name is uppercase, while variable names are lowercase. It may check the first letter user types to decide whether to supress auto completion.
However I'm not sure if it could be implemented...

**Comment by mchernyavsky** [comment] 2018-11-30 17:39
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/2619.

**Closed by mchernyavsky** 2018-11-30 17:39 UTC
Labels: duplicate, feature
