### ISSUE TITLE
std::intrinsics::{,un}likely marked as unsafe, but they are safe to call

### ISSUE THREAD

**Issue by Kloenk** [intellij-rust/intellij-rust#8783] opened 2022-04-23 11:09 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.170.4570-221-nightly
* **Rust toolchain version:** 1.62.0-nightly (4ca19e09d 2022-04-19) aarch64-apple-darwin
* **IDE name and version:** CLion 2022.1 (CL-221.5080.224)
* **Operating system:** macOS 12.3.1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
The functions [`std::intrinsics::likely`](https://doc.rust-lang.org/stable/std/intrinsics/fn.likely.html) and [`std::intrinsics::unlikely`](https://doc.rust-lang.org/stable/std/intrinsics/fn.unlikely.html) are marked by the plugin as unsafe and therefore show an error, whereas rustdoc explicitly says those two functions are save to call.

## Steps to reproduce
use rust nightly with this code:
```rust
#![feature(core_intrinsics)]

fn main() {
 if std::intrinsics::likely(true) {
    printen!("this if is marked as error");
 }
}
```

**Comment by Undin** [comment] 2022-04-23 21:37
Duplicate of #3129

**Closed by Undin** 2022-04-23 21:37 UTC
Labels: bug, subsystem::highlighting
