### ISSUE TITLE
Feature request: Exclude specific auto-imports

### ISSUE THREAD

**Issue by wcarmon** [intellij-rust/intellij-rust#9909] opened 2022-12-19 16:32 UTC
## Environment
- org.rust.lang (0.4.183.5026-222)

* **Rust toolchain version:**
- rustc 1.67.0-nightly (b833ad56f 2022-11-18)

* **IDE name and version:**
- GoLand 2022.2.4

* **Operating system:**
- `Linux 5.4.0-128-generic #144-Ubuntu x86_64 x86_64 x86_64 GNU/Linux`

## Problem description
- Can we have this feature (which already exists in intellij): 
https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#exclude-from-auto-import

## Steps to reproduce
1. Same as in official docs, but for rust (same justifications as for java)

**Comment by neonaot** [comment] 2022-12-19 17:06
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/8971 

But fix is on its way! https://github.com/intellij-rust/intellij-rust/pull/9123

**Closed by neonaot** 2022-12-19 17:06 UTC
