### ISSUE TITLE
Can't resolve imported item if its name is the same as the name of its crate

### ISSUE THREAD

**Issue by mchernyavsky** [intellij-rust/intellij-rust#5507] opened 2020-06-05 05:25 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.124.3136-201-nightly
* **Rust toolchain version:** 1.43.1 (8d69840ab 2020-05-04) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.1.2 (CL-201.7846.88)
* **Operating system:** macOS 10.15.5

## Steps to reproduce

* `Cargo.toml`
```
[package]
name = "example"
...
```

* `lib.rs`
```rust
pub struct S;

pub fn foo(_s: S) {}
```

* `main.rs`
```rust
use example::{example /*unresolved*/, S /*unresolved*/};

fn main() {
    example(S);
}
```

**Comment by mchernyavsky** [comment] 2020-06-05 06:28
Part of https://github.com/intellij-rust/intellij-rust/issues/5502.

**Comment by Undin** [comment] 2020-06-08 19:33
Duplicate of #4509

**Closed by Undin** 2020-06-08 19:33 UTC
Labels: bug, subsystem::type inference & resolve
