### ISSUE TITLE
Captured identifiers in format strings marked as unused

### ISSUE THREAD

**Issue by haakonn** [intellij-rust/intellij-rust#8485] opened 2022-01-30 12:12 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.163.4378-213
* **Rust toolchain version:** 1.58.1 (db9d1b20b 2022-01-20) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2021.3.2 Community Edition (IC-213.6777.52)
* **Operating system:** Linux 5.4.0-94-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Rust 1.58 introduced [captured identifiers in format strings[(https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings). intellij-rust still shows such identifiers as unused if they are *only* used in such format strings.

## Steps to reproduce

The issue is demonstrated with code such as this:

```rust
let foo = 42;
let _ = format!("{foo}");
println!("{foo}");
```
Here `foo` is used in two places, but is still marked as "never used".

**Comment by Undin** [comment] 2022-01-31 05:53
Duplicate of #8417

**Closed by Undin** 2022-01-31 05:53 UTC
Labels: bug, subsystem::code insight::auto import
