### ISSUE TITLE
Cannot infer type of deref implementations defined in macros

### ISSUE THREAD

**Issue by PizzaCrust** [intellij-rust/intellij-rust#6647] opened 2021-01-10 18:45 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.51.0-nightly (fde692739 2021-01-02) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.3.1 (CL-203.6682.181)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Deref implementations defined in macros don't work correctly.
```rust
use std::ops::Deref;

fn a() -> u32 {
    struct A;
    macro_rules! b {
        () => {
            impl Deref for A {
                type Target = u32;
                fn deref(&self) -> &Self::Target {
                    &1
                }
            }
        };
    }
    b!();
    let c = *A;
    c
}
```

## Steps to reproduce
Place aforementioned code in editor, and attempt to see the type of `c`

**Comment by Undin** [comment] 2021-01-10 18:47
Duplicate of #6164

**Closed by Undin** 2021-01-10 18:47 UTC
Labels: subsystem::macros, subsystem::type inference & name resolution
