### ISSUE TITLE
Loading rust plugin makes editor unusable

### ISSUE THREAD

**Issue by Sieabah** [intellij-rust/intellij-rust#7556] opened 2021-07-20 06:24 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.151.3997.211
* **Rust toolchain version:** stable-x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ Idea 2021.1.3
* **Operating system:** Windows 10

## Problem description
When loading/opening a brand new rust project the entire editor becomes unusable. When mashing the comma on the keyboard after a quote it doesn't work. It never shows up, I cannot add <> within quote either. As soon as I load any Rust project into an IntelliJ window it affects all running instances and makes the entire IDE unusable. Frequently "linting" my code to remove characters I just added and restricting my to type characters in certain contexts. I can't figure out a pattern to it since it seems to be completely arbitrary.

There isn't much a video can show of the regular problem, but opening up a different project written with JS the issue is apparent. This is me hitting the comma key constantly as it tries to clean and remove the quote. I had never configured any linter to automatically do this and as I said before it only occurs **after opening a rust project**.

https://i.gyazo.com/3801a79f8649bdcc90e2329083cfc821.mp4

This issue also persists after restarting IntelliJ with IntelliJ. I have to fully close it and open it from the toolbox to get the issue to go away. This plugin is completely unusable for me.

## Steps to reproduce

I don't believe there is anything specific, it seems to be any project I open that invokes this plugin. Here is the first project I opened where the error occured.

```
// Cargo.toml

[dependencies]
rocket = "0.5.0-rc.1"
```

```
// src/main.rs
#[macro_use] extern crate rocket;

#[get("/world")]
fn world() -> &'static str {
    "Hello, world!"
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/hello", routes![world])
}
```

Literally open rust in IntelliJ and the entire editor is completely unusable. It doesn't you type a variety of characters within quotes. It doesn't let you put commas after quotes. No idea how this occurs, even after updating Java the issue persists. 

I understand the mp4 is a video from JS but loading this plugin in any open window causes the all instances of IntelliJ to exhibit this behavior.

**Comment by mili-l** [comment] 2021-07-21 05:18
Hello @Sieabah! Thank you for your report. Do you mind if I ask you to send a diagnostic report, you can collect it in the following way: `Help -> Collect Logs and Diagnostic Data`

**Comment by Sieabah** [comment] 2021-07-27 05:11
Really wish I didn't have to go through and remove all the sensitive information... 

[idea-logs-20210727-005827.zip](https://github.com/intellij-rust/intellij-rust/files/6882833/idea-logs-20210727-005827.zip)

**Comment by Sieabah** [comment] 2021-07-28 05:40
I regret reinstalling this plugin. It literally corrupted my entire IntelliJ installation and made it so all my projects no longer allow me to even move files or do any "refactoring" such as renaming variables or renaming files.

**Comment by vlad20012** [comment] 2021-07-29 08:17
According to the logs, the problem is not in the Rust plugin, but in the Haxe plugin that is [incompatible](https://github.com/HaxeFoundation/intellij-haxe/issues/1083) with `2021.1` and `2021.2` IDEAs.
You've installed a version from the 2015 year from the market (that is wrongly marked as froward-compatible with any IDE version)

![image](https://user-images.githubusercontent.com/3221931/127456684-20b33913-bbd5-4e6a-b8db-0c13aadd5c6d.png)
(please, note version 0.9.6 and then find this version in [the plugin changelog](https://plugins.jetbrains.com/plugin/6873-haxe-toolkit-support/versions))


Just remove `Haxe` plugin and all will be fine

**Comment by Sieabah** [comment] 2021-08-03 23:38
I've had to reinstall the entire IDE because of other issues. Still running into issues with IntelliJ in general not updating folders when I'm creating them. Not sure what that issue is but it's not related to this plugin so I suppose this could be closed.

The issue is that I only ever ran into this issue when I opened a Rust project. No other project type caused this issue.

**Closed** 2021-08-10 11:20 UTC
Labels: performance
