### ISSUE TITLE
No highlighting of string-formatting `panic!` macro

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#6638] opened 2021-01-09 10:12 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3 (CL-203.5981.166)
* **Operating system:** macOS 10.16
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
`panic!` macro should be highlighted as a string-formatting, i.e. like `println`, `format`, and so on.

The implementation of such highlighting is located is `src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt`

<img width="480" alt="Screenshot 2021-01-09 at 13 08 57" src="https://user-images.githubusercontent.com/4854600/104088971-e1f02980-527b-11eb-845f-caed7be54c48.png">

## Steps to reproduce
```Rust
fn main() {
    let x = 42;
    println!("{}", x); // `{}` is highlighted
    panic!(“{}”, x);   // `{}` not is highlighted
}
```

**Comment by Undin** [comment] 2021-01-09 10:17
Duplicate of #6119
Implemented in #6120

**Closed by Undin** 2021-01-09 10:17 UTC
Labels: E-easy, improvement, subsystem::code insight
