### ISSUE TITLE
Syntax highlighting reports unresolved reference in a file that successfully compiles

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#4999] opened 2020-02-20 21:12 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.115.2157-193
* **Rust toolchain version:**
* **IDE name and version:** CL-193.6015.37,
* **Operating system:** Linux(amd64) v4.19.0-6-amd64

## Problem description

In the attached files using the crate `derive_try_from_primitive` the syntax highlighting in lib.rs reports that the "try_from" calls are unresolved references. However this file successfully compiles.

https://gist.github.com/maxim-banaev/bc489d4ecf774e3c7bc89bbd6d5b45f7

Submitted to CLion tracker https://youtrack.jetbrains.com/issue/CPP-19003

**Comment by Undin** [comment] 2020-03-02 12:23
Unfortunately, items generated by procedural macros are not supported by plugin currently

**Comment by Undin** [comment] 2020-03-02 12:23
Duplicate of #1786

**Closed by Undin** 2020-03-02 12:23 UTC
Labels: subsystem:macros, subsystem:proc-macros
