### ISSUE TITLE
Renaming aliases doesn't work

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#6485] opened 2020-12-04 20:38 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.136.3514-203
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.3 (CL-203.5981.166)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

When renaming an imported type alias, the usages are left as they were.

## Steps to reproduce

```rust
use foo::Foo as Bar;

let bar = Bar;
```

Rename Bar and notice `let bar = Bar;` is left unchanged.

**Comment by Undin** [comment] 2020-12-04 21:35
Duplicate of #3340

**Closed by Undin** 2020-12-04 21:35 UTC
Labels: feature, subsystem::refactoring
