### ISSUE TITLE
Error recognizing tokio modules

### ISSUE THREAD

**Issue by rgutierrez2004** [intellij-rust/intellij-rust#5563] opened 2020-06-13 01:37 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.123.3132-201
* **Rust toolchain version:**
* **IDE name and version:** CLion 2020.1.1
* **Operating system:** Linux

## Problem description
One of the most popular crates, tokio, has modules which cannot be parsed by the plugin.
This has been an issue before with the Rust plugin and still is not fully resolved
Example: tokio::net::UdpSocket module.

**Comment by Undin** [comment] 2020-06-13 06:55
Try new macro expansion engine. See #3628 for more details

**Comment by Undin** [comment] 2020-06-13 06:55
Duplicate of #4627

**Closed by Undin** 2020-06-13 06:55 UTC
Labels: bug, subsystem::macros, subsystem::type inference & resolve
