### ISSUE TITLE
Is anyone working on automatic use (import) QuickFix?

### ISSUE THREAD

**Issue by andreycizov** [intellij-rust/intellij-rust#1488] opened 2017-07-19 23:55 UTC
I am very much used to the python plugin's "Import this name" functionality, which allows you to add an import to the header of the file with a quick ⌘+Enter when you've mentioned a module or a class name that needs importing. 

It saves a good chunk of my time, since I don't need to browse to the top of the file and write the code for it. 

It also reduces the overhead of looking through the previous imports and takes care of cases like:
```
use foo::bar;
use foo::baz;
```
Which it collapses into:
```
use foo::{bar, baz};
```

In any case - I would like to see this as the functionality of this plugin and would be willing to take this upon myself, in any case no one is already working on it.

**Comment by farodin91** [comment] 2017-07-20 05:50
### Two possible start point:
1. Using the CargoCheckAnnotator
- E0433
- E0599: Sometimes the rust compiler, shows possible imports like use `std::io::Read; `
- unused import
2. Extend the RsUnresolvedReferenceInspection and implement a RsUnusedImportInspection

### Two steps needed to implement:
1. Optimize imports like combining lines and remove unused imports (Reduce
2. Implement Importer using ReferenceImporter
How to find possible structs or functions? I have no idea, but @matklad or @vlad20012 could help.
For example: https://github.com/JetBrains/kotlin/blob/ddcff3c96d31d25e507461d25307472145fbc930/idea/src/org/jetbrains/kotlin/idea/quickfix/KotlinReferenceImporter.kt

**Comment by alygin** [comment] 2017-07-20 09:19
Would be great to have it. I just want to mention a couple of related issues:

- this issue is a duplicate of #1366
- a short discussion of the feature with some useful information can be found in #949

**Comment by farodin91** [comment] 2017-07-23 14:48
@andreycizov If you need any suggestion or help, i could look into.

**Comment by andreycizov** [comment] 2017-07-24 13:12
@farodin91 I had started browsing the code for various approaches on how this could be done, but if you've got any suggestions on how I could start or where I should be paying attention first - that is absolutely welcome.

Is there any specific reason why no one had mentioned `RsErrorAnnotator`, as this class seems to be analysing the code specifically in order to create all of the QuickFix objects related to the PSI it's annotating?

**Comment by farodin91** [comment] 2017-07-24 15:01
Short answer for second part, no one mentioned RsErrorAnnotator, all annotation should work stable. This currently impossible the is incomplete. 

I'll answer part one later, take to long on a mobile device.

**Comment by farodin91** [comment] 2017-07-24 19:03
I look a bit deeper into topic. 
- I would start with implementing `org.rust.ide.annotator.fixes.ImportFix` with `LocalQuickFixAndIntentionActionOnPsiElement`.
- ImportFix is called as a fix for annotation holder. For example: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt#L99-L100
- Now you need to find for the reference possible receiver. I think you need to access the Indexing routin of idea by accessing `RsNamedElementIndex.getElements`. 
- The index should return `RsNamedElement`s, theses should filter by the needed type Struct, Enum, Trait, Type or others.
- Now to build an `use`, therefore you RsPsiFactory and add this to first parent mod. You can get the first parent with the type of `RsMod` using element.parentOfType<RsMode>()

Cleanup and reference Importer could be done later.

**Comment by farodin91** [comment] 2017-07-25 12:12
@alygin Do you have any other suggestions?

**Comment by andreycizov** [comment] 2017-07-25 12:27
Is there any index that would include the visibility information as well?

Example:
```rust
let a = HashMap::new();
```

If I look up `HashMap` in `RsNamedElementIndex` - it will return an object residing in `std::collections::map::HashMap`.

The actual path to HashMap is `std::collections::HashMap`, where in `std::collections` it's declared as:
```
pub use map::HashMap;
```

Basically, is there an index I could use in order to find an importable path to HashMap without resorting to any heuristics (such as assuming `pub use/pub mod` is always declared in the parent module)?

**Comment by farodin91** [comment] 2017-07-25 19:45
I have no idea, i need look into the code. 
My first guess is to iterate over all parent mods and look to reexports.

**Comment by alygin** [comment] 2017-07-26 07:13
> @alygin Do you have any other suggestions?

My main suggestion at the moment, actually, repeats what you already said. I just want to amplify a bit.

As far as I know, in mature languages, IntelliJ uses two relatively separate steps to automatically add an import item: it adds an import (`use` in Rust's case) as a separate line and then calls a subroutine that optimizes existing items (collapses them, removes unnecessary, reorders and reformats what's left).

The task of optimizing existing imports is totally separate, it can be used per se, and I think it should be implemented as a separate feature before moving to autoimport. But it has a great deal of nuances and I'm not sure there's a standard way to do that.

So, I think there's two ways to go:
1. Implement "Optimize imports" first as a separate feature, aiming the `rustfmt` defaults as the standard. After that, implement autoimport to a new line with a consequent call to the optimizer.
2. Implement autoimport that does its best to add the new item to one of the existing `use` lines before conceding and adding it as a separate line.

As for the approach to searching for import candidates, I don't have useful ideas at the moment. I've been pressured for time lately and didn't think thoroughly about it yet.

I think, all the described tasks are quite challenging and have many pitfalls.

BTW, there's another related issue: #789. The feature is really longed-for :)

**Comment by farodin91** [comment] 2017-08-24 06:09
@andreycizov Do you need any help?

**Comment by vlad20012** [comment] 2017-09-16 23:09
Moved to #1737

**Closed by vlad20012** 2017-09-16 23:09 UTC
Labels: E-hard
