### ISSUE TITLE
String interpolation does not mark variable as used

### ISSUE THREAD

**Issue by p-kraszewski** [intellij-rust/intellij-rust#9065] opened 2022-07-14 16:57 UTC
## Environment

* **IntelliJ Rust plugin version:** `0.4.174.4743-221`
* **Rust toolchain version:** `1.62.0`
* **IDE name and version:** `#CL-221.5921.27`
* **Operating system:** `Arch Linux x86_64` and `FreeBSD 13.1 x86_64`

## Problem description

When the only use of variable is in string interpolation syntax, it is marked as unused (*grayed out* in the default color scheme) with the error message of `Variable VAR_NAME is never used`.

## Steps to reproduce

```rust
fn main() {
    let bug = "bug";               // variable bug is grayed out and reported ...
    println!("This is a {bug}!");  // ... as unused despite being read here.
}
```

**Comment by andrewring** [comment] 2022-07-14 17:52
Also present in `Ubuntu x86_64` w/ the same Rust plugin version, toolchain version, and IDE version.

**Comment by neonaot** [comment] 2022-07-15 08:33
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/8417

**Closed by neonaot** 2022-07-15 08:33 UTC
