### ISSUE TITLE
Missing support for Rust Edition 2018, incorrect code-completion without extern crate

### ISSUE THREAD

**Issue by lilianmoraru** [intellij-rust/intellij-rust#2857] opened 2018-09-15 20:42 UTC
## Environment

* **Intellij-Rust plugin version:** `v0.2.0.2420-182-nightly`
* **Rust toolchain version:** `rustc 1.30.0-nightly (2ab3eba30 2018-09-14)`
* **IDE name and version:**
```
IntelliJ IDEA 2018.3 EAP (Community Edition)
Build #IC-183.2407.10, built on September 12, 2018
JRE: 1.8.0_152-release-1293-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.8
```
* **Operating system:** `Pop!_OS 18.04 LTS(Ubuntu 18.04 LTS), Linux`

## Problem description
We can now remove `extern crate` from code with Rust Edition 2018, as long as the dependency is added inside `Cargo.toml`.
Commenting out `extern crate` results in Intellij-Rust failing to offer code completion(and jump-to, of course), even though the code compiles alright.

Note that `cargo-features = ["edition"]` is not required anymore inside `Cargo.toml`, so the handling of this is probably based on the `rustc` version(newer versions automatically use the newer edition - as I understand it, did not follow the Edition topic as much as I would of liked).

**Comment by Undin** [comment] 2018-09-15 20:44
Duplicate of #2547

**Comment by Undin** [comment] 2018-09-15 20:45
You can see the current status of Rust 2018 support [here](https://github.com/intellij-rust/intellij-rust/issues/2622)

**Closed by Undin** 2018-09-15 20:44 UTC
Labels: duplicate, feature, rust 2018

**Comment by lilianmoraru** [comment] 2018-09-15 20:48
That was fast :)
