### ISSUE TITLE
The CargoProjectResolver.addContentRoots method is too simplistic

### ISSUE THREAD

**Issue by himikof** [intellij-rust/intellij-rust#190] opened 2015-12-20 02:49 UTC
First of all, is does not handle the case when a crate has targets with root file at the same directory as the manifest file: `File(t.src_path).parentFile.absolutePath` leads to a NPE. For example, crates-io subcrate in the cargo repository has a library target with `src_path = "lib.rs"`.

More importantly, there are a lot of different target types in Cargo:
 * crate library: encoded in cargo metadata as any subset of crate types (`lib`, `rlib`, `dylib`, `staticlib`)
 * binary executable artifact: encoded as `["bin"]`
 * custom build script: build system implementation detail, usually located at the crate root, encoded as `["custom-build"]`
 * example executable for a library: encoded as `["example"]`
 * integration test executable: encoded as `["test"]`
 * benchmark executable: encoded as  `["bench"]`

http://doc.crates.io/manifest.html#the-project-layout suggests a default layout for targets within a crate, but as it is completely non-mandatory, an IDE implementation should not depend on it. Cargo metadata should be enough for determining appropriate content roots for any layout.

I think that directories containing library and binary targets should be marked as sources roots, directories containing examples, integration tests and benchmarks should be marked as test sources roots (because they contain "development-only" project sources) and custom build scripts should not affect project layout at all.

**Comment by matklad** [comment] 2015-12-20 10:40
>For example, crates-io subcrate in the cargo repository has a library target with src_path = "lib.rs".

I was getting an NPE for the cargo project just last night, but failed to identify the source :)

**Comment by matklad** [comment] 2015-12-21 10:28
Somewhat relevant to the issue is that currently we allow only one crate root per module.

**Comment by alexeykudinkin** [comment] 2016-01-28 20:20
Will be fixed alongside the #218 being landed in master.

**Closed** 2016-03-02 21:21 UTC
Labels: fixed
