### ISSUE TITLE
In unit tests, IntelliJ uses "Expected"/"Actual" -- Rust uses "left", "right"

### ISSUE THREAD

**Issue by Enrico2** [intellij-rust/intellij-rust#5465] opened 2020-05-27 21:29 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.122.3105-201
* **Rust toolchain version:** 1.45.0-nightly (a74d1862d 2020-05-14) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.1.1 Ultimate Edition (IU-201.7223.91)
* **Operating system:** macOS 10.15.4

## Problem description

Rust avoids defining which side of an assertion is expected vs actual and uses left / right instead. This is an explicit choice. IntelliJ still prints `Expected: ..` and `Actual: ..`

## Steps to reproduce

```
#[test]
fn temp() {
    assert_eq!(1, 2);
}
```

Run the test from IntelliJ.

![image](https://user-images.githubusercontent.com/161314/83074122-80e64f00-a026-11ea-91b1-dfb68bd2dc75.png)

**Comment by Undin** [comment] 2020-05-28 05:49
Duplicate of #3814

**Closed by Undin** 2020-05-28 05:49 UTC
Labels: subsystem::tests
