### ISSUE TITLE
Clion rust autocomplete does not work with external crate

### ISSUE THREAD

**Issue by ta32** [intellij-rust/intellij-rust#5616] opened 2020-06-20 03:18 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.124.3162-201
* **Rust toolchain version:** 1.44.0 (49cae5576 2020-06-01) x86_64-pc-windows-gnu
* **IDE name and version:** CLion 2020.1.2 (CL-201.7846.88)
* **Operating system:** Windows 10 10.0

## Problem description
Binary application using reqwest as external crate, auto complete does not find definitions of external public functions. It does put them as suggestions. I can F12 to the type eg I cant find the definition of the Response struct and manually find the definitions of public functions but the autocomplete does not find them 

## Steps to reproduce
clone this repo - example project with the problem
https://github.com/ta32/issues/tree/master/rust_requests
build the project.
in the main function there are no suggestions for the res object. hitting F12 on the content_length method does not find it. Doing res dot, should result in methods like status being suggested.

It appears to be related to this crate

**Comment by ta32** [comment] 2020-06-20 03:20
[Cargo.lock.txt](https://github.com/intellij-rust/intellij-rust/files/4807292/Cargo.lock.txt)

I also attached my cargo lock

**Comment by Undin** [comment] 2020-06-20 07:10
A lot of modules in `reqwest` library is located [under](https://github.com/seanmonstar/reqwest/blob/master/src/lib.rs#L273-L305) `if_hyper` macro call. And currently, default macro expansion engine can't handle it because of some technical reasons. It leads to the corresponding behavior in your case. Try to enable new macro expansion engine (see #3628 for more details). It should solve your issue

**Comment by Undin** [comment] 2020-06-20 07:10
Duplicate of #4627

**Closed by Undin** 2020-06-20 07:10 UTC
Labels: bug, subsystem::macros, subsystem::type inference & name resolution
