### ISSUE TITLE
Exhaustive pattern on u8 not recognized

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#5398] opened 2020-05-18 09:36 UTC
## Environment

* **IntelliJ Rust plugin version:** TBD
* **Rust toolchain version:** TDB
* **IDE name and version:** CLion xxxx.x TDB
* **Operating system:** TBD

## Problem description
If you manually match the full range of a `u8` (namely `0x00` to `0xFF`) in a match pattern, the interface still marks the pattern as not-exhaustive ([compiler warning [E0004]](https://doc.rust-lang.org/error-index.html#E0004)). Nevertheless, if you compile the file, you don't get that error from the compiler.

![image](https://user-images.githubusercontent.com/37836437/82197741-04f05680-9904-11ea-8a08-00466268a136.png)

## Steps to reproduce

Minimal working example for reproduction [here](https://youtrack.jetbrains.com/issue/CPP-19840)

**Comment by Undin** [comment] 2020-05-22 13:03
Duplicate of #4311

**Closed by Undin** 2020-05-22 13:03 UTC
Labels: bug, subsystem::code insight
