### ISSUE TITLE
Aliased crates aren't understood

### ISSUE THREAD

**Issue by CleanCut** [intellij-rust/intellij-rust#2612] opened 2018-06-25 22:09 UTC
If I alias a crate, intellij-rust doesn't seem to know anything about it anymore.  😭 This may be related to (or a duplicate of) #1658.

```rust
use my_crate_with_a_really_long_name as shortname;
use shortname::Thing;

...
    Thing::new();  // intellij-rust is like, "Unresolved reference: `Thing`
```

Not sure if this is a feature request, a bug, or both. 😉 Loving the plugin, by the way!  I've been bouncing between Vim, Atom, and IntelliJ for my Rust coding.  intellij-rust is keeping me on IntelliJ for the moment, though I prefer lighter-weight IDEs or editors in general.

**Comment by Undin** [comment] 2018-06-30 14:56
@CleanCut looks like that it's duplicate of #2568 but not #1658

**Comment by Undin** [comment] 2018-07-21 15:32
Fixes in #2685

**Closed by Undin** 2018-07-21 15:32 UTC
Labels: bug, type inference & resolve

**Comment by CleanCut** [comment] 2018-07-21 17:54
You guys are so awesome!
