### ISSUE TITLE
"Cannot declare a new module at this location" false positive

### ISSUE THREAD

**Issue by sfackler** [intellij-rust/intellij-rust#637] opened 2016-08-27 21:29 UTC
I don't know what exactly triggers this, but the invalid module declaration error seems to pop up in contexts it shouldn't. Specifically, it'll flag this entire region: https://github.com/sfackler/rust-native-tls/blob/master/src/lib.rs#L77-L90. I'm running version 0.0.1.903 of the plugin.

<img width="772" alt="screen shot 2016-08-27 at 11 27 36 pm" src="https://cloud.githubusercontent.com/assets/1455697/18030188/e3798322-6cad-11e6-8206-2934eac8bfc6.png">

**Comment by matklad** [comment] 2016-08-27 22:06
>seems to pop up

Does it happens sometimes randomly, or does happens deterministic every time? 

Do you use Windows?

**Comment by sfackler** [comment] 2016-08-28 09:11
Sorry, should have been more specific. The error reproduces 100% of the time with that crate. However, other module declarations seem to work properly.

I am on OSX right now and see it, and I'm ~90% sure I've seen it on Linux and Windows as well.

**Comment by matklad** [comment] 2016-08-28 10:09
I am unable to reproduce this bug :( 

Looks like something is wrong with Cargo configuration (the plugin does not understand that `lib.rs` is a crate root and can have dependent modules).

Here are some things to do which may give a bit more info:

* Does invoking `go to definition` on any of `mod imp;` works? 
* Are there any errors reported when doing "refresh cargo project"? 
* What is the output of the `cargo metadata` command invoked from the command line in the root directory of the project?

**Comment by sfackler** [comment] 2016-08-28 10:14
Go to declaration works on the submodules.

No errors running "refresh cargo project".

Here's the metadata output: https://gist.github.com/sfackler/b41069145084c3214d262e5836acbbfa

**Comment by sfackler** [comment] 2016-08-28 15:08
It does seem like it isn't aware that the file's a crate root. If I add a `mod foo;` to a crate root and then use the "create module file" fix, it moves lib.rs to lib/mod.rs and creates lib/foo.rs.

IIRC the only weird system configuration I have is that this stuff's on a case-sensitive HFS+ partition. IDEA is configured to be case sensitive though.

**Comment by matklad** [comment] 2016-08-28 16:50
>case-sensitive HFS+ partition

Hey, this might be the issue! Can you try this [build] (of this [branch])? It 's not really the fix, but it should allow to verify that case sensitivity is indeed a problem. 

[biuld]: https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_Idea16_TestsRust_2/853263:id/intellij-rust-0.0.1.954.zip
[branh]: https://github.com/intellij-rust/intellij-rust/commit/8a271b6000d6762af1e2ae60190b5abadc79ec73

**Comment by sfackler** [comment] 2016-08-28 17:29
Installed it, but nothing seems to have changed.

**Comment by sfackler** [comment] 2016-08-28 17:36
Ah, though it does look like that could be the issue! A minimal test case is:

* `cargo new foo`
* Open foo as a project from existing sources
* Add `mod bar;` to `lib.rs`
* Hit "Create module file"

On my case-sensitive partition this causes the weird `lib/mod.rs` issue, but doesn't on the normal case-insensitive partition.

**Comment by matklad** [comment] 2016-08-28 17:55
One more question: what is excellently the error message for these mod decls (there may be different errors for mods with/without path attributes )?

**Comment by sfackler** [comment] 2016-08-28 17:57
The exact error message is "Cannot declare a new module at this location".

Interestingly, the mod decls with path attributes no longer show up as errors after installing that build you linked:

<img width="734" alt="screen shot 2016-08-28 at 7 57 23 pm" src="https://cloud.githubusercontent.com/assets/1455697/18035630/abd20b9a-6d59-11e6-91e0-d91a94325243.png">

**Comment by matklad** [comment] 2016-08-28 17:59
>Interestingly, the mod decls with path attributes no longer show up as errors after installing that build you linked:

Yes, they should be fixed by #621

**Comment by matklad** [comment] 2016-08-28 18:12
>Installed it, but nothing seems to have changed.

That's interesting, because `.toLowereCase()` hack should have "fixed" this... I'll try to find a Mac with HFS+ then, because case sensitivity is definitely not handled properly at the moment :) 

Or, if you are feeling adventurous, you can try to debug it yourself. The error annotation is created here:
https://github.com/intellij-rust/intellij-rust/blob/a1f9ffe4b6a4d17202fd919d39ae14510a66681d/src/main/kotlin/org/rust/ide/annotator/RustItemsAnnotator.kt#L41

And I believe that this method fails: https://github.com/intellij-rust/intellij-rust/blob/a1f9ffe4b6a4d17202fd919d39ae14510a66681d/src/main/kotlin/org/rust/cargo/project/CargoProjectDescription.kt#L98

However I also believe that `.toLowerCase()` should fix this, so something else might be broken! 

https://github.com/intellij-rust/intellij-rust/blob/a1f9ffe4b6a4d17202fd919d39ae14510a66681d/src/main/kotlin/org/rust/cargo/project/CargoProjectDescription.kt#L98

**Comment by matklad** [comment] 2016-08-29 16:03
I hope that [this build](https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_Idea16_TestsRust_2/853804:id/intellij-rust-0.0.1.958.zip) fixes the issue, can you please check (it is the current master)?

**Comment by sfackler** [comment] 2016-08-29 16:27
Progress! If I depend on the crate "directly" (e.g. `/Volumes/git/foo`) everything works.

But, if I have a symlink from a case insensitive to a case sensitive partition (e.g. `~sfackler/code -> /Volumes/git`) and depend on the crate through that (e.g. `~sfackler/code/foo`) it still runs into the error.

**Comment by matklad** [comment] 2016-08-29 22:56
>But, if I have a symlink from a case insensitive to a case sensitive partition (e.g. ~sfackler/code -> /Volumes/git) and open on the crate through that (e.g. ~sfackler/code/foo) it still runs into the error.

I think this is fundamentally the platform's issue at the moment (https://youtrack.jetbrains.com/issue/IDEA-135546), but I'll try to see if there is some workaround.

**Comment by sfackler** [comment] 2016-08-30 18:58
No worries about the symlink issue - it's a pretty weird edge case. Things work for Java-based projects through simlinks so I wasn't aware it was a deeper issue.

Thanks for looking into this! Feel free to close unless you want to keep it open for the cross-sensitivity issue.

**Comment by matklad** [comment] 2016-08-30 19:53
Yeah, let's close this one for now. I'm watching  the platform issue and I'll ping you when it's resolved so that you can verify that everything works as expected :) 

> Things work for Java-based projects through simlinks so I wasn't aware it was a deeper issue.

In Java, you don't actually care about file names and paths, because each file contains a package clause which allows to construct canonical fully qualified names looking the contents of the single file only. In contrast in Rust you really have to care about tree structure of modules, and about the mapping between files and modules, so things are more complex.

**Closed by matklad** 2016-08-30 19:53 UTC

**Comment by matklad** [comment] 2016-09-05 12:36
Looks like the symlink issue is orthogonal to case sensitivity: https://github.com/intellij-rust/intellij-rust/issues/652

Build: https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_Idea16_TestsRust_2/858611:id/intellij-rust-0.0.1.975.zip

**Comment by alexander-irbis** [comment] 2016-10-29 19:15
> issue is orthogonal to case sensitivity

I can confirm it. Gentoo Linux, both filesystems are ext4.
![intellij-rust](https://cloud.githubusercontent.com/assets/1448323/19832149/d3d8bffc-9e24-11e6-9061-5b9a42742e1c.png)
