### ISSUE TITLE
Strange reformatting of comments inside an enum

### ISSUE THREAD

**Issue by memoryallocator** [intellij-rust/intellij-rust#7021] opened 2021-03-25 18:09 UTC
## Problem description
If there is a line such as `EnumVariant  // a comment` inside an enum's "body" (between curly brackets) then it will be reformatted to
```
EnumVariant
// a comment
```
This behavior is not expected.
It does not matter if the `File | Settings | Editor | Code Style | Rust  -> Wrapping and Braces -> Keep when reformatting -> Line breaks` checkbox is checked or not.

## Steps to reproduce
```
enum MyEnum {
    First,  // first
    Second,  // second
    Last,  // last
}
```
Click `Code | Reformat Code`. The reformatted code will be the following:
```
enum MyEnum {
    First,
    // first
    Second,
    // second
    Last,  // last
}
```

## Environment

* **IntelliJ Rust plugin version:** 0.3.143.3737-203
* **Rust toolchain version:** 1.50.0 (cb75ad5db 2021-02-10) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Linux 5.8.0-48-generic
* **Macro expansion engine:** new
* **Name resolution engine:** old

**Comment by dima74** [comment] 2021-03-31 13:59
Duplicate of #3657

**Closed by dima74** 2021-03-31 13:59 UTC
