### ISSUE TITLE
Fix all problems: External Linter: remove unused use import not working

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#6229] opened 2020-10-09 13:39 UTC
I have code like this and `use external linter` on.
```rust
use std::time;
```
Alt+Enter -> External Linter: remove unused use import -> Fix all Annotator problems in file -> Not working
![image](https://user-images.githubusercontent.com/33482468/95589856-eab44200-0a77-11eb-9ab6-ce2494f4c6d2.png)

**Comment by dima74** [comment] 2020-10-09 23:15
Duplicate of #6230

**Closed by dima74** 2020-10-09 23:15 UTC
