### ISSUE TITLE
Incorrectly reports '_' as duplicate import

### ISSUE THREAD

**Issue by ctron** [intellij-rust/intellij-rust#6216] opened 2020-10-08 06:54 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.132.3395-202
* **Rust toolchain version:** 1.46.0 (04488afe3 2020-08-24) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.2.3 (CL-202.7319.72)
* **Operating system:** Linux 5.8.11-200.fc32.x86_64

## Problem description

Having multiple imports as `_`, causes the editor to complain about duplicate imports.

## Steps to reproduce

~~~rust
use panic_rtt_target as _;
use stm32f4 as _;
~~~

Results in an error like:

![image](https://user-images.githubusercontent.com/202474/95424956-cfe0b100-0943-11eb-85ab-8618afd77291.png)

**Comment by Undin** [comment] 2020-10-08 06:55
Duplicate of #5067

**Closed by Undin** 2020-10-08 06:55 UTC
Labels: bug, subsystem::code insight
