### ISSUE TITLE
Wrong code analysis when method is declared twice (with annotations e.g.)

### ISSUE THREAD

**Issue by lem0nify** [intellij-rust/intellij-rust#3077] opened 2018-11-23 08:06 UTC
I've tried to implement one of basic examples of pretty popular now GUI library for rust — Azul (the first one from [this page](https://github.com/maps4print/azul/wiki/Getting-Started)).
I was surprised that intellij rust displays an error message where shouldn't be any errors (this code builds and runs properly):
![screenshot_15](https://user-images.githubusercontent.com/17163615/48932839-ea0b7480-ef0e-11e8-943b-f56385510f0f.png)
I've navigated to `Layout` trait definition and found out such code:
```Rust
pub trait Layout {
    /// Updates the DOM, must be provided by the final application.
    ///
    /// On each frame, a completely new DOM tree is generated. The final
    /// application can cache the DOM tree, but this isn't in the scope of `azul`.
    ///
    /// The `style_dom` looks through the given DOM rules, applies the style and
    /// recalculates the layout. This is done on each frame (except there are shortcuts
    /// when the DOM doesn't have to be recalculated).
    #[cfg(not(test))]
    fn layout(&self, window_id: WindowInfo<Self>) -> Dom<Self> where Self: Sized;
    #[cfg(test)]
    fn layout(&self) -> Dom<Self> where Self: Sized;
}
```
When I've swapped these two declarations of `layout` method, the error disappeared. So, as I suppose, IntelliJ Rust pays attention to the last declaration only and it's wrong I think.
Excuse me for my English.

**Comment by mchernyavsky** [comment] 2018-11-30 16:50
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/2821.

Related PR - https://github.com/intellij-rust/intellij-rust/pull/2166.

**Closed by mchernyavsky** 2018-11-30 16:50 UTC
