### ISSUE TITLE
False positive `Call to unsafe function` E0133

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#9815] opened 2022-11-28 15:12 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.184.5040-223-beta
* **Rust toolchain version:** 1.65.0 (897e37553 2022-11-02) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.3 RC (CL-223.7571.113)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled

## Problem description
![image](https://user-images.githubusercontent.com/49211026/204312336-1b2d2a5f-8fd5-4576-bc1d-8e0d4844f708.png)

Code is generated from c++, so feel free to specify title and labels of this issue. 

## Steps to reproduce
Clone https://github.com/google/autocxx/, open `demo/main`

**Comment by Maksim20023** [comment] 2023-08-28 15:42
I'm closing this ticket because this issue does not reproduce in the current environment (CLion 2023.2.1, Rust plugin 0.4.200.5421-232). If this issue still reproduces for you, please reopen the ticket.

**Closed as not planned by Maksim20023** 2023-08-28 15:42 UTC
Labels: subsystem::code insight, bug, subsystem::highlighting
