### ISSUE TITLE
Unable to set standard library path for default project

### ISSUE THREAD

**Issue by target-san** [intellij-rust/intellij-rust#735] opened 2016-10-13 07:45 UTC
Steps to reproduce:
File->Settings->Other Settings->Default Settings->Languages & Frameworks->Rust
Field "Standard Library" shows N/A, "..." button to its right does nothing
Same when accessing default project settings from IDEA's "splash screen"
Setting this path for particular project works fine
Setting cargo location for both default and particular project works fine

IDEA v2016.1.2 #IC-145.972
Rust plugin v0.1.0.1079
OS: Linux Mint 17.3 Rosa amd64

**Comment by cengizIO** [comment] 2017-01-20 21:40
Hello @target-san 

I think this is a duplicate of #609

**Comment by target-san** [comment] 2017-01-20 21:56
@cengizIO Seems to be it. Then you can close the issue.

**Comment by matklad** [comment] 2017-01-21 18:32
No, this is not a duplicate, we really don't support configuring stdlib for the default project. 

On the other hand, I am inclined to close this as a won't fix: 

* If you use rustup, you don't need to setup stdlib at all, this is done automatically. Given that rustup is now 1.0 and is the default method for installing Rust, I think few people would actually try to configure the default project. 

* This is a useful feature, but there are more high priority ones.

* Our project model is not solid at the moment, because of all the differences between different IDEs. I would like to create a more stable basis first before adding more features.

**Closed by matklad** 2017-01-21 18:32 UTC
