### ISSUE TITLE
Mismatched type [E0308] comparing String with &str

### ISSUE THREAD

**Issue by Bastczuak** [intellij-rust/intellij-rust#4540] opened 2019-10-15 11:57 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.107.2137-192
* **Rust toolchain version:** rustc 1.38.
* **IDE name and version:** Webstorm 2019.2.3
* **Operating system:** MacOs 10.14.6

## Problem description
Webstorm tells me that I can't compare String with &str. But the program compiles and runs with no errors.

## Steps to reproduce
Copy paste this and see the error in the IDE:
```rust
fn main() {
  let s = String::from("Hello");
  if s == "Hello" {
    println!("{}", s)
  }
}
```

**Comment by Undin** [comment] 2019-10-15 13:44
Duplicate of #4224
Try to enable new experimental macro engine - it should fix your issue. See #3628 for more details

**Closed by Undin** 2019-10-15 13:44 UTC
Labels: bug, duplicate, type inference & resolve

**Comment by Bastczuak** [comment] 2019-10-16 07:32
@Undin thanks for that information!
