### ISSUE TITLE
`include!` macro calls generated by another macro call (#5336/#5306) not working

### ISSUE THREAD

**Issue by awu** [intellij-rust/intellij-rust#6579] opened 2020-12-29 19:41 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.3 Ultimate Edition (IU-203.5981.155)
* **Operating system:** macOS 10.16
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
#5336 was supposed to enable completion support for macros that use `include!` macros (notably, for tonic, as outlined in the real-world case in #5036/https://github.com/intellij-rust/intellij-rust/issues/1908#issuecomment-593026377) however it's not working on my machine.

## Steps to reproduce
1. Enabled new macro engine
2. Enabled new name resolution engine
3. `org.rust.cargo.fetch.out.dir` enabled
4. Autocompletion works on the following:
  ```
  pub mod proto {
      include!(concat!(env!("OUT_DIR"), "/proto.rs"));
  }
  ```
  But this does not:
  ```
  pub mod proto {
      tonic::include_proto!("proto");
  }
  ```

**Comment by ncioj10** [comment] 2021-01-23 19:53
Weirdly I'm sure in a former version this has worked, as I made use of it a while ago. Now it seems even with the fetch.out.dir enabled, it doesn't work anymore.

**Comment by rkarp** [comment] 2021-04-11 17:17
Another datapoint here: I cannot reproduce this on Windows 10, Plugin version 0.3.144.3766-211. This is when using the `windows-rs` library with `windows::include_bindings!();`.
It works even without the new name resolution engine, though not everything gets resolved in that case.

**Comment by elichai** [comment] 2021-11-10 12:54
Any updates here? This makes it really hard to use `tonic` (I'm currently manually copying the generated output and calling `include!("file.rs")` directly on it)

**Comment by z3000z3000z3000** [comment] 2021-11-29 04:06
> Any updates here? This makes it really hard to use `tonic` (I'm currently manually copying the generated output and calling `include!("file.rs")` directly on it)

Same problem. But 
```
include!(concat!(env!("OUT_DIR"), "/proto.rs"));
```
also don't work for me.

Could you explain your workaround?  Where do you copy generated proto.rs ?

ver 2021.2.3

**Comment by RayneHwang** [comment] 2021-12-29 13:26
Seems it still doesn't work in projects like [raft-rs](https://github.com/tikv/raft-rs), CLion version: #CL-213.6461.46, JetBrains Rust plugin version: 0.4.163.4330-213-nightly

**Comment by dima74** [comment] 2022-08-22 17:28
@awu @rkarp @elichai @z3000z3000z3000 @v0y4g3r we recently fixed one bug related to nested `include!` macros #9132. Could you please check latest version v176 with `org.rust.cargo.evaluate.build.scripts` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) enabled?

**Comment by MarcelCoding** [comment] 2022-08-24 16:30
I've configured everything as described, but it is still not working...
I've used that tutorial: https://github.com/hyperium/tonic/blob/master/examples/helloworld-tutorial.md
![image](https://user-images.githubusercontent.com/34819524/186471993-4d185ff2-07c9-4fb6-a129-c946ef78bb05.png)
![image](https://user-images.githubusercontent.com/34819524/186472032-a5c014a6-edff-44c0-9c9c-9c737878f920.png)
![image](https://user-images.githubusercontent.com/34819524/186472127-3619f0ce-763d-4d43-8d8f-429dc760916f.png)

Directly including like this doesn't work for me:
![image](https://user-images.githubusercontent.com/34819524/186472901-49eee17e-610e-4c79-9223-b33008dcebe6.png)

**Comment by MarcelCoding** [comment] 2022-08-24 16:50
For me, everything is now working. :+1:

**Comment by elichai** [comment] 2022-08-31 12:41
@dima74 This is working for me too :)

**Closed** 2022-09-03 05:38 UTC
Labels: subsystem::type inference & name resolution, subsystem::build scripts
