### ISSUE TITLE
Not work for 'pub use' type method !

### ISSUE THREAD

**Issue by zhuxiujia** [intellij-rust/intellij-rust#4963] opened 2020-02-13 17:31 UTC
just like the tokio's code
see this tokio's time mod.
``` rust
mod delay;
pub use delay::{delay_for, delay_until, Delay};
```
when need call the  pub use method     'delay_for' we write in your Clion or VSCode:
``` rust
 tokio::time::delay_ 
```
But ! the IDE do not tip me have func delay_for.
Unless you change the module to pub and call it according to path example:
So I have to check tokio documents every time when i write delay,it' s so bad.....

**Comment by Undin** [comment] 2020-02-13 22:01
@zhuxiujia thanks for the report!
It's known issue.
Fix will be available in next release. Or you can try nightly builds (see [instruction](https://intellij-rust.github.io/install#nightly-builds) how to get them)
Anyway, to get proper name resolution and completion, you need to turn on the experimental macro expansion engine. See #3628 for more details

**Comment by Undin** [comment] 2020-02-13 22:02
Duplicate of #4627

**Closed by Undin** 2020-02-13 22:02 UTC
Labels: bug, subsystem:macros, subsystem:type inference & resolve
