### ISSUE TITLE
Debugging a single test runs all tests insteads

### ISSUE THREAD

**Issue by robinst** [intellij-rust/intellij-rust#2958] opened 2018-10-18 02:21 UTC
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2107-182
* **Rust toolchain version:** 1.29.1
* **IDE name and version:** CLion 2018.2.4, Build #CL-182.4505.18, built on September 17, 2018
* **Operating system:** macOS 10.13.6

## Problem description

Running a single test case works fine in normal mode, but when debugging it, all the tests are run instead.

## Steps to reproduce

1. I don't think it's specific to the code base, but clone this repo: https://github.com/trishume/syntect/
2. Open `src/parsing/parser.rs`
3. Go to the `can_parse_simple` test and click the green arrow in the gutter -> Debug

Expected: The single test is run in debug mode.
Actual: All the tests of the project are run instead.

Looking at the run configuration, the command looks like this: `test --package syntect --lib parsing::parser::tests::can_parse_simple -- --exact`

But when running debug, this is all that's run: `/path/to/project/target/debug/syntect-205289834647ad64 --exact`

It's possible to make it work correctly by changing the command in the run configuration to this: `test --package syntect --lib parsing::parser::tests::can_parse_simple -- --exact parsing::parser::tests::can_parse_simple`. But that's just a workaround, and you'd have to do it for every test case you want to debug.

**Comment by Undin** [comment] 2018-10-18 07:02
Duplicate of #1843

**Closed by Undin** 2018-10-18 07:02 UTC
Labels: bug, debugger, tests
