### ISSUE TITLE
Debugger variable type information all say ObjHeader

### ISSUE THREAD

**Issue by BrynCooke** [intellij-rust/intellij-rust#7493] opened 2021-07-09 13:47 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.150.3968-211
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2021.1.3 Ultimate Edition (IU-211.7628.21)
* **Operating system:** Linux 5.11.0-22-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **LLDB version:** lldb version 10.0.1 (LLVM; JetBrains IDE bundle; build 173)
## Problem description
When debugging all variable has a type `ObjHeader`.
This only happens in IntelliJ Ultimate, and not in CLion. 

## Steps to reproduce
```rust
use std::collections::HashMap;

struct Test {
    age: i16,
    name: String,
}

fn main() {
    let a = "d";
    let mut b = HashMap::new();
    b.insert("Hi", 3);
    b.insert("There", 3);
    let c = Test {
        age: 2,
        name: "Bob".to_string(),
    };
    println!("Hello, world!"); //Place breakpoint here
}

```
Here is the view from IntelliJ:
![image](https://user-images.githubusercontent.com/747836/125086772-37db4800-e0cc-11eb-8ce7-5ceda3007722.png)

Vs the view in CLion (also LLDB)

![image](https://user-images.githubusercontent.com/747836/125086857-50e3f900-e0cc-11eb-9b2f-86fe1214f929.png)

**Comment by Undin** [comment] 2021-07-09 14:06
Duplicate of #6922
Fixed in 2021.2
Also, as a workaround, you can disable the `Kotlin` plugin

**Closed by Undin** 2021-07-09 14:06 UTC
Labels: bug, subsystem::debugger
