### ISSUE TITLE
Can't rename identifier

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [intellij-rust/intellij-rust#7820] opened 2021-09-09 14:47 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.154.4085-212
* **Rust toolchain version:** `rustup 1.24.3 (ce5817a94 2021-05-31)`, `rustc 1.54.0 (a178d0322 2021-07-26)`
* **IDE name and version:**
```
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 40793M
Cores: 28
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: Batch Scripts Support (1.0.12), bundled-intellij-idea-help (212.4746.92), com.intellij.nativeDebug (212.4746.92), com.jetbrains.plugins.ini4idea (212.4746.57), com.intellij.plugins.watcher (212.4746.52), com.pinkfloyded.idea-file-path-autocomplete.idea-file-path-autocomplete (0.4.1), com.sburlyaev.terminal.plugin (0.4.4), net.berla.intellij.bookmarkactions (1.1), org.antlr.intellij.plugin (1.16), mobi.hsz.idea.gitignore (4.2.0), name.kropp.intellij.makefile (212.4746.52), org.jetbrains.plugins.vagrant (212.4746.57), org.toml.lang (0.2.154.4085-212), com.intellij.kubernetes (212.4746.57), GrepConsole (11.10.211.6086.0), String Manipulation (8.15.203.000.3), com.intellij.plugin.adernov.powershell (2.0.7), Dart (212.4746.57), io.flutter (59.0.4), JSTestDriver Plugin (202.5), com.intellij.plugins.html.instantEditing (212.4746.57), com.intellij.tailwindcss (212.4746.57), com.jetbrains.plugins.jade (212.4746.57), Pythonid (212.4746.96), org.jetbrains.plugins.ruby (212.4746.92), nl.rubensten.texifyidea (0.7.10-2), org.rust.lang (0.4.154.4085-212), de.endrullis.idea.postfixtemplates (2.12.1.212), com.jetbrains.edu (2021.8-2021.2-298)
Kotlin: 212-1.5.10-release-IJ4746.92
```
* **Operating system:**
```
OS Name:                   Microsoft Windows 10 Enterprise Insider Preview
OS Version:                10.0.21313 N/A Build 21313
```

## Problem description
Can't rename identifier using <kbd>shift+f6</kbd>

## Steps to reproduce
* cargo new test6
* Add `bitflags = "1.3.2"` to Cargo.toml
* Add this code to main.rs
```rust
bitflags::bitflags! {
    pub struct CharType:u8 {
        const LOWERCASE = 0b00000001;
        const UPPERCASE = 0b00000010;
        const DIGIT     = 0b00000100;
        const SPECIAL   = 0b00001000;
        const EXTENDED  = 0b00010000;
    }
}

fn main() {
    println!("Hello, world!");
}
```
* Move the cursor on `CharType` and press <kbd>shift+f6</kbd>
* The following error message pops up
![20210909223435](https://user-images.githubusercontent.com/39968/132706160-01ea2045-3ac0-4967-99e3-5d8c24814c5a.png)

I don't know if this is expected behavior, since the struct is defined in `bitflags`. I opened this issue and just want to confirm. Thanks.

**Comment by Undin** [comment] 2021-09-10 21:03
Duplicate of #5740

**Closed by Undin** 2021-09-10 21:03 UTC
Labels: bug, subsystem::macros, subsystem::refactoring
