### ISSUE TITLE
Incorrect dependency version completion

### ISSUE THREAD

**Issue by afetisov** [intellij-rust/intellij-rust#9122] opened 2022-07-27 14:37 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.176.4773-221-nightly
* **Rust toolchain version:** 1.62.0 (a8314ef7d 2022-06-27) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.1.3 (CL-221.5921.27)
* **Operating system:** Linux 5.4.0-122-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Steps to reproduce

Create a new project. In the Cargo.toml, add a new dependency, e.g.
```toml
[dependencies]

itertools = "<caret>"
```

Invoke completion popup. The list of dependency completions is
```text
{}
0.10.3
0.10.1
0.10.0
...
```

Note the "{}" at the top of the list, which is not a valid dependency specification.

**Comment by neonaot** [comment] 2022-07-28 09:21
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/9116

**Closed by neonaot** 2022-07-28 09:21 UTC
Labels: bug, subsystem::toml
