### ISSUE TITLE
Not able to run tests from line marker

### ISSUE THREAD

**Issue by marhkb** [intellij-rust/intellij-rust#2858] opened 2018-09-16 19:39 UTC
## Environment

* **Intellij-Rust plugin version**: 0.2.0.2105-182
* **Rust toolchain version**: 1.29.0
* **IDE name and version**: IntelliJ IDEA 2018.2.3 (Community Edition)
* **Operating system**: Arch Linux

## Problem description
Running tests from line markers do not seem to work anymore. when I click on a marker to run a test only a popup is presented saying "Nothing here"

## Steps to reproduce
write a test and try to run it from the gutter icons.

**Comment by Undin** [comment] 2018-09-24 12:26
@marhkb Could you provide example of code where line marker doesn't launch test?
Because, the simplest case works:
```rust
// lib.rs
#[test]
fn test() {
    assert_eq!(1, 2);
}
```

**Comment by mchernyavsky** [comment] 2018-10-12 13:57
I think it's duplicate of https://github.com/intellij-rust/intellij-rust/issues/1252.

**Closed by mchernyavsky** 2018-10-12 13:57 UTC
Labels: tests
