### ISSUE TITLE
Reports missing return value with yew `html!{}` macro

### ISSUE THREAD

**Issue by ctron** [intellij-rust/intellij-rust#8076] opened 2021-11-05 12:44 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.158.4203-212
* **Rust toolchain version:** 1.56.0 (09c42c458 2021-10-18) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** Linux 5.14.14-300.fc35.x86_64
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Use the yew framework, it is common to return `Html` using the `html!` macro like this:

~~~rust
    fn view(&self) -> Html {
        html! {<button/>}
    }
~~~

This compiles just fine.

However, the IntelliJ Rust integration shows an error:

![image](https://user-images.githubusercontent.com/202474/140511890-4613eb5b-bbe9-449f-a270-8abeb663ca62.png)

## Steps to reproduce

* Create a new Yew based Rust project (e.g. https://blog.logrocket.com/rust-webassembly-frontend-web-app-yew/ )
* Use the `html!`macro

**Comment by mili-l** [comment] 2021-11-05 13:10
Could you please enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` experimental features and try again?
<img width="808" alt="Screenshot 2021-11-05 at 14 06 32" src="https://user-images.githubusercontent.com/1213122/140514907-5729c2e5-d470-4cf7-bd18-8b32b32c690f.png">

**Comment by Undin** [comment] 2021-11-05 19:33
Duplicate of #6732

**Closed by Undin** 2021-11-05 19:33 UTC
Labels: subsystem::type inference & name resolution, bug

**Comment by ctron** [comment] 2021-11-08 08:13
> @ctron Could you please enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` experimental features and try again? <img alt="Screenshot 2021-11-05 at 14 06 32" width="808" src="https://user-images.githubusercontent.com/1213122/140514907-5729c2e5-d470-4cf7-bd18-8b32b32c690f.png">

I enabled both. Did a restart. However, the problem still exists.
