### ISSUE TITLE
Code completion don't work properly

### ISSUE THREAD

**Issue by CGQAQ** [intellij-rust/intellij-rust#4678] opened 2019-11-23 06:44 UTC
## Environment

* **IntelliJ Rust plugin version: 0.2.110.2150-192**
* **Rust toolchain version: rustc 1.39.0 (4560ea788 2019-11-04)**
* **IDE name and version: Clion 2019.2.5**
* **Operating system: arch linux**

## Problem description
![a](https://user-images.githubusercontent.com/15936231/69474681-e8fd7380-0dfe-11ea-8167-4eb3f656cadf.png)
![b](https://user-images.githubusercontent.com/15936231/69474682-e9960a00-0dfe-11ea-8ee3-88c0641837d4.png)
![a](https://user-images.githubusercontent.com/15936231/69474796-28788f80-0e00-11ea-8fb2-06bc02ca8cf2.png)

Code completion don't work properly, in vs-code, 3rd party crates  Code completion don't work at all. idearust plugin is better than vs-code plugin, but when it come to re-export ``` pub use xxxx::xxx```, idea plugin can't handle either,
Is that an rls limitation?

**Comment by yangshuairocks** [comment] 2019-11-25 17:51
I'm on Windows and I have a similar issue. 

![rust_completion_issue](https://user-images.githubusercontent.com/39968/69565087-30e2ed00-0fef-11ea-92cc-ef1e4e3f8907.gif)

**Comment by Undin** [comment] 2019-11-25 20:21
@CGQAQ It's a known problem. The main reason that almost every module in `async_std` is declared under macros (like `cfg_std`). The plugin can handle the case when module is declared in macro call with new experimental macro expansion engine (see #3628). But if its child modules are declared in the same way, the plugin can't find them that leads to unresolved references and absence of completion. We are working on solution

**Comment by Undin** [comment] 2019-11-25 20:23
@yangshuairocks your issue is not related to the original one. Just try to enable new experimental macro expansion engine. See #3628 for more details

**Comment by Undin** [comment] 2019-11-25 20:23
Duplicate of #4627

**Closed by Undin** 2019-11-25 20:23 UTC
