### ISSUE TITLE
Wrong autocomplete suggestion for modules

### ISSUE THREAD

**Issue by adiba** [intellij-rust/intellij-rust#1085] opened 2017-03-23 18:49 UTC
Somehow, when using other modules, top level modules like `std` are suggested as nested ones:
`use other_module::`
here `std` is suggested. Also when typing `std::`, a nested module of `other_module` is suggested, but modules that already occur in the path aren't suggested (if the path is invalid).
This seems so random... help!

**Comment by alygin** [comment] 2017-03-23 19:45
Looks like a #874 relapse.

**Comment by adiba** [comment] 2017-03-23 20:29
Although there are no cycles now

**Comment by matklad** [comment] 2017-05-29 12:48
I am ... not sure if this is really fixed or not, but I can't reproduce this anymore, so closing! :)

**Comment by adiba** [comment] 2017-05-29 15:33
@matklad my plugin is up to date
![image](https://cloud.githubusercontent.com/assets/23532559/26555327/cee85bc6-4494-11e7-857b-db035ed4d5fa.png)

**Closed** 2018-10-03 18:58 UTC
