### ISSUE TITLE
Autocompletion in macros

### ISSUE THREAD

**Issue by Yuri6037** [intellij-rust/intellij-rust#9770] opened 2022-11-19 10:37 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.182.4996-222
* **Rust toolchain version:** 1.65.0 (897e37553 2022-11-02) aarch64-apple-darwin
* **IDE name and version:** CLion 2022.2.4 (CL-222.4345.21)
* **Operating system:** macOS 13.0.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.macros.proc.derive, org.rust.macros.proc.function-like, org.rust.macros.proc

## Problem description
Autocompletion is completely broken in macros (especially in tokio::select).

## Steps to reproduce
- Open a project which uses tokio and tokio::select.
- Enjoy no autocompletion (not even on the self type).

**Comment by reesmanp** [comment] 2022-11-21 00:25
This behavior is also seen with Rocket.

**Comment by vlad20012** [comment] 2022-11-21 14:28
It seems to be fixed by #9708. Please check out today's release 0.4.183

**Comment by Yuri6037** [comment] 2022-11-21 15:47
I've just tested again after updating and while indeed "self" autocompletion is now fixed, autocompletion on "tokio::select" branch results is still broken as it thinks all types are "unknown"...

**Comment by Yuri6037** [comment] 2022-11-21 16:01
In the following code, `cli_reader` is a `tokio::io::BufReader<tokio::io::Stdin>`:

```
    loop {
        tokio::select! {
            res = self.cli_reader.next_line() => {
                match res {
                    Ok(v) => match v { //<- here v is identified as "match arm binding: <unknown>"
                        Some(line) => {
                            //self.command_in.send(Command::Chat(line.trim().into())).unwrap();
                        },
                        None => break,
                    },
                    Err(e) => {
                        eprintln!("An error has occurred: {}", e);
                        break;
                    },
                }
            }
        }
    }
```

Also, `tokio::select` does most of the macro work in normal macro rules and uses a proc macro only to provide better error messages, so it should be possible for the IDE to figure out properly the type information of `select` branches.

**Comment by vlad20012** [comment] 2022-11-21 16:07
> Also, `tokio::select` does most of the macro work in normal macro rules

**Closed by vlad20012** 2022-11-21 16:07 UTC
Labels: subsystem::macros, subsystem::сompletion

**Comment by vlad20012** [comment] 2022-11-21 16:09
> Also, `tokio::select` does most of the macro work in normal macro rules

Oh, that's good. Missed that. 

 If `cli_reader` is `tokio::io::BufReader<tokio::io::Stdin>`, then what is `cli_reader.next_line()`? I can't compile this code:
 ```rust
 fn foo(cli_reader: tokio::io::BufReader<tokio::io::Stdin>) {
    cli_reader.next_line();
}
```

```
error[E0599]: no method named `next_line` found for struct `tokio::io::BufReader` in the current scope
  --> src/main.rs:24:16
   |
24 |     cli_reader.next_line();
   |                ^^^^^^^^^ method not found in `tokio::io::BufReader<tokio::io::Stdin>`

```

**Comment by Yuri6037** [comment] 2022-11-21 16:10
> > Also, `tokio::select` does most of the macro work in normal macro rules
> 
> Oh, that's good. Missed that.
> 
> If `cli_reader` is `tokio::io::BufReader<tokio::io::Stdin>`, then what is `cli_reader.next_line()`? I can't compile this code:
> 
> ```rust
> fn foo(cli_reader: tokio::io::BufReader<tokio::io::Stdin>) {
>    cli_reader.next_line();
> }
> ```
> 
>  ```
> error[E0599]: no method named `next_line` found for struct `tokio::io::BufReader` in the current scope
>   --> src/main.rs:24:16
>    |
> 24 |     cli_reader.next_line();
>    |                ^^^^^^^^^ method not found in `tokio::io::BufReader<tokio::io::Stdin>`
> ```

Oh well I forgot:

```rust
use tokio::io::{BufReader, Stdin, AsyncBufReadExt, Lines};
```

and to get `read_line` you need `.lines()` modifier on the allocation of the `BufReader<Stdin>`.

**Comment by vlad20012** [comment] 2022-11-21 16:21
I managed to reproduce it! Thanks for the explanation!
I've opened a separate issue for it: #9781
