### ISSUE TITLE
Debugging option disabled in Windows 10 with all pre-requisites installed

### ISSUE THREAD

**Issue by wisteso** [intellij-rust/intellij-rust#6082] opened 2020-09-08 02:20 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.130.3337-202
* **Rust toolchain version:** 1.46.0
* **IDE name and version:** IntelliJ Ultimate 2020.2.1 version 202.6948.69
* **Operating system:** Windows 10 version 1909 (build 18363.1016)
* **Native Support Plugin version:** 202.6948.69

## Problem description
After installing all required plugins, I am able to run the program normally but the debug option is unavailable.  I'm not able to trigger a debug session at all, so there is no error message to provide.   IntelliJ log has no mention of any relevant errors to this.

I tested with CLion as well and am able to debug the same project just fine with that IDE. Problem is limited to IntelliJ.

There are no troubleshooting steps listed anywhere (Jetbrains, StackOverflow, etc) for this scenario, so I haven't been able to troubleshoot further than this.

## Steps to reproduce
- Install IntelliJ 2020.2.1, Rust plugin, Native Debug Support
- Create new project with default hello-world program
- Observe no debugging option

**Comment by Undin** [comment] 2020-09-08 07:05
@wisteso it's expected behaviour. Debugging outside of CLion is supported only in macOS and CLion (see #5200)

**Comment by Undin** [comment] 2020-09-08 07:05
Duplicate of #5610

**Closed by Undin** 2020-09-08 07:05 UTC
Labels: subsystem::debugger
