### ISSUE TITLE
Struct with no implementation has "Has implementation" gutter icon

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#2490] opened 2018-04-23 17:12 UTC
![image](https://user-images.githubusercontent.com/873919/39142205-a434541a-4732-11e8-9626-a91c4a47fc56.png)

**Comment by mchernyavsky** [comment] 2018-11-26 17:05
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/1708.

**Closed by mchernyavsky** 2018-11-26 17:05 UTC
