### ISSUE TITLE
Clion create new rust project missing

### ISSUE THREAD

**Issue by dblock247** [intellij-rust/intellij-rust#4630] opened 2019-11-13 15:43 UTC
I have CLion 2019.2.5 in which the rust plugin is installed on Mac OSX Catalina. (This may be by default). While following the instructions to create a rust project, I stalled when trying to create a new rust project. Please correct me if I am wrong but the plugin should add the ability to create a new cargo based rust project. That option is missing for me. 

![Rust New Project](https://user-images.githubusercontent.com/5385169/68779249-555bc400-0602-11ea-801c-53bdb1bb590f.png)
![Rust Plugin](https://user-images.githubusercontent.com/5385169/68779250-555bc400-0602-11ea-8764-e32fab73fb97.png)

**Comment by ortem** [comment] 2019-11-14 11:00
@dblock247 thank you for reporting! I cannot reproduce it, so I have no idea what's the reason for it. However, for now, you can try to create a Rust project via Cargo from the terminal and then open it in CLion.

@Undin do you have any ideas?

**Comment by Undin** [comment] 2019-11-14 19:27
@dblock247 it works for me as well. And it definitely should!
I'd recommend reinstalling the plugin. Probably it's a platform bug (who knows?).
If it doesn't help, please, provide logs. They can be collected by `Help | Compress Logs and Show in Finder` action

**Comment by racingicemen** [comment] 2020-12-04 18:45
Just upgraded to 2020.3 and seeing the same problem

![image](https://user-images.githubusercontent.com/815159/101202155-ba26f980-361d-11eb-9bec-749ffb4984bc.png)

**Comment by Undin** [comment] 2020-12-06 08:03
I close this issue as not reproducible. If you have a similar issue, file a new issue please

**Closed by Undin** 2020-12-06 08:03 UTC
Labels: bug, subsystem::IDE

**Comment by eltiare** [comment] 2021-11-07 17:58
I had this problem on Windows, and since this is on the front page of Google for this problem I'll post what happened with me. I got this error message when checking the plugins page.  Installing the TOML plugin resolved the issue for me. 

![image](https://user-images.githubusercontent.com/3036/140656196-d6b060f7-12d1-4c2d-915b-0a3f7328130e.png)

**Comment by jamsoft** [comment] 2023-04-10 16:12
I've just run into this on Windows and Rider 2022.3.3 but I have the Toml plugin already installed. Just cannot get this working.

**Comment by Undin** [comment] 2023-04-10 16:59
@jamsoft Unfortunately, it's expected - Rider doesn't have `Rust` option in `New project` action.
Current workaround it to create new Rust project from terminal using `cargo new` or `cargo init` commands and open it with Rider
