### ISSUE TITLE
debugger always shows address and never value

### ISSUE THREAD

**Issue by avnerbarr** [intellij-rust/intellij-rust#7604] opened 2021-07-28 13:03 UTC
using latest rust plugin.

in general debugger works terribly

Shows useless adresses and nearly never the actual data of interest

for example:

![image](https://user-images.githubusercontent.com/2404795/127324631-805fb4c4-805e-444a-a016-c354543fb973.png)
![image](https://user-images.githubusercontent.com/2404795/127324717-24461214-69c9-48cb-ba42-ad35e57d5e18.png)

tried toggling all states

![image](https://user-images.githubusercontent.com/2404795/127324756-bb50d581-5fd0-49bf-80cd-93724ef90424.png)

**Comment by Kobzol** [comment] 2021-07-28 14:35
What is your IntelliJ version? It seems similar to [this bug](https://youtrack.jetbrains.com/issue/KTIJ-3776). Do you have the Kotlin plugin enabled?

**Comment by avnerbarr** [comment] 2021-07-28 19:34
Same

**Comment by avnerbarr** [comment] 2021-07-28 19:35
Latest version ultimate

**Comment by ortem** [comment] 2021-08-05 07:37
Duplicate of #6922.
Fixed in IntelliJ IDEA 2021.2.
With older versions, a workaround is to disable Kotlin plugin in [settings](https://www.jetbrains.com/help/idea/managing-plugins.html#open-plugin-settings).

**Closed by ortem** 2021-08-05 07:37 UTC
