### ISSUE TITLE
Test with very long output does not pass

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#8994] opened 2022-07-01 09:20 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.173.4714-222
* **Rust toolchain version:** 1.63.0-nightly (546c826f0 2022-06-12) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.2 EAP (CL-222.3048.7)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

Originally posted in https://youtrack.jetbrains.com/issue/CPP-29687/Really-long-test-output-breaks-newlines-in-output
## Problem description

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/49211026/176859764-3df5b7ef-a5e9-48d5-908d-778f7c89b90c.png">

But works ok with `cargo test`

## Steps to reproduce
```rust
#[test]
fn test_output() {
    for i in 0..100000 {
        println!("----------------------------------------------------------------------------------------------------"); //100 chars
    }
}
```

**Comment by Undin** [comment] 2022-07-01 21:51
Duplicate of #6381

**Closed by Undin** 2022-07-01 21:51 UTC
Labels: bug, subsystem::tests
