### ISSUE TITLE
Wrong `make self mutable` correction on methods

### ISSUE THREAD

**Issue by p0lunin** [intellij-rust/intellij-rust#6743] opened 2021-01-27 19:15 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.131.3366-201
* **Rust toolchain version:** 1.49.0 (e1884a8e3 2020-12-29) x86_64-pc-windows-msvc
* **IDE name and version:** PyCharm 2020.1.2 Community Edition (PC-201.7846.77)
* **Operating system:** Windows 10 10.0

## Problem description
`make self mutable` correction on `self` argument change that to `&mut self` (expected `mut self`).

## Steps to reproduce
Put that code:
```
struct Foo(u8);
impl Foo {
    fn inc(self) -> Self {
        self.0 += 1;
        self
    }
}
```
then choose `make self mutable` option.
![image](https://user-images.githubusercontent.com/48922415/106041263-40266480-60e4-11eb-9872-39d1e0ba08f6.png)
We give:
![image](https://user-images.githubusercontent.com/48922415/106041534-9693a300-60e4-11eb-9399-2fc12f521c88.png)

**Comment by Kobzol** [comment] 2021-01-27 19:36
I can't reproduce this locally, it works correctly (changes to `self mut`). Please try to update to the newest version of the plugin.

**Comment by Undin** [comment] 2021-01-27 19:39
Duplicate of #6183

**Closed by Undin** 2021-01-27 19:39 UTC
Labels: bug, subsystem::code insight
