### ISSUE TITLE
Ctrl+N shows also Java classes in the search results

### ISSUE THREAD

**Issue by rostidev** [intellij-rust/intellij-rust#2182] opened 2018-01-10 02:17 UTC
When editing a Rust code searching for other Rust traits, structs, etc. by pressing Ctrl+N shows also Java classes and interfaces in the search results. In many cases the search results are flooded by the Java classes and interfaces with similar names.

I guess this is hard to be fixed when Intellij-Rust is a plugin of a Java IDE. I think the best solution for such issues would be making a new IntelliJ based IDE dedicated to Rust developers. Just like PyCharm for Python and CLion for C/C++. Also this would make possible to fix the Rust interactive debugger unavailability in a community edition of IntelliJ.

**Comment by alygin** [comment] 2018-01-10 04:34
I guess, IDEA shows you Java classes because you configured Java SDK for your project. Could you, please, check Project Settings -> Project -> Project SDK setting? Try to set it to "No SDK" and see if Java classes disappear from search results.

**Comment by rostidev** [comment] 2018-01-11 06:44
Yes you're right. Changing this setting to "No SDK" eliminates Java classes from search result. However I didn't configure it for my particular IntelliJ project. It's just a default IntelliJ behavior of creating a new and even an empty project.

I still think that making a dedicated for Rust IDE is much better than just a plugin for IDE of other language.

**Comment by mkaput** [comment] 2018-01-11 08:25
> It's just a default IntelliJ behavior of creating a new and even an empty project.

This behaviour seems strange for me. I never get Java SDK auto assigned to non-java projects on IntelliJ (not only Rust, but also Python). Are you using our project creator/importer for Cargo, or do you just attach Cargo to existing IntelliJ projects?

**Comment by ortem** [comment] 2021-03-18 06:39
Not reproducible anymore, I think this was fixed a long time ago

**Closed by ortem** 2021-03-18 06:39 UTC
