### ISSUE TITLE
No add missing implementations intention anymore

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#960] opened 2017-01-23 20:13 UTC
Since I updated to [Version 27](https://intellij-rust.github.io/2017/01/23/changelog-27.html) this quickfix for adding missing functions to the trait implementation does not appear anymore.

**Comment by matklad** [comment] 2017-01-23 20:21
Is this a trait from the standard library, from some cargo dependency, or your own trait?

Am I correct that goto definition (`Ctrl+B`) does not work on the trait either?

**Comment by matklad** [comment] 2017-01-23 20:24
The previous update is https://plugins.jetbrains.com/plugin/download?pr=idea&updateId=31814.

There were some significant changes in how we manage libraries in this release, so it might have problems :(

**Comment by matklad** [comment] 2017-01-23 20:32
Also, can you say exactly what plugin version you are using? (`Ctrl+Shift+A` > `plugins` > `Rust`)?

Two versions were released today, `0.1.0.1537` which definitely had a major bug, and a hotfix `0.1.0.1539`.

**Comment by torkleyy** [comment] 2017-01-23 20:41
I'm using version `0.1.0.1539`. It works on traits I define myself. It doesn't work for any library traits, like `Default`, `From` or `std::io::Read`.

**Comment by torkleyy** [comment] 2017-01-23 20:46
@matklad goto works, though

**Comment by matklad** [comment] 2017-01-23 20:49
So, goto to `Default` work, but inspections does not? That is surprising. What family (IDEA, PyCharm, ...) an version of IDE are you using?

**Comment by torkleyy** [comment] 2017-01-23 21:06
I'm using Intellij IDEA Community Edition `2016.3 Build #IC-163.11103.6` and Rust `stable 1.14`

**Comment by torkleyy** [comment] 2017-01-23 21:09
I just remember having a problem after updating: i think there was a process simialar to "setup stdlib" which didn't finish after 30 minutes, so I deleted my old `.IdeaIC2016.3` folder

**Comment by torkleyy** [comment] 2017-01-23 21:12
@matklad I think that'd make sense that I interrupted some sort of indexing... but it should do the indexing again after deleting the idea user folder, shouldn't it?

**Comment by matklad** [comment] 2017-01-23 21:18
Thanks for all this info! I'll investigate this tomorrow: offhand, I don't know the reason for this might be...

>I just remember having a problem after updating: i think there was a process simialar to "setup stdlib" which didn't finish after 30 minutes, so I deleted my old .IdeaIC2016.3 folder

Hm, can you check if the following commands work from the command line?

* `cargo metadata`

* `rustup component add rust-src`

* `rustc --print sysroot`

These are all commands which we execute when the project is opened. 

>I think that'd make sense that I interrupted some sort of indexing...

IDEA should just recalculate the index if it is corrupted, but of course some errors there are possible.

**Comment by matklad** [comment] 2017-01-23 21:27
Wait, I think I've got it! Can you open inspection settings, open some Rust inspection and see that this fixes the issue?

**Comment by torkleyy** [comment] 2017-01-23 21:35
@matklad Here's the output of these commands:

### `cargo metadata`

```json
{
  "packages": [
    {
      "name": "hello_world",
      "version": "0.1.0",
      "id": "hello_world 0.1.0 (path+file:///home/thomas/Workspace/IdeaProjects/hello_world)",
      "license": null,
      "license_file": null,
      "source": null,
      "dependencies": [],
      "targets": [
        {
          "kind": [
            "bin"
          ],
          "name": "hello_world",
          "src_path": "/home/thomas/Workspace/IdeaProjects/hello_world/src/main.rs"
        }
      ],
      "features": {},
      "manifest_path": "/home/thomas/Workspace/IdeaProjects/hello_world/Cargo.toml"
    }
  ],
  "workspace_members": [
    "hello_world 0.1.0 (path+file:///home/thomas/Workspace/IdeaProjects/hello_world)"
  ],
  "resolve": {
    "root": "hello_world 0.1.0 (path+file:///home/thomas/Workspace/IdeaProjects/hello_world)",
    "nodes": [
      {
        "id": "hello_world 0.1.0 (path+file:///home/thomas/Workspace/IdeaProjects/hello_world)",
        "dependencies": []
      }
    ]
  },
  "version": 1
}
```

### `rustup component add rust-src`

```
info: component 'rust-src' is up to date
```

### `rustc --print sysroot`

```
/home/thomas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
```

> Wait, I think I've got it! Can you open inspection settings, open some Rust inspection and see that this fixes the issue?

Didn't change anything...

**Comment by matklad** [comment] 2017-01-23 21:44
Could you try this build?

https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_CurrentIdea_TestsRust/973154:id/intellij-rust-0.1.0.1543.zip

Download the archive and use **Install plugin from disk action**.

**Comment by matklad** [comment] 2017-01-23 22:10
Ah, that does not solve the issue apparently. But I can now reproduce it perfectly!

**Comment by matklad** [comment] 2017-01-23 22:45
Ok, so this is fixed in https://github.com/intellij-rust/intellij-rust/commit/9482a77c939bc17201d14aaaa22be2aff642e296: I've mixed up operator precedence =/

Thanks a lot for the report! I'll publish a alpha with a fix now, it is a rather unpleasant issue!

**Closed by matklad** 2017-01-23 22:45 UTC
