### ISSUE TITLE
Exact match should be listed first in cargo.toml dependency completion

### ISSUE THREAD

**Issue by fctorial** [intellij-rust/intellij-rust#7416] opened 2021-06-26 15:30 UTC
## Environment

* **IntelliJ Rust plugin version:**
* 0.4.148.3911-211
* **Rust toolchain version:**
* 1.51.0
* **IDE name and version:**
* latest stable clion
* **Operating system:**
* nixos

## Problem description

An exact match for crate dependency is not listed first in the cargo.toml dependency completion

## Steps to reproduce

https://user-images.githubusercontent.com/58381615/123517974-83035d00-d6c1-11eb-9db9-3b3cd8eb44a2.mp4

**Comment by avrong** [comment] 2021-06-26 18:50
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/5908

You can try [Crates Local Index](https://github.com/intellij-rust/intellij-rust/issues/6463) feature to have better expirience with dependency competion. Note, it is still experimental and you might run into issues sometimes

**Closed** 2021-06-26 18:51 UTC
Labels: duplicate
