### ISSUE TITLE
Stabilise org.rust.cargo.evaluate.build.scripts

### ISSUE THREAD

**Issue by tustvold** [intellij-rust/intellij-rust#9402] opened 2022-09-23 16:54 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.178.4873-222
* **Rust toolchain version:** 1.63
* **IDE name and version:** Clion 2022.2.3
* **Operating system:** Linux

## Problem description

First of all thank you so much for this plugin, it is awesome :+1:

My problem is more of a question, I find myself recommending people enable the experimental feature `org.rust.cargo.evaluate.build.scripts` in order for the plugin to pick up code generated to and then `include!`d from `OUT_DIR`. 

This is a fairly common pattern used by [prost](https://docs.rs/prost-build/latest/prost_build/) and [cranelift](https://docs.rs/cranelift-codegen/latest/cranelift_codegen/) to name a few.

My questions are therefore:

* What is experimental about this feature, is it dangerous, unstable, or just not fully polished yet
* Are there downsides to enabling this feature
* Is there a path to enabling this feature by default, as I think with the recent proc macro work (mega kudos btw) this is the last major pain point I see users run into frequently

## Steps to reproduce

A test example that appears to only work with this feature enabled can be found - https://github.com/apache/arrow-datafusion/pull/3580#issuecomment-1256432671

**Comment by Undin** [comment] 2022-09-26 09:19
@tustvold Glad to hear that you like the plugin!

> What is experimental about this feature, is it dangerous, unstable, or just not fully polished yet

Currently, we consider it quite stable. Although, recently it caused an unexpected problem with compilation of `anyhow`crate (#9227)

> Are there downsides to enabling this feature

Project model loading becomes longer because under the hood it calls `cargo check` to compile all host code (procedural macros and build scripts) and execute build script binaries.

> Is there a path to enabling this feature by default, as I think with the recent proc macro work (mega kudos btw) this is the last major pain point I see users run into frequently

Note, enabling build script evaluation by default won't fix issues related to procedural macros because it requires enabling `org.rust.macros.proc` feature as well. But we are going to enable build scripts evaluation by default in stable release in the near future. The feature is already [enabled](https://github.com/intellij-rust/intellij-rust/pull/9325) in nightly builds to collect more feedback/unexpected issues

**Comment by tustvold** [comment] 2022-09-26 09:23
That's fantastic news, thank you for answering my questions. I am happy for you to close this issue, if it is already tracked elsewhere

**Comment by Undin** [comment] 2022-09-26 09:24
Actually, we don't have a separate tracking issue for this feature so let's keep it open

**Comment by tfielding-sourcepoint** [comment] 2022-10-03 18:12
This setting is actually very unstable for me, IJ freezes up within a min of turning this on.  

IJ Version: Build #IU-222.4167.29
Rust toolchain version: 1.63
Rust plugin: 0.4.179.4903-221
OS: OSX

Unfortunately navigating into protos via Prost library doesn't work very well with this setting turned off.

**Comment by afetisov** [comment] 2022-10-04 16:52
If build script evaluation is stabilized (hurray!), there should be an option in the settings to turn it off. Build scripts have the potential to negatively affect the IDE in arbitrary ways. It may also be the case (even if I would consider it a misuse of build scripts) that the build script depends on some environment variables or external services, which the IDE knows nothing about, and so couldn't evaluate the script properly (at least without extra config options).

**Comment by Undin** [comment] 2022-10-07 08:54
> This setting is actually very unstable for me, IJ freezes up within a min of turning this on.

@tfielding-sourcepoint any chance to get logs (`Help | Collect Logs and Diagnostic Data` action, see https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files for details) or even project source code (if it's open source, of course)/some example to reproduce the problem?

**Comment by drcarney-sp** [comment] 2022-10-12 12:16
> > This setting is actually very unstable for me, IJ freezes up within a min of turning this on.
> 
> @tfielding-sourcepoint any chance to get logs (`Help | Collect Logs and Diagnostic Data` action, see https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files for details) or even project source code (if it's open source, of course)/some example to reproduce the problem?

Hey there @Undin, @tfielding-sourcepoint  and i have isolated the issue a little more and come up with a pretty minimal repro here:

https://github.com/drcarney-sp/ij-issue

i've left some comments in lib.rs, but basically we are seeing intellij freeze if you uncomment line 15 of lib.rs

**Comment by Undin** [comment] 2022-10-12 16:54
@drcarney-sp Thanks a lot! I'll take a look

**Comment by Undin** [comment] 2022-10-12 21:30
> If build script evaluation is stabilized (hurray!), there should be an option in the settings to turn it off. Build scripts have the potential to negatively affect the IDE in arbitrary ways. It may also be the case (even if I would consider it a misuse of build scripts) that the build script depends on some environment variables or external services, which the IDE knows nothing about, and so couldn't evaluate the script properly (at least without extra config options).

@afetisov we thought about introducing a user-visible option for this. But we don't plan to introduce it anymore because we decided we don't want to allow users to turn ot off (except some critical issues. For such cases, it will be possible just to turn off experimental feature). Absence of build scripts and proc macro support doesn't allow us to fully rely on our analysis because the plugin doesn't know all info about project. And it's not some corner case, it's a quite common situation when you use some procedural macros directly or your external library has a build script and/or usages of procedural macros. If we try to enable, for example, `Unresolved reference` inspection in all cases, users will get tons of false positives without build script and proc macro support.
Also, don't forget that proc macro support requires build script evaluation feature itself because "Build script evaluation" compiles all host code including procedural macros and we need artifacts of this compilation to expand procedural macros.
So "introducing a user-visible option to disable build script evaluation" means supporting two different worlds: when the plugin can rely on its own analysis or not. And we don't want to do it - too confusing for users and too costly from team resources point of view

> Build scripts have the potential to negatively affect the IDE in arbitrary ways

Do you know about particular problems?

> It may also be the case (even if I would consider it a misuse of build scripts) that the build script depends on some environment variables or external services, which the IDE knows nothing about, and so couldn't evaluate the script properly (at least without extra config options).

But I don't see a real issue when a build script depends on some custom environment because:
- it's not so often
- the plugin will work even if compilation of some build script fails (and now with using [--keep-going](https://github.com/intellij-rust/intellij-rust/pull/9176) flag, it doesn't break proc macro compilation in most cases)
- other build systems like Gradle do the same

Also, it's not so hard just to provide a way to pass necessary environment variables for build script evaluation process

**Comment by Undin** [comment] 2022-10-14 11:55
@drcarney-sp I've checked your case and created #9531

But it seems that it's a bug in procedural macro expansion support which is still disabled by default, and if you turn it off, everything will work fine. So this case doesn't block us to enable build scripts evaluation

Could you check that everything is fine if you disable `org.rust.macros.proc` [experimental](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) feature?

**Comment by drcarney-sp** [comment] 2022-10-14 18:30
> 

@Undin - thanks for looking into this. i'll check it out. in the meantime i've just removed the include! macros from our codebase, but they were originally from the tonic codebase, so tonic uses might experience issues

**Closed** 2022-10-14 19:23 UTC
Labels: subsystem::build scripts

**Comment by afetisov** [comment] 2022-11-07 03:06
@Undin Here is an example with build script evaluation failing. Try working on the rust compiler. The build script evaluation tries to run a check of dependent crates, and predictably chokes on the repo's copy of libcore. In the end, I get an unworkable project with no semantic analysis. 

That wasn't a case in the past, months ago I could work on that codebase without such issues.

I'm not sure how much it depends on the build.rs evaluation proper, since running `cargo check` is unlikely to be done by a build script. But it is an example where the current project model is absolutely unfit for the use case. The plugin should provide assistance even if it's unable to get full project information.

Also, build script evaluation is entirely opaque. It doesn't tell what it builds with which parameters and how it runs the artifacts, thus there is no way to debug a failure.

**Comment by vlad20012** [comment] 2022-11-07 11:57
> The plugin should provide assistance even if it's unable to get full project information.

Yes, it should and it still does!

> In the end, I get an unworkable project with no semantic analysis.

But how can we reproduce it? I opened the `rust-lang/rust` project right now end everything seems to work like before, despite the fact that buildscript evaluation is now failing. And this is intentional, expected and tested behavior - using the plugin with buildscript evaluation failure must be equivalent to using the plugin with disabled buildsript evaluation

**Comment by vlad20012** [comment] 2022-11-07 12:03
Btw we must make buildscript evaluation to work with `rust-lang/rust` project, there are [instructions for rust-analyzer](https://rustc-dev-guide.rust-lang.org/building/suggested.html#configuring-rust-analyzer-for-rustc) and it seems to be quite easy
