### ISSUE TITLE
Go To Declaration doesn't work for expressions inside a macro

### ISSUE THREAD

**Issue by photex** [intellij-rust/intellij-rust#590] opened 2016-08-10 09:16 UTC
Howdy!

I have two modules, one defines a bunch of functions, the other is referring to these and using a macro to DRY up the code a bit..
If I have a use of the function outside of the macro then the plugin correctly locates the symbol and I can jump to the declaration.
But any call to that function inside a macro will not work.

Here is the macro:
```rust
macro_rules! build_registry {
    ($(($method_name:expr, $handler:path),)*) => {{
        let fnv = BuildHasherDefault::<FnvHasher>::default();
        let mut tmp_registry = HandlerMap::with_hasher(fnv);
        $({
            info!("Registering handler for \"{}\"...", $method_name);
            let fnum = protocols::id_for_field_name::<protocols::rpc::Request>($method_name);
            tmp_registry.insert(fnum, $handler);
        })*
            tmp_registry
    }};
}
```

And here is an example of it's use:
```rust
let registry = Arc::new(build_registry![
        ("asset", handlers::get_asset),
        ("update_asset", handlers::update_asset),
        ("find_assets", handlers::find_assets),
        ("system_request", handlers::system_request),
        ("project_info", handlers::project_info),
        ("create_project", handlers::create_project),
        ("find_projects", handlers::find_projects),
        ("userdata", handlers::userdata_request),
    ]);
```

If I were to put a line above that registry binding: `let foo = handlers::get_asset` then the plugin can locate get_asset just fine. It's only inside the invocation of build_registry! that seems to be the problem.

I tested with racer in emacs and vscode and they both locate the function fine.

**Comment by matklad** [comment] 2016-08-10 15:21
Hi!

Yes, we don't do macros yet :( The problem is, we build a proper AST from the Rust code, so currently we see the inside of macro invocation simply as a token tree, not as an expression. The relevant issue is here: https://github.com/intellij-rust/intellij-rust/issues/545

Just out of curiosity, why `bulid_registry` needs to be a macro? Are those handlers of different types?

**Comment by matklad** [comment] 2016-08-10 15:22
closing as a dupe of #545

**Closed by matklad** 2016-08-10 15:22 UTC

**Comment by photex** [comment] 2016-08-10 15:27
It's a macro only to prevent copy pasta. Those strings get converted to integers using protobuf reflection to determine field numbers.
I could just make a function instead for each item but the macro also performs the hoohah of creating a new hashmap with the fnv hasher.

This was just an example. Anything inside a `try!` macro also has this problem... which is a lot of my code haha.

Sorry for the duplicate issue. :)

**Comment by matklad** [comment] 2016-08-10 15:28
>Anything inside a try! macro also has this problem... 

Are you sure about this? We currently special-case the `try!` and some other macros, so it should work

**Comment by photex** [comment] 2016-08-10 15:46
Totally sure. I just double checked that this is the case.

I have code in two modules from the same crate and I can't use this functionality in any call to try!

**Comment by matklad** [comment] 2016-08-10 16:02
Hm, the following works for me:

```Rust
fn bar() -> Result<(), ()> {
    try!(self::m::foo()); // <- go to declaration works for foo
    Ok(())
}

mod m {
    pub fn foo() -> Result<(), ()> {
        Ok(())
    }
}
```

Perhaps it's not the `try!` macro that's broken?

**Comment by photex** [comment] 2016-08-10 16:11
The code is in separate files and the function doesn't use a full path like that. In this case its a method on a trait: `self.api.foo()`

**Comment by photex** [comment] 2016-08-10 16:12
Outside of the try usage it's resolved fine.

**Comment by matklad** [comment] 2016-08-10 17:04
Looks like a bug, but I have not been able to reproduce it myself :( 

I've tried something like 

```Rust
fn main() {
    use self::m::T;
    let s = self::m::S;
    s.api.foo();
    try!(s.api.foo());
}

// really `mod m;` and the contents in the other file
mod m {
    struct S {
        api: A
    }

    struct A;

    trait T {
        fn foo(&self) -> Result<(), ()>;
    }

    impl T for A {
        fn foo(&self) -> Result<(), ()> {}
    }
}
```

**Comment by photex** [comment] 2016-08-10 20:44
I've found some places that definitely do work. I'm pretty slammed with work at the moment, but I'll try and figure out how or what it is about my code that's causing this and follow up.

**Comment by photex** [comment] 2016-08-11 07:55
Oh, I see what the issue is now. 

It's not working outside of try! in this case either. The parser just isn't able to infer the type of a result.

```rust
let api = try!(Api::open()); // doesn't know what api is
let api = Api::open().unwrap(); // still doesn't know

let api: Api = try!(Api::open()); // works
```

Where the open signature is: `Api::open() -> Result<Api, Error>`.

Annotating the type then sorts stuff out in other calls that are inside `try!`.

**Comment by matklad** [comment] 2016-08-11 08:06
Yes, we unfortunately don't handle generic parameters yet. This would be the next step in our type inference.
