### ISSUE TITLE
"Cannot find declaration to go to"

### ISSUE THREAD

**Issue by lUNuXl** [intellij-rust/intellij-rust#6138] opened 2020-09-19 23:37 UTC
## Environment

* **IntelliJ Rust plugin version:**
0.3.132.3360-202-nightly
(I also tried with the "stable" version of this plugin)
* **Rust toolchain version:**
~/git/rust-website $ rustc --version
rustc 1.46.0 (04488afe3 2020-08-24)
~/git/rust-website $ rustup --version
rustup 1.22.1 (2020-07-08)
* **IDE name and version:**
Intellij IDEA Ultimate 2020.2.2
CLion 2020.2.3
* **Operating system:**
ArchLinux
## Problem description
Clion and IDEA cannot find declaration of 
```rust
use std::os::unix::net::{UnixStream,UnixListener};
use std::thread;
```

## Steps to reproduce
```rust
use std::io::{BufRead, BufReader};
use std::os::unix::net::{UnixStream,UnixListener};
use std::thread;

fn handle_client(stream: UnixStream) {
    let stream = BufReader::new(stream);
    for line in stream.lines() {
        println!("{}", line.unwrap());
    }
}

fn main() {
    let listener = UnixListener::bind("/tmp/rust-uds.sock").unwrap();

    for stream in listener.incoming() {
        match stream {
            Ok(stream) => {
                thread::spawn(|| handle_client(stream));
            }
            Err(err) => {
                println!("Error: {}", err);
                break;
            }
        }
    }
}
```

Now hover over to 2 line and try going to declaration of UnixStream or UnixListener

Attached project files, it runs without issues with cargo run
[rust-website.zip](https://github.com/intellij-rust/intellij-rust/files/5250852/rust-website.zip)

**Comment by Undin** [comment] 2020-09-19 23:40
Duplicate of #3957

**Closed by Undin** 2020-09-19 23:40 UTC
Labels: bug, subsystem::type inference & name resolution
