### ISSUE TITLE
Captured identifiers in format strings

### ISSUE THREAD

**Issue by mylvghb** [intellij-rust/intellij-rust#8668] opened 2022-03-16 05:46 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.166.4486-213
* **Rust toolchain version:** 1.59.0 (9d1b2106e 2022-02-23) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.3.4 (CL-213.7172.20)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Warning: Variable `x` is never used

## Steps to reproduce
``` Rust
fn main() {
    let x = 1;
    println!("{x}");
}
```
![image](https://user-images.githubusercontent.com/35945793/158524586-2973640e-6335-49a9-b83d-bdc009a2b28d.png)

**Comment by Undin** [comment] 2022-03-16 06:11
Duplicate of #8417

**Closed by Undin** 2022-03-16 06:11 UTC
Labels: bug, subsystem::highlighting
