### ISSUE TITLE
Immediate hint after typing `::`

### ISSUE THREAD

**Issue by daschl** [intellij-rust/intellij-rust#537] opened 2016-07-19 09:10 UTC
Hi folks,

When I'm typing an Enum and then `::` it doesn't display the variants, but as soon as I type a character it provides me the options. Is it possible to immediately show all the variants as soon as you type `::`?

So

<img width="457" alt="screen shot 2016-07-19 at 11 09 20" src="https://cloud.githubusercontent.com/assets/29086/16944531/52d0110e-4da1-11e6-96b3-80679a633446.png">

vs.

<img width="603" alt="screen shot 2016-07-19 at 11 09 36" src="https://cloud.githubusercontent.com/assets/29086/16944533/54f0de3c-4da1-11e6-9d82-859b82b6cf76.png">

if this is already tracked in a different ticket please disregard and close - I couldn't find it.

Thanks much!

**Comment by matklad** [comment] 2016-07-19 09:19
Yep, this is a dupe of #439, and I am about to fix it!

**Closed by matklad** 2016-07-19 09:19 UTC

**Comment by daschl** [comment] 2016-07-19 09:21
👍 thanks!

**Comment by matklad** [comment] 2016-07-19 10:42
Here you are: https://github.com/intellij-rust/intellij-rust/commit/a1367c91ccc6a7ffb94aa107c13a643547022aaa
