### ISSUE TITLE
Invalid "Cannot move" diagnostic

### ISSUE THREAD

**Issue by wolverian** [intellij-rust/intellij-rust#6831] opened 2021-02-11 17:30 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.140.3644-203
* **Rust toolchain version:** 1.49.0 (e1884a8e3 2020-12-29) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.1 EAP Ultimate Edition (IU-211.5787.15)
* **Operating system:** macOS 11.2
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description

The following code:

```rust
fn foo() {
    struct A(i64);
    let a = A(1);
    let x = match &a {
        A(i) => A(*i),
    };
}
```

[Try the code on Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8e582bd2eb3bead0f8272ba2f6eabe3a)

Produces this invalid warning:

<img width="465" alt="Screenshot 2021-02-11 at 19 30 54" src="https://user-images.githubusercontent.com/42124/107674490-b0fe7c80-6c9f-11eb-9cfc-0cf45959430f.png">

This might be a duplicate of https://github.com/intellij-rust/intellij-rust/issues/6826.

**Comment by Undin** [comment] 2021-02-12 07:07
@wolverian Thanks for the report. I reproduced it.
Looks like the reason is not a but in our analysis but some incompatible API changes in the 2021.1 EAP that break the analysis.
It's already fixed in #6791. The fix will be included in next stable build next week. To try it right now, you can install nightly plugin version. See [instruction](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly) how to do it

**Closed by Undin** 2021-02-12 07:07 UTC
Labels: bug, subsystem::code insight
