### ISSUE TITLE
[Feature request]: Support Intra Rustdoc Links (RFC 1946)

### ISSUE THREAD

**Issue by kop** [intellij-rust/intellij-rust#5852] opened 2020-08-01 08:30 UTC
[RFC 1946](https://rust-lang.github.io/rfcs/1946-intra-rustdoc-links.html) (merged, pending stabilization) adds a notation how to create relative links in documentation comments (based on Rust item paths) and extend Rustdoc to automatically turn this into working links:

```
[Iterator](std::iter::Iterator)
[Iterator][iter], and somewhere else in the document: [iter]: std::iter::Iterator
[Iterator] or [`Iterator`] with automatically generated link reference definition
```

**Comment by PieterPenninckx** [comment] 2020-11-20 09:29
Update: [linking in rustdoc has now been stabilized](https://blog.rust-lang.org/2020/11/19/Rust-1.48.html#easier-linking-in-rustdoc).

**Comment by ozkriff** [comment] 2022-10-19 07:04
There seems to be an identical feature request issue created a little bit earlier - https://github.com/intellij-rust/intellij-rust/issues/4845 - I guess this should be closed as duplicate?

**Comment by neonaot** [comment] 2022-12-21 11:59
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/4845

**Closed by neonaot** 2022-12-21 11:59 UTC
