### ISSUE TITLE
Move statement up/down just moves the current line

### ISSUE THREAD

**Issue by tristanpemble** [intellij-rust/intellij-rust#9668] opened 2022-11-03 00:06 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.181.4965-222
* **Rust toolchain version:** 1.66.0-nightly
* **IDE name and version:** CLion 2022.2.4
* **Operating system:** macOS 12.4 (21F79)

## Problem description

the "Move Statement Up" and "Move Statement Down" actions used to move entire statements (functions, types, etc). It's only moving the current line.

## Steps to reproduce

![Screen Recording 2022-11-02 at 5 02 16 PM](https://user-images.githubusercontent.com/2466322/199624669-4ff6f0b6-21e9-4337-938f-ff605da536c1.gif)

**Comment by dima74** [comment] 2022-11-03 00:46
I can't reproduce it. Could you please check which shortcuts are assigned to `Move Statement Up/Down` and which are assigned to `Move Line Up/Down` actions? Maybe they conflict with each other

**Comment by tristanpemble** [comment] 2022-11-03 06:17
> I can't reproduce it. Could you please check which shortcuts are assigned to `Move Statement Up/Down` and which are assigned to `Move Line Up/Down` actions? Maybe they conflict with each other

I did check this first, and meant to include a screenshot; but it happens if I use the `Move Statement Up` from the action pallet. My keyboard shortcuts are bone-dry stock. Nonetheless:

<img width="179" alt="image" src="https://user-images.githubusercontent.com/2466322/199657941-4cb96db7-92a6-4f87-8016-dcd06449b9ff.png">

and

<img width="198" alt="image" src="https://user-images.githubusercontent.com/2466322/199657967-9b857a5b-1746-4fac-b6d2-deb0d40a89d8.png">

if you want I can recreate the video using the action pallet.

is there any kind of debugging or logs I can enable to help?

**Comment by tristanpemble** [comment] 2022-11-03 06:25
more clues; there's a difference in behavior of move line up and move statement up.

before:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/2466322/199658815-8d582b77-c286-45a6-b031-be2faedc93c3.png">

move line up:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/2466322/199658854-3a06d26c-23ce-4bb2-81d6-1c35806822ca.png">

move statement up:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/2466322/199658877-24cb8630-0805-4d9a-be8a-1b4e64b0ddbe.png">

note the differences in indentation.

**Comment by dima74** [comment] 2022-11-16 20:09
Looks like it is related to macOS
@ortem could you please take a look

**Comment by afetisov** [comment] 2022-11-21 23:27
@dima74 I'm confused that you can't reproduce it. I had the same bug for a long time (a year? something broke at one point). It happens on Linux and Windows. I though it's a well-known issue.

**Comment by afetisov** [comment] 2022-11-22 00:22
Solved it. The issue is that RsLineMover incorrectly called `super.checkAvailable`, which was responsible for initializing `MoveInfo`. If there are move providers which run before Rust ones, they properly initialize `MoveInfo` and Rust's moves work properly. If earlier move providers are unavailable, Rust slams into an empty `MoveInfo`, so all its move providers become disabled.

In tests, Xml and Json move providers always run before Rust ones, so the bug was hidden.

**Closed** 2022-11-22 17:46 UTC
Labels: bug, subsystem::fmt
