### ISSUE TITLE
Can't recognize `tokio TcpStream`

### ISSUE THREAD

**Issue by Future2100** [intellij-rust/intellij-rust#5419] opened 2020-05-22 02:38 UTC
As the title, when I use `tokio TcpStream`, rust can't find where it is but I can compile successfully.
(There would be something wrong with rust condition compilation.)

**Comment by Undin** [comment] 2020-05-22 07:28
See https://github.com/intellij-rust/intellij-rust/issues/4627#issuecomment-583407031

**Comment by Undin** [comment] 2020-05-22 07:28
Duplicate of #4627

**Closed by Undin** 2020-05-22 07:28 UTC
Labels: subsystem::macros, subsystem::type inference & resolve

**Comment by Future2100** [comment] 2020-05-22 10:53
Thanks a lot.
