### ISSUE TITLE
Incorrect "toolchain is incompatible with the plugin" message

### ISSUE THREAD

**Issue by danslapman** [intellij-rust/intellij-rust#686] opened 2016-09-24 14:36 UTC
![intellij-rust-bug](https://cloud.githubusercontent.com/assets/1708325/18809132/52f55822-827d-11e6-8ae8-b91dc47410d7.png)

**Comment by mkaput** [comment] 2016-09-24 15:05
Your cargo seems not to have `cargo metadata` command, hence the warning

**Comment by danslapman** [comment] 2016-09-24 15:08
Just executed `cargo metadata` in project's folder, works fine.

**Comment by johnthagen** [comment] 2016-09-24 17:53
Probably similar / duplicate of #659.

**Closed** 2016-09-26 15:13 UTC

**Comment by matklad** [comment] 2016-09-26 15:21
>Your cargo seems not to have cargo metadata command, hence the warning

Not sure what was the real issue, but turns out we executed cargo a bunch of times for no real reason. Perhaps something was wrong with concurrent Cargos? This has happend before.
