### ISSUE TITLE
Bug - removing {} from {self} leads to compilation error

### ISSUE THREAD

**Issue by e-oz** [intellij-rust/intellij-rust#1512] opened 2017-07-25 19:30 UTC
Please don't remove {} around "self" word.
Also I would be very pleasure to see some setting "Never remove non-space symbols from my code, commas, brackets and so on".

**Comment by farodin91** [comment] 2017-07-25 19:41
Could you add some code to reproduce this issue?

**Comment by e-oz** [comment] 2017-07-26 00:27
```rust
use rustc_serialize::json::{self};
```

**Comment by la10736** [comment] 2017-07-26 06:46
What you want?
```
use rustc_serialize::json
```
or leave it unchanged?

My taste is for removing it...

2017-07-26 2:27 GMT+02:00 Evgeniy OZ <notifications@github.com>:

**Comment by e-oz** [comment] 2017-07-26 09:16
@la10736 your taste leads to compilation error as I wrote in title of this issue. It should be left unchanged. And I don't understand why my code should be changed by somebody's else taste.

**Comment by mkaput** [comment] 2017-07-26 09:37
@e-oz , Why do you need
```rust
use rustc_serialize::json::{self}
```
instead of
```rust
use rustc_serialize::json
```
? (is there any semantic difference I don't know about?)

I think @la10736's taste meant removing whole `{self}` which I certainly 👍, while leaving only `self` is of course a bug

**Comment by e-oz** [comment] 2017-07-26 09:49
@mkaput because I prefer to don't have useless changes in git history. Somebody's taste is nothing for me and I don't want to care about it at all. If `use rustc_serialize::json::{self}` works - it should be just left untouched, despite of what somebody on the planet thinks about beauty of this line. If you will keep enforcing of changing my code to your taste, I will just be forced to not use this feature of your plugin. It would also help to prevent bugs like this. Currently I forced to spend some time to change my code just to be able to use this plugin - it's not a graceful behaviour of a plugin.

**Comment by matklad** [comment] 2017-07-26 10:02
Yeah, there are definitely at least two severe bugs here:

* We should never ever break the code by reformatting. 

* Our punctuation cleanups should be configurable.

I'll fix it as soon as possible! Unfortunately "as soon as possible" won't be super soon, because there's some stuff that prevents me from fixing it right now :( 

Thanks for feedback!

**Comment by matklad** [comment] 2017-07-26 10:03
>I prefer to don't have useless changes in git history. 

There's also a checkbox for "reformat code" dialog, which allows to reformat only non-committed code by default.

**Comment by la10736** [comment] 2017-07-26 12:00
Maybe the formatter should leave unchanged rows like 

```rust
use rustc_serialize::json::{self}
```
Change it into
```rust
use rustc_serialize::json
```
is an _Optimize imports_ duty.

Just for the record `rustfmt` remove the `self` part and leave just `use rustc_serialize::json`.

**Comment by la10736** [comment] 2017-07-26 12:12
I'm on it. First PR that not break code (leave unchanged). After we'll decide if make it configurable or demand to _Optimize Imports_ implementation

**Closed** 2017-07-26 13:37 UTC

**Comment by matklad** [comment] 2017-07-28 14:19
Ok, now there's a special checkbox in the settings to disable all "punctuation" changes the formatter can do (removing braces in uses, commans in match arms and adding `;` after returns):

![punct](https://user-images.githubusercontent.com/1711539/28721391-d38cd2a8-73b8-11e7-8092-7396d20c549f.png)

https://github.com/intellij-rust/intellij-rust/pull/1529

**Comment by e-oz** [comment] 2017-07-28 14:28
Thank you!
