### ISSUE TITLE
AssertionError: `X` is not a string literal

### ISSUE THREAD

**Issue by CraftSpider** [intellij-rust/intellij-rust#6815] opened 2021-02-07 22:10 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.141.3655-211-nightly
* **Rust toolchain version:** rustc 1.51.0-nightly (a2f8f6281 2021-01-27)
* **IDE name and version:** CLion 2021.1 EAP
* **Operating system:** Windows 10

## Problem description

Get constant 'experienced an error' messages, with the context
```
java.lang.AssertionError: `true` is not a string literal
	at org.rust.ide.injected.RsStringLiteralEscaperKt.escaperForLiteral(RsStringLiteralEscaper.kt:26)
	at org.rust.lang.core.psi.ext.RsLitExprMixin.createLiteralTextEscaper(RsLitExpr.kt:65)
	at com.intellij.ws.inspection.HttpUrlsUsageInspection.findLinkLiteral(HttpUrlsUsageInspection.kt:95)
	at com.intellij.ws.inspection.HttpUrlsUsageInspection.access$findLinkLiteral(HttpUrlsUsageInspection.kt:17)
	at com.intellij.ws.inspection.HttpUrlsUsageInspection$MyVisitor.visitElement(HttpUrlsUsageInspection.kt:66)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.rust.lang.core.psi.impl.RsExprImpl.accept(RsExprImpl.java:33)
	at org.rust.lang.core.psi.impl.RsLitExprImpl.accept(RsLitExprImpl.java:33)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:344)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:169)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$8(LocalInspectionsPass.java:344)
	at com.intellij.codeInspection.ex.InspectionEventsKt.reportWhenInspectionFinished(inspectionEvents.kt:9)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$9(LocalInspectionsPass.java:339)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1114)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:612)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

`true` isn't the only way the assertion fails, I've also seen integer literals in the error message.

## Steps to reproduce

Open any medium-sized project. I haven't tested with an entirely new project, but all my existing ones have the error. It seems to happen most often on files containing lines with iterator adapters, not sure if it's just the chained calls or something in the code it's trying to understand.

**Comment by Undin** [comment] 2021-02-07 22:24
Duplicate of #6754

**Comment by Undin** [comment] 2021-02-07 22:25
@CraftSpider see https://github.com/intellij-rust/intellij-rust/issues/6754#issuecomment-769590386

**Closed by Undin** 2021-02-07 22:24 UTC
Labels: bug, subsystem::code insight
