### ISSUE TITLE
References should be accepted in arithmetic expressions

### ISSUE THREAD

**Issue by umanwizard** [intellij-rust/intellij-rust#5246] opened 2020-04-16 16:28 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.120.2202-201
* **Rust toolchain version:** 1.42.0
* **IDE name and version:**
```
CLion 2020.1
Build #CL-201.6668.126, built on April 9, 2020
Licensed to Materialize, Inc. / Brennan Vincent
Subscription is active until August 20, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.7.0-rc1
GC: ParNew, ConcurrentMarkSweep
Memory: 19987M
Cores: 64
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: org.toml.lang, org.rust.lang
Current Desktop: ubuntu:GNOME
```
* **Operating system:** Ubuntu 20.04

## Problem description
Plugin highlights trying to add `T` and `&T` as an error, which rustc accepts.

## Steps to reproduce
```rust
pub fn add(x: u8, y: &u8) -> u8 {
    x + y
}
```

**Comment by Undin** [comment] 2020-04-17 11:25
It's because the corresponding `Add` trait `impl` is generated by macros. The default macro expansion engine doesn't handle them.
Try to enable new experimental macro engine (see #3628 for details). It should help

**Comment by Undin** [comment] 2020-04-17 11:26
Duplicate of #4328

**Closed by Undin** 2020-04-17 11:26 UTC
Labels: bug, subsystem::macros, subsystem::type inference & resolve

**Comment by umanwizard** [comment] 2020-04-17 15:19
Thanks @Undin . I can't believe I opened the same issue twice. I must have forgotten the old one. My apologies for the spam!
