### ISSUE TITLE
IntelliSense doesn't work for procedural macro generated code.

### ISSUE THREAD

**Issue by CryoMyst** [intellij-rust/intellij-rust#10646] opened 2023-07-04 04:19 UTC
## Environment

Rust Plugin - 0.4.197.5401-231
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.72.0-nightly (f7ca9df69 2023-06-24)
CLion 2023.1.4 (Build #CL-231.9161.40, built on June 20, 2023)
Arch Linux - 6.3.9-arch1-1

## Steps to reproduce
1. Create a procedural macro crate with the following macro
```rust
extern crate proc_macro;

#[proc_macro_attribute]
pub fn create_struct_at_start_of_method(
    attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    let mut attr = syn::parse_macro_input!(attr as syn::Type);
    let mut item = syn::parse_macro_input!(item as syn::ItemFn);
    
    item.block.stmts.insert(
        0,
        syn::parse_quote! {
            let some_struct = #attr::default();
        },
    );
    
    let output = quote::quote! {
        #item
    };
    output.into()
}
```
2. Reference the procedural macro crate with another crate and use the macro with any type that derives Default
```rust
#[cfg(test)]
mod tests {
    use testing_macro::create_struct_at_start_of_method;
    
    #[test]
    #[create_struct_at_start_of_method(SomeStruct)]
    fn testing_macros() {
        println!("Struct.a: {}", some_struct.0); // No intellisense on some_struct
        assert_eq!(2 + 2, 4);
    }
    
    #[derive(Default)]
    struct SomeStruct(i32);
}
```
3. Try and use intellisense on the new `some_struct` variable that was inserted at the beginning of the function.

Images:
Intellij-rust does not see the new `some_struct` variable
![No intellisense](https://github.com/intellij-rust/intellij-rust/assets/38846413/aaccf88d-4b67-4cce-9498-d4382e39306a)
VSCode does see the new `some_struct` variable and is able to provide intellisense on it.
![VSCode](https://github.com/intellij-rust/intellij-rust/assets/38846413/204fcf6e-0850-4c19-b370-4d2b67574072)

**Comment by vlad20012** [comment] 2023-07-04 09:19
The issue is fixed in the nightly plugin. You can try it now (see [instructions](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly))

**Comment by CryoMyst** [comment] 2023-07-04 10:15
I am now using `0.4.198.5424-231-nightly` from the `https://plugins.jetbrains.com/plugins/nightly/8182` repository and this still seems to be the case.
![image](https://github.com/intellij-rust/intellij-rust/assets/38846413/d393354d-2b48-4ac9-9a97-c378e28ed1e5)
![image](https://github.com/intellij-rust/intellij-rust/assets/38846413/985e870e-778e-4497-8e69-57336c3beac0)

**Comment by vlad20012** [comment] 2023-07-04 12:19
Ah, I'm sorry, I didn't read the issue description carefully enough. I think #9834 should solve the issue, but I don't see it as a high-priority issue because attribute macros usually don't introduce new names into the function they're applied to. Anyway, #9834 will be landed eventually

**Closed** 2024-09-05 16:33 UTC
