### ISSUE TITLE
STDOUT falsely considered an internal call

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#6973] opened 2021-03-15 20:11 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.144.3732-211-nightly
* **Rust toolchain version:** 1.52.0-nightly (b3e19a221 2021-03-12) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2 EAP (CL-212.936)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

My innocent STDOUT is considered a part of an internal call. I guess I was unlucky with the format

![internal](https://user-images.githubusercontent.com/2500320/111214903-904d7d80-85e3-11eb-95da-3aa538fd775d.gif)

## Steps to reproduce

```rust
fn main() {
    let haystack = [1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862];

    for item in &haystack {
        let result = match item {
            42 | 132 => "hit",
            _ => "miss",
        };

        if result == "hit" {
            println!("{}: {}", item, result);
        }
    }
}
```

**Comment by Undin** [comment] 2021-03-16 06:04
Duplicate of #6924

**Closed by Undin** 2021-03-16 06:04 UTC
Labels: bug, subsystem::build & run
