### ISSUE TITLE
Unary operator returning other type not supported

### ISSUE THREAD

**Issue by wrnrlr** [intellij-rust/intellij-rust#9004] opened 2022-07-04 12:54 UTC
In rust it is allowed when overloading a unary/binary operator to return another type.

```rust
impl Not for Plane {
  type Output = Point;
  fn not(self)->Point { Point { p3: self.p0 }}
}
```

But the plugins syntax checker always assumes it is the same type.

## Environment

* **IntelliJ Rust plugin version: 0.4.172**
* **Rust toolchain version: all**

**Comment by Undin** [comment] 2022-07-05 17:01
Duplicate of #6589

**Closed by Undin** 2022-07-05 17:01 UTC
Labels: subsystem::type inference & name resolution
