### ISSUE TITLE
mismatched types [E0308]expected `DateTime<Utc>`, found `DateTime<Utc>`

### ISSUE THREAD

**Issue by juev** [intellij-rust/intellij-rust#6087] opened 2020-09-08 16:52 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.130.3337-202
* **Rust toolchain version:** 1.46.0 (04488afe3 2020-08-24) x86_64-apple-darwin
* **IDE name and version:** GoLand 2020.2.2 (GO-202.6948.9)
* **Operating system:** macOS 10.15.6

## Problem description

I have some `main.rs` file for run new sdk functions.

```rust
use anyhow::Result;
use chrono::*;
use dotenv::dotenv;
use invest_openapi_rs_sdk::rest_client::*;
use std::env;

fn main() -> Result<()> {
    dotenv().ok();
    let token = env::var("TOKEN").unwrap();
    let rest_client = RestClient::new_sandbox(token);
    let operations = rest_client.operations(
        "",
        Utc::now() - Duration::days(7),
        Utc::now(),
        "BBG000BB88K4",
    )?;
    println!("{:?}", operations);

    Ok(())
}
```
intelij-rust got errors:
mismatched types [E0308]expected `DateTime<Utc>`, found `DateTime<Utc>`

and compile without issues.

## Steps to reproduce

Create file, run. Run withotu issues, but Goland prodused errors.

**Comment by LeaveHM123** [comment] 2020-09-10 06:14
Also encountered a similar problem and I am very confused！

**Comment by Maksim20023** [comment] 2023-07-28 16:51
Hi! I’m closing this ticket because the issue does not reproduce in the current environment (GoLand 2023.2 Build #GO-232.8660.185, Rust plugin 0.4.199.5415-232). If this issue still reproduces for you, please reopen the ticket.

**Closed by Maksim20023** 2023-07-28 16:51 UTC
Labels: subsystem::type inference & name resolution, bug
