### ISSUE TITLE
Broken configuration on FreeBSD

### ISSUE THREAD

**Issue by alexdupre** [intellij-rust/intellij-rust#4425] opened 2019-09-23 08:18 UTC
## Environment

* **IntelliJ Rust plugin version:**
0.2.105.2133-192

* **Rust toolchain version:**
This is the official rust from the FreeBSD package system
```
% /usr/local/bin/rustc --version --verbose
rustc 1.36.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-freebsd
release: 1.36.0
LLVM version: 8.0
```
* **IDE name and version:**
IntelliJ IDEA 2019.2.2

* **Operating system:**
FreeBSD 12.0

## Problem description
The plugin doesn't seem to recognize a cargo project, I guess the issue is due to the following unhandled NPE in parsing a date, probably the `commit-hash` date above that is `unknown`
```
2019-09-23 10:07:39,474 [3024922]   INFO - rust.openapiext.CommandLineExt - Executing `/usr/local/bin/rustc --print sysroot` 
2019-09-23 10:07:39,529 [3024977]   INFO - rust.openapiext.CommandLineExt - Executing `/usr/local/bin/rustc --version --verbose` 
2019-09-23 10:07:39,584 [3025032]  ERROR -    #org.rust.stdext.AsyncValue - java.lang.NullPointerException: text 
java.util.concurrent.CompletionException: java.lang.NullPointerException: text
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:827)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException: text
        at java.util.Objects.requireNonNull(Objects.java:228)
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1848)
        at java.time.LocalDate.parse(LocalDate.java:400)
        at java.time.LocalDate.parse(LocalDate.java:385)
        at org.rust.cargo.toolchain.RustToolchainKt.scrapeRustcVersion(RustToolchain.kt:150)
        at org.rust.cargo.toolchain.RustToolchainKt.access$scrapeRustcVersion(RustToolchain.kt:1)
        at org.rust.cargo.toolchain.RustToolchain.queryVersions(RustToolchain.kt:29)
        at org.rust.cargo.project.model.impl.CargoProjectImplKt$fetchRustcInfo$1.invoke(CargoProjectImpl.kt:566)
        at org.rust.cargo.project.model.impl.CargoProjectImplKt$fetchRustcInfo$1.invoke(CargoProjectImpl.kt)
        at org.rust.openapiext.AsyncTasksKt$runAsyncTask$1.run(AsyncTasks.kt:34)
        at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
        at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

## Steps to reproduce

1) install Intellij IDEA and rust from FreeBSD packages
2) install the IntelliJ-Rust plugin
3) create a new rust project

**Comment by Undin** [comment] 2019-09-23 08:35
Duplicate of #4372

**Closed by Undin** 2019-09-23 08:35 UTC
Labels: bug, tools
