### ISSUE TITLE
Font size issue with type hints

### ISSUE THREAD

**Issue by hpwxf** [intellij-rust/intellij-rust#5480] opened 2020-06-01 16:08 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.122.3105-201
* **Rust toolchain version:** 1.43.1 (8d69840ab 2020-05-04)
* **IDE name and version:** CLion 2020.1.1 (Build #CL-201.7223.86)
* **Operating system:** macOS Catalina (10.15.5)

## Problem description
Hint font size for type annotation becomes desynchronized from the current text size after zoom in/out using mouse wheel.

Examples:
![Capture d’écran 1](https://user-images.githubusercontent.com/26146722/83427896-c1343b80-a431-11ea-95bf-d7d7c519a09f.png)
![Capture d’écran 10](https://user-images.githubusercontent.com/26146722/83427902-c42f2c00-a431-11ea-9ac3-be6df86d3cc1.png)

## Steps to reproduce
* Open a .rs file (fonts are ok)
* Do zoom in or out using mouse wheel (fonts are not OK but the difference is not so big)
* Do opposite zoom (out or in) using mouse wheel 

These steps use mouse wheel zoom:
![Capture d’écran 7](https://user-images.githubusercontent.com/26146722/83428025-f50f6100-a431-11ea-9819-1b2d82aa1e3e.png)

**Comment by Undin** [comment] 2020-06-13 07:15
@hpwxf inlay hints rendering is platform feature so this bug is platform bug
Looks like it's duplicate of https://youtrack.jetbrains.com/issue/IDEA-232560

**Closed by Undin** 2020-06-13 07:15 UTC
Labels: subsystem::hints
