### ISSUE TITLE
Clion gives an error E0277 but code compiles and work

### ISSUE THREAD

**Issue by p0lunin** [intellij-rust/intellij-rust#4568] opened 2019-10-25 16:10 UTC
##  Environment

* **IntelliJ Rust plugin version:** 0.2.106.2135-192
* **Rust toolchain version:** rustc 1.37.0 (eae3437df 2019-08-13)
* **IDE name and version:** CLion 2019.2
* **Operating system:** Windows 10

## Problem description
I have the code which compiles and work, but CLion gives errors.

## Steps to reproduce

Code:
```rust
trait Foo {
    fn bar(self) -> Bar<Self> where Self: Sized
    {
        Bar::new(self)
    }
}

struct Bar<T>(T);

impl<T> Bar<T> {
    pub fn new(t: T) -> Self {
        Bar {
            0: t
        }
    }
}

struct FooStruct {}

impl Foo for FooStruct {}

fn main() {
    let foo = FooStruct {};
    let bar = foo.bar();
}
```
errors in lines 2:
1. The trait bound `Bar<Self>: std::marked::Sized` is not satisfied [E0277].
2. `Bar<Self>` does not have a constant size known at compile-time.

I bad understand what are doing this code, but it compiles, and CLion gives errors, so i created this issue.

**Comment by Undin** [comment] 2020-02-09 09:28
Duplicate of #2530

**Closed by Undin** 2020-02-09 09:28 UTC
Labels: bug, subsystem:type inference & resolve
