### ISSUE TITLE
Spell checking on lifetimes

### ISSUE THREAD

**Issue by ericpubu** [intellij-rust/intellij-rust#5858] opened 2020-08-02 19:52 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.1.127.3249-202
* **Rust toolchain version:** 1.45.1
* **IDE name and version:** CLion 2020.2
* **Operating system:** Manjaro Linux

## Problem description
If a lifetime has an English word is marked as a typo by the editor, taking the `'` as part of the word, it should be ignored and spellcheck just the word, it happens with all words, most noticeable is the special `'static` lifetime  

## Steps to reproduce
* Create a lifetime with a valid English word
```
pub trait CompanyRepository: Send + Sync + 'static {
    fn get_all(&self) -> RepositoryResult<Vec<Company>>;
}
```

![Screenshot_20200802_144128](https://user-images.githubusercontent.com/18682359/89131041-aaf93900-d4cf-11ea-8c5e-05a3159632a9.png)

**Comment by Undin** [comment] 2020-08-02 20:02
Duplicate of #5551

**Closed by Undin** 2020-08-02 20:02 UTC
Labels: bug, subsystem::code insight
