### ISSUE TITLE
Missing highlight on import entity from crate with the same name

### ISSUE THREAD

**Issue by fan-tom** [intellij-rust/intellij-rust#4186] opened 2019-07-26 08:42 UTC
## Environment

* **IntelliJ Rust plugin version:**
v0.2.102.2130-191

## Problem description
When I import function/macro with the same name as crate, highlighting and resolve get broken
![изображение](https://user-images.githubusercontent.com/14140464/61938621-fc144a00-afaa-11e9-8d02-44f37f89da8d.png)
![изображение](https://user-images.githubusercontent.com/14140464/61938637-05051b80-afab-11e9-8ef9-f77c9bc4dd3b.png)
![изображение](https://user-images.githubusercontent.com/14140464/61938647-0df5ed00-afab-11e9-8a6f-14269151239a.png)
![изображение](https://user-images.githubusercontent.com/14140464/61938686-21a15380-afab-11e9-8bd0-f2e0786a58b9.png)
![изображение](https://user-images.githubusercontent.com/14140464/61938713-2a922500-afab-11e9-9bc7-c42b55a54303.png)

**Comment by alexbool** [comment] 2019-11-24 13:52
This is extremely annoying :(

**Comment by Undin** [comment] 2020-01-09 01:42
Duplicate of #4509

**Closed by Undin** 2020-01-09 01:42 UTC
Labels: bug, type inference & resolve

**Comment by Undin** [comment] 2020-01-09 01:45
@fan-tom although this issue was created earlier than #4509, #4509 has more detailed description. So I've close this one as duplicate
Thanks for the report!
