### ISSUE TITLE
Private module in crate shadows exported functions of same name in that crate

### ISSUE THREAD

**Issue by tdyas** [intellij-rust/intellij-rust#4717] opened 2019-12-03 06:19 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.111.2147-193 Dec 02, 2019
* **Rust toolchain version:** 1.39.0
* **IDE name and version:** IntelliJ Ultimate 2019.3 (Build #IU-193.5233.102)
* **Operating system:** Ubuntu 19.10

## Problem description

When importing a function from a crate that has the same name as a private module in that crate, the plugin jumps to the private module when using jump to definition instead of the exported function. Case in point is the `tokio` crate v0.2.2 and the name `tokio::time::timeout`. The expected behavior would be to jump to the function definition within that crate.

## Steps to reproduce

See project at https://github.com/tdyas/tftp-rs. In https://github.com/tdyas/tftp-rs/blob/master/src/conn.rs, use jump to definition on timeout on line 8 or line 132. For line 8, it finds the private module in the tokio crate, for line 132, it says that it cannot find the definition of the exported timeout function.

Interesting point: The tokio crate is using `pub use` to export the function from a submodule of the same name.

**Comment by MightyPork** [comment] 2020-04-28 08:40
some screenshots of this bug, as I just came here to report the same:

![Screenshot_20200428_103707](https://user-images.githubusercontent.com/2041118/80466170-71e38280-893c-11ea-9f2c-08b7646c6767.png)

![Screenshot_20200428_103728](https://user-images.githubusercontent.com/2041118/80466177-760fa000-893c-11ea-911f-c3149f55f8bc.png)

tokio uses a macro to declare the module, so, further, intellij-rust has problems indexing the file (thinks it is not included in module tree)

```rust
cfg_time! {
    pub mod time;
}


macro_rules! cfg_time {
    ($($item:item)*) => {
        $(
            #[cfg(feature = "time")]
            #[cfg_attr(docsrs, doc(cfg(feature = "time")))]
            $item
        )*
    }
}
```

**Comment by Undin** [comment] 2020-04-28 08:58
Try to enable new experimental macro expansion engine (see #3628 for details). It should help

**Comment by Undin** [comment] 2020-04-28 08:58
Duplicate of #4627

**Closed by Undin** 2020-04-28 08:58 UTC
Labels: bug, subsystem::code insight, subsystem::macros

**Comment by MightyPork** [comment] 2020-04-28 09:07
the new macro expander is very slow (like, really), but enabling it fixed the issue :+1:

**Comment by Undin** [comment] 2020-04-28 09:10
> the new macro expander is very slow (like, really)

@MightyPork what exactly slow? Expansion phase at the start or something else?

**Comment by MightyPork** [comment] 2020-04-28 09:16
I'm not really sure, it always did one step (of 66 or so) and then reindexed it. Unless it needs to run frequently it should be OK - and you have an excuse to stretch or get a coffee
