### ISSUE TITLE
Add Rust to New Solution for Rider

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#8510] opened 2022-02-04 11:27 UTC
## Problem description
There is no Rust on New Solution window on Rider
<img width="799" alt="Screenshot 2022-02-04 at 12 25 30" src="https://user-images.githubusercontent.com/1213122/152521161-ac9ecd11-6b16-41d5-a324-f2c371b5cca5.png">

**Comment by ozkriff** [comment] 2022-02-04 11:29
Related (duplicate?) https://github.com/intellij-rust/intellij-rust/issues/7312

**Comment by mili-l** [comment] 2022-02-04 12:41
@ozkriff yep, thank you!

**Comment by Undin** [comment] 2022-02-05 08:57
duplicate of #7312

**Closed by Undin** 2022-02-05 08:57 UTC
Labels: feature, subsystem::ui
