### ISSUE TITLE
Feature request: Allow customizing macro expansion depth

### ISSUE THREAD

**Issue by nazar-pc** [intellij-rust/intellij-rust#7911] opened 2021-09-28 22:10 UTC
Macro expansion currently stops at depth of 64, while in Substrate-based projects there are many macros and I suspect IDE can help more if more expansion is allowed (Substrate's runtime is configured to recursion depth of 256 by default).

I searched in registry and settings and didn't find an option to customize this.

**Comment by Undin** [comment] 2022-03-26 22:54
Duplicate of #6681

**Closed by Undin** 2022-03-26 22:54 UTC
Labels: improvement, subsystem::macros
