### ISSUE TITLE
"Rust generator"(yield) missing color syntax highlight

### ISSUE THREAD

**Issue by Horki** [intellij-rust/intellij-rust#2434] opened 2018-04-04 10:06 UTC
keyword "yield" is missing color syntah (using Clion 2018.1 with Rust plugin), example as here [link](https://doc.rust-lang.org/nightly/unstable-book/language-features/generators.html)

**Comment by Undin** [comment] 2018-04-04 10:43
Duplicate of #2203

**Closed by Undin** 2018-04-04 10:43 UTC
