### ISSUE TITLE
Variable is unused when it only appears in a string format

### ISSUE THREAD

**Issue by CLOVIS-AI** [intellij-rust/intellij-rust#8932] opened 2022-06-13 12:29 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.171.4656-221
* **Rust toolchain version:** 1.60.0 (7737e0b5c 2022-04-04) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.1.2 (CL-221.5787.29)
* **Operating system:** Linux 5.18.1-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

If a variable is only used in a string format, it shows up as unused in the IDE.

## Steps to reproduce

```rust
fn foo(a: usize) -> String {
    format!("{a}")
}
```

The IDE reports that the variable `a` is unused.
Also happens in other template macros (`write!`, etc) and other variable types (as a bound variable in a `match` statement, etc).

**Comment by neonaot** [comment] 2022-06-13 13:27
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/8417

**Closed by neonaot** 2022-06-13 13:27 UTC
