### ISSUE TITLE
Add keyword completion

### ISSUE THREAD

**Issue by auduchinok** [intellij-rust/intellij-rust#7173] opened 2021-04-25 14:34 UTC
When trying to type in [this example](https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html#handling-invalid-input), there's no lookup items for keywords, so `continue` has to be typed in manually.

<img width="675" alt="Screenshot 2021-04-25 at 17 32 06" src="https://user-images.githubusercontent.com/3923587/115997590-44cbbd80-a5ec-11eb-9ff7-c1406328a269.png">

## Environment

* **IntelliJ Rust plugin version:** 0.3.145.3797-211
* **Rust toolchain version:** 1.50.0 aarch64-apple-darwin
* **IDE name and version:** CLion 2021.1.1 (CL-211.7142.21)
* **Operating system:** macOS 11.2.2
* **Macro expansion engine:** new
* **Name resolution engine:** new

**Comment by Kobzol** [comment] 2021-04-26 05:59
Closing as a duplicate of https://github.com/intellij-rust/intellij-rust/issues/6524 (a PR is already in works).

**Closed by Kobzol** 2021-04-26 05:59 UTC
