### ISSUE TITLE
Semantic coloring for macro invocations

### ISSUE THREAD

**Issue by HighCommander4** [intellij-rust/intellij-rust#4800] opened 2019-12-28 21:58 UTC
Invocations of complex macros, such as [`error_chain!`](https://docs.rs/error-chain/0.12.1/error_chain/index.html) currently receive no semantic coloring (only basic lexical coloring like string literals and keywords).

While technically a macro invocation is just "token soup", it should be possible to give the tokens a fairly good coloring as follows:

  * keep track of a mapping between tokens in the invocation, and occurrences of those tokens in the expansion
  * for each token in the invocation, compute how each occurrence in the expansion would be colored
  * if all occurrences in the expansion would be colored the same (e.g. all occurrences name a struct), apply that color to the token in the invocation

**Comment by Undin** [comment] 2019-12-28 22:01
@HighCommander4 I think it's already implemented in #4640

**Comment by Undin** [comment] 2020-01-06 06:18
Duplicate of #3706

**Closed by Undin** 2020-01-06 06:18 UTC
Labels: feature, macros
