### ISSUE TITLE
Rust: IntelliJ markes safe intrinsics as unsafe

### ISSUE THREAD

**Issue by ljchen1** [intellij-rust/intellij-rust#8761] opened 2022-04-18 04:28 UTC
From https://youtrack.jetbrains.com/issue/IDEA-292347

***What steps will reproduce the issue?***
1. Install the Rust nightly toolchain (`rustup toolchain install nightly`)
2. Install the Rust plugin
3. Create a new Rust plugin using the Nightly toolchain
4. Enter the following code into `main.rs`:
``` rust
#![feature(core_intrinsics)]

use std::intrinsics::{add_with_overflow, likely};

fn main() {
    if likely(true) {}
    let x = add_with_overflow(1, 2);
}
```
5. Verify that it compiles fine

***What is the expected result?***
IntelliJ's analysis should not indicate any errors as `likely` and `add_with_overflow` are two examples of safe (experimental) intrinsics, see [the docs](https://doc.rust-lang.org/std/intrinsics/#functions).

***What happens instead?***
IntelliJ marks the use of `likely` and `add_with_overflow` as "Call to unsafe function requires unsafe function or block [E0133]".

![image](https://user-images.githubusercontent.com/103916765/163754432-d4298311-0713-40fe-be74-d1e318b79b34.png)

**Software:**
IntelliJ Ultimate 2022.1
Build #IU-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Rust plugin version: 0.4.168.4555-221
Rust toolchain version: 1.59.0-nightly
Rust edition used in project's Cargo.toml: 2021

**Comment by Undin** [comment] 2022-04-18 07:35
Duplicate of #3129

**Closed by Undin** 2022-04-18 07:35 UTC
Labels: bug, subsystem::highlighting
