### ISSUE TITLE
There is a problem that I cannot create a 

### ISSUE THREAD

**Issue by mySeraphine** [intellij-rust/intellij-rust#7263] opened 2021-05-27 15:54 UTC
## Environment

* **IntelliJ Rust plugin version:**
* **Rust toolchain version:**
* **IDE name and version:**
* **Operating system:**

**Comment by Kobzol** [comment] 2021-05-27 16:17
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/7263.

**Closed by Kobzol** 2021-05-27 16:17 UTC
Labels: duplicate
