### ISSUE TITLE
Issue of processing modules declared inside macro

### ISSUE THREAD

**Issue by skyao** [intellij-rust/intellij-rust#5258] opened 2020-04-19 01:17 UTC
This problem is due to the modules declared inside macro, there are many issues related to this, like:

#4914 
#4714 

From above issues, it said that the problem is fixed. But when I tried to use clion and tokio, it reaappeard.

- clion: the lated version 2020.1
- intellij-rust plugin version: 0.2.120.2202-201, released in 2020-04-13

## Environment

* **IntelliJ Rust plugin version:**. 0.2.120.2202-201, released in 2020-04-13
* **Rust toolchain version:** 1.42.0
* **IDE name and version:**. clion 2020.1
* **Operating system:**.  linux mint 19.3 

## Problem description

As described in above issues.

## Steps to reproduce

cargo.toml

```toml
tokio = { git = "https://github.com/tokio-rs/tokio", features = ["full", "tcp"] }
```

then:

```rust
use std::future::Future;
use tokio::net::TcpListener;

pub async fn run(listener: TcpListener, shutdown: impl Future) -> crate::Result<()> {

    println!("server stopped");
    Ok(())
}
```

Here clion reports: "Unresolved reference: `TcpListener`  "

**Comment by Undin** [comment] 2020-04-19 07:21
Please, see https://github.com/intellij-rust/intellij-rust/issues/4627#issuecomment-583407031

**Comment by Undin** [comment] 2020-04-19 07:21
Duplicate of #4627

**Closed by Undin** 2020-04-19 07:21 UTC
Labels: subsystem::macros, subsystem::type inference & resolve

**Comment by skyao** [comment] 2020-04-19 14:41
So, let's keep this issue open until new macro expansion engine is enabled by default

OK, I got it --- it is due to new macro expansion engine is NOT enabled by default. I change the setting in clion and it works.

Thank you !
