### ISSUE TITLE
Cargo project update failed: No Rust toolchain / "This feature is only available in Edition 2018"

### ISSUE THREAD

**Issue by bootrino** [intellij-rust/intellij-rust#6254] opened 2020-10-13 20:54 UTC
## Environment

* **IntelliJ Rust plugin version:**
0.3.132.3395-202
* **Rust toolchain version:**
% rustc --version
rustc 1.47.0 (18bf6b4f0 2020-10-07)
% cargo --version
cargo 1.47.0 (f3c7e066a 2020-08-28)
hotqueue@Andrews-Mini ~ %
* **IDE name and version:**
Pycharm 20.2.3
* **Operating system:**
OSX 10.15.6

## Problem description
Cargo project update failed:
		No Rust toolchain

Also, the "async" keyword in code is red underlined and hovering says:
This feature is only available in Edition 2018

## Steps to reproduce
Install latest Pycharm, latest Rust, latest Intellij Rust plugin

I think the problem might occur when the Rust project is not in the root directory of the Pycharm project.

See these two screenshots in which the rust project is in root (works) and when it is not in root not working).

![Screen Shot 2020-10-14 at 7 52 14 am](https://user-images.githubusercontent.com/22624099/95915106-6a346f00-0df2-11eb-9037-cb0b3cbef526.png)

![Screen Shot 2020-10-14 at 7 51 55 am](https://user-images.githubusercontent.com/22624099/95915128-715b7d00-0df2-11eb-8dc0-c40c90a2572c.png)

**Comment by Undin** [comment] 2020-10-14 07:23
The issue with "No Rust toolchain" seems to be a duplicate of #6193

About `async` keyword and "This feature is only available in Edition 2018" - as you can see on your screenshot there is `No Cargo project found` warning. It means that there isn't any Cargo project in the plugin project structure. As a result, plugin knows nothing about your package including its edition. You can attach it via `Attach` action at the warning panel and choose either `Cargo.toml` of the package or its root directory

**Comment by Undin** [comment] 2020-10-14 07:33
I think this issue can be closed.
@bootrino don't hesitate to reopen it if attaching package doesn't help

**Closed by Undin** 2020-10-14 07:33 UTC
