### ISSUE TITLE
Plugin does not highlight undefined variables

### ISSUE THREAD

**Issue by lynkas** [intellij-rust/intellij-rust#5698] opened 2020-07-05 05:02 UTC
## Environment

* **IntelliJ Rust plugin version: 0.2.123.3132-193**
* **Rust toolchain version: 1.44.1**
* **IDE name and version: Intellij IDEA and CLion**
* **Operating system: Windows 10, 2004**

## Problem description
Using undefined variables but no any error provided. 
![image](https://user-images.githubusercontent.com/22864418/86525899-62922f80-bebf-11ea-833b-5dbd609318ea.png)

This happens in both IDEA and CLion. Although #3146 states a similar situation, but the option in that issue is gone now. All the settings are default.

**Comment by Undin** [comment] 2020-07-05 07:07
Currently, there are two ways to solve your issue:
- turn on cargo check as an external linter. Enable `Preferences | Languages & Frameworks | Rust | Cargo | Run external linter to analyze code on the fly` option. Note, it's CPU consuming especially on large projects
- Turn off `Ignore unresolved references without quick fix` option of `Rust | Unresolved reference` inspection in `Preferences | Editor | Inspections` settings. Note, it may lead to false-positive error annotations.

**Comment by Undin** [comment] 2020-07-05 07:09
BTW 2019.3 IDEs are no longer supported by the plugin

**Comment by Undin** [comment] 2020-07-05 07:12
I've added both options as workarounds in the original issue.
So I think this issue can be closed.
Duplicate of #3146

**Closed by Undin** 2020-07-05 07:12 UTC
Labels: feature, subsystem::code insight

**Comment by Pfiver** [comment] 2021-12-30 13:54
Why is the option enabled by default? Although I have a vague idea what the possible reasons might be, as a new user it is not a very intuitive default and hard to find the "workaround". Why does this need a workaround in the first place?
