### ISSUE TITLE
Debugger: Strings and string slices cannot be read from memory when passed into function 

### ISSUE THREAD

**Issue by maljaroudi** [intellij-rust/intellij-rust#6703] opened 2021-01-20 21:14 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.139.3615-203
* **Rust toolchain version:** 1.49.0
* **IDE name and version:** CLion CL-203.6682.181
* **Operating system:** Windows 10 2004 

## Problem description
When passing a string or a string slice to a function, the debugger is unable to read the memory of the passed in variable. However, it's able to read it after cloning it into a variable inside the function.

## Steps to reproduce

1- declare a string or a string slice variable (or both). 
2- write a function that takes the string or slice as parameter.
3- place breakpoint into the function. 
4- check the variables tab for the passed in variable value. 
5- the value will say "error = read memory from 0x  failed (0 of 1 bytes read)."

```
fn main() {
    println!("Hello, world!");

    let tester = "This is a test &str for the debugger";

    take_str(tester);
    let test_num = 555;
    take_i32(test_num);


    let test_string_sample = String::from("This is a test");
    take_string(test_string_sample);
}




fn take_str(test_str: &str) {
    let copy = test_str.clone();
    println!("{}", copy);
}

fn take_i32(test_i32: i32) {
    let copy = test_i32.clone();
    println!("{}", copy);
}

fn take_string(test_string: String){
    let copy = test_string.clone();
    println!("{}", copy);
}
```
place breakpoints on each function and check the variables. i32 seem to pass, but the string and str functions' variables doesn't seem to appear when debugging.

**Comment by MauriceKayser** [comment] 2021-01-25 10:46
This might be a duplicate of #6676

**Comment by ortem** [comment] 2021-01-25 15:46
@maljaroudi Thank you for reporting and finding out that cloning into a variable fixes the problem!

@MauriceKayser You're right, let's use https://github.com/intellij-rust/intellij-rust/issues/6676 to avoid duplicating

**Closed by ortem** 2021-01-25 15:46 UTC
Labels: bug, duplicate, subsystem::debugger
