### ISSUE TITLE
Recent updates possibly causing missing Code completion

### ISSUE THREAD

**Issue by tbraun96** [intellij-rust/intellij-rust#4929] opened 2020-02-06 14:37 UTC
rust version: 1.43 nightly
Intellij Rust version: 116 (most recent)
OS: Windows 10
IntelliJ version: 2020 EAP (also didn't work in the latest 2019 version)

Suppose I have this inside the text area:
```rust
use slab::Slab;
use mio::net::UdpSocket;
use mio::{Events, Interest, Poll, Token};
use std::rc::Rc;

pub struct MioHandler {
    tokens: Slab<Token>,
    sockets: Vec<Rc<UdpSocket>> /// UdpSocket is red, even though it's imported above
}
```

This happens for many types too. Further, I've also noticed that an already imported type's intellisense-completion (I don't know the jargon here. What I mean is the menu that pops-up once you type my_var then ".") does not show up. Essentially, things are marked missing when they are not.

**Comment by Undin** [comment] 2020-02-07 14:12
It's fixed in #4914 and will be landed in the next release (I hope).
I close this issue as a duplicate of #4627 because they have the same reason

**Closed by Undin** 2020-02-07 14:12 UTC
Labels: bug, subsystem:macros, subsystem:type inference & resolve
