### ISSUE TITLE
Running tests does not use integrated test runner

### ISSUE THREAD

**Issue by phkeese** [intellij-rust/intellij-rust#10531] opened 2023-06-02 09:22 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.195.5408-231
* **Rust toolchain version:** 1.70.0 (90c541806 2023-05-31) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2023.1.3 (CL-231.9011.31)
* **Operating system:** Windows 11.0
* **Macro expansion:** enabled

## Problem description
Running tests using `cargo test` or the integrated run button does not show test results in the integrated test runner.
On macOS, the runner opens and shows an entry for each test.
This is annoying and does not reflect the desired behavior as described in [the plugin documentation](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-testing.html#view-test-results).
This issue occurs with both the old and new UI.

## Steps to reproduce
1. Create or download a new project with tests
2. Execute tests using either `cargo test` and Ctrl + Enter or by pressing the run button 
![image](https://github.com/intellij-rust/intellij-rust/assets/26239210/fef54d80-cf1f-45a1-9ade-a28ea0db80f0)
3. Tests are executed, but the integrated test runner does not show them 
![image](https://github.com/intellij-rust/intellij-rust/assets/26239210/3d1068f9-93ef-4b50-97a5-f831c8a33799)
How it should look (old UI):
![Documentation Image](https://plugins.jetbrains.com/api/webhelp/8182/d7e084ff-61e1-409a-b4fb-588dfaf7be76/img/rust_testing_results.png)

**Comment by sanri** [comment] 2023-06-02 09:34
I had the same problem with the MacOS.

> Running tests using cargo test or the integrated run button does not show test results in the integrated test runner.

### Environment

- IntelliJ Rust plugin version: 0.4.195.5408-231
- Rust toolchain version: 1.70.0 (90c541806 2023-05-31) x86_64-apple-darwin
- IDE name and version: CLion 2023.1.3 (CL-231.9011.31)
- Operating system: MacOS 12.6.6
- Macro expansion: enabled

**Comment by vlad20012** [comment] 2023-06-02 11:14
This regression is caused by the recent changes in the Rust test framework released within Rust 1.70, and the IntelliJ Rust regression is explicitly mentioned in the [Rust 1.70 release blog post](https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html): 

> When `#[test]` functions are compiled, the executable gets a command-line interface from the `test` crate. This CLI has a number of options, including some that are not yet stabilized and require specifying `-Zunstable-options` as well, like many other commands in the Rust toolchain. However, while that's only intended to be allowed in nightly builds, that restriction wasn't active in `test` -- until now. Starting with 1.70.0, stable and beta builds of Rust will no longer allow unstable `test` options, making them truly nightly-only as documented.
**There are known cases where unstable options may have been used without direct user knowledge, especially `--format json` used in IntelliJ Rust and other IDE plugins. Those projects are already adjusting to this change, and the status of JSON output can be followed in its [tracking issue](https://github.com/rust-lang/rust/issues/49359).**

The only known workaround is switching to the Rust nightly toolchain or switching back to the Rust 1.69. You can also track the progress on stabilizing `--format json` in the [tracking issue](https://github.com/rust-lang/rust/issues/49359)

**Comment by Kage-Yami** [comment] 2023-06-03 07:11
> This regression is caused by the recent changes in the Rust test framework released within Rust 1.70, and the regression in IntelliJ Rust is explicitly mentioned in the [Rust 1.70 release blog post](https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html):
> 
> > When `#[test]` functions are compiled, the executable gets a command-line interface from the `test` crate. This CLI has a number of options, including some that are not yet stabilized and require specifying `-Zunstable-options` as well, like many other commands in the Rust toolchain. However, while that's only intended to be allowed in nightly builds, that restriction wasn't active in `test` -- until now. Starting with 1.70.0, stable and beta builds of Rust will no longer allow unstable `test` options, making them truly nightly-only as documented.
> > **There are known cases where unstable options may have been used without direct user knowledge, especially `--format json` used in IntelliJ Rust and other IDE plugins. Those projects are already adjusting to this change, and the status of JSON output can be followed in its [tracking issue](https://github.com/rust-lang/rust/issues/49359).**
> 
> The only known workaround is switching to the Rust nightly toolchain or switching back to the Rust 1.69. You can also track the progress on stabilizing `--format json` in the [tracking issue](https://github.com/rust-lang/rust/issues/49359)

Unfortunately, that "workaround" to switch to the nightly channel on the run configuration (with or without adding the relevant `-Zunstable-options --message-format=json` part to the run command) does _not_ work on the current version of the IntelliJ Rust plugin (`0.4.195.5408-231` as at the time of writing). I can clearly see the JSON output being printed, but it's still  not using the integrated test runner.

**Comment by vlad20012** [comment] 2023-06-03 14:15
@Kage-Yami The Rust plugin figures out the toolchain version during the Cargo project model loading, which happens during the IDE startup, and then can be performed manually, usually after some changes in `Cargo.toml` files. Unfortunately, project model refresh is not suggested after changing `rustup default`, but you can always invoke it manually using `Refresh Cargo Projects` action that you can find in the Cargo tool window (at the right-hand side of the IDE frame) 
![image](https://github.com/intellij-rust/intellij-rust/assets/3221931/bb06674e-1268-4803-8a1c-313a84c22a0c)

**Comment by david-monroe** [comment] 2023-06-05 14:20
This remains working if you set RUSTC_BOOTSTRAP=1. Could you add this as an additional condition besides the version check?

**Comment by david-monroe** [comment] 2023-06-05 14:42
In the meantime you can work around this by renaming ~/.cargo/bin/rustc to real-rustc and adding the following shell script in its place:

```bash
#!/bin/bash

function rustc() {
    exec -a rustc "~/.cargo/bin/real-rustc" "$@"
}

if [[ "$1" = "--version" ]]; then
    (rustc "$@") | sed -E 's/((rustc|release:) [0-9]+\.[0-9]+\.[0-9]+)( |$)/\1-nightly\3/'
else
    rustc "$@"
fi
```

This will make intellij believe that you are always using nightly and then it will show the test window.

**Comment by vlad20012** [comment] 2023-06-05 14:49
I would strongly advise no one to follow @david-monroe solution (with the bash script) because it can break many things in the plugin that depends on the knowledge that the toolchain is stable or nightly

**Comment by david-monroe** [comment] 2023-06-05 14:54
Which things in particular?

**Closed** 2023-06-10 04:18 UTC
Labels: subsystem::tests, subsystem::build & run
