### ISSUE TITLE
Ignoring integer type limits

### ISSUE THREAD

**Issue by Zelaux** [intellij-rust/intellij-rust#10438] opened 2023-05-06 14:27 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.193.5352-231
* **Rust toolchain version:** -
* **IDE name and version:** Intellij idea 2023.1
* **Operating system:** -

## Problem description
The plugin does not take into account the bit depth of integer variables
![image](https://user-images.githubusercontent.com/58040045/236630111-68cd81fa-5bea-4e57-8a8b-7cbbe7c294cf.png)

**Comment by Maksim20023** [comment] 2023-08-28 12:51
Hi! I'm closing this ticket since the problem does not reproduce in the current environment (IntelliJ IDEA 2023.2.1, Rust plugin 0.4.200.5421-232). If this issue still reproduces for you, please reopen the ticket.

**Closed by Maksim20023** 2023-08-28 12:51 UTC
