### ISSUE TITLE
If using lazy_ Static macro, its method cannot be called intelligently

### ISSUE THREAD

**Issue by ansel-peng** [intellij-rust/intellij-rust#9496] opened 2022-10-10 10:00 UTC
## Environment

* **IntelliJ Rust plugin version:**  0.4.179.4903-222
* **Rust toolchain version:** 1.64.0
* **IDE name and version:**  CLion 2022.2.3
* **Operating system:** MacOS

## Problem description

If I use lazy_ static macro, its method cannot be called intelligently.The program can be executed normally.
![截屏2022-10-10 下午5 56 36](https://user-images.githubusercontent.com/78771329/194841015-54a1b730-b541-4b35-b4ba-8fa1d7fc46af.png)

**Comment by dima74** [comment] 2022-10-10 18:31
Duplicate of #8223

**Closed by dima74** 2022-10-10 18:31 UTC
