### ISSUE TITLE
Missing auto-complete and code coloration for some structs and functions

### ISSUE THREAD

**Issue by CLOVIS-AI** [intellij-rust/intellij-rust#8225] opened 2021-12-06 12:00 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.160.4276-213
* **Rust toolchain version:** cargo 1.56.0 (4ed5d137b 2021-10-04)
* **IDE name and version:** IntelliJ IDEA 2021.3 Ultimate Edition (IU-213.5744.223)
* **Operating system:** Linux 5.15.6-arch2-1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

When using Cargo for a Vulkano project, some files don't seem to be indexed by IntelliJ Rust. They do not appear in code completion, are not syntactically colored, and don't have quick documentation (not even the declaration).

## Steps to reproduce

- Repository URL: https://gitlab.com/braindot/quasar.git
- Commit 97af63f30c6b7393bd6eb430eafe7a7c526da6c4

The project compiles and runs fine, however IntelliJ doesn't recognize some symbols.

`Instance::new` is recognized and works perfectly:
![Screenshot_20211206_125436](https://user-images.githubusercontent.com/25709889/144841710-44c956c9-bc44-4909-97c4-93737917d216.png)

`physical_device.properties()` is not recognized (does not appear in code completion, no documentation available, cannot navigate to declaration):
![Screenshot_20211206_125522](https://user-images.githubusercontent.com/25709889/144841786-bbb8b15c-74c1-4921-b182-65ff8bae7cd1.png)

In some parts of the library, some structs are recognized, some aren't (here, `Version` works perfectly well, but `Properties` and `Features` don't, IntelliJ behaves as if those fields didn't exist). To find this struct: in engine.rs:21, navigate to `PhysicalDevice`'s declaration, then navigate to `PhysicalDeviceInfo`'s declaration.
![Screenshot_20211206_125652](https://user-images.githubusercontent.com/25709889/144841968-6b2dc875-0a20-4f42-8f3f-55be269a5792.png)

I currently have not found a logic in whether types are correctly analyzed or not. I have removed the `~/.cargo` folder, restarted IntelliJ, invalidated the caches and rebooted the computer etc multiple times, and it is always the same structs that are not recognized.

**Comment by Undin** [comment] 2021-12-06 19:57
The plugin doesn't properly infer type of `physical_device` [here](https://gitlab.com/braindot/quasar/-/blob/97af63f30c6b7393bd6eb430eafe7a7c526da6c4/src/engine.rs#L21)

![image](https://user-images.githubusercontent.com/2539310/144913271-95458aaa-2f2d-46e3-b588-c69509afc833.png)

As a result, the plugin fails to find the corresponding `impl` block, and navigation and completion don't work as expected

**Comment by sywesk** [comment] 2022-02-27 09:46
The problem is still occuring with the 0.4.165.4438-213 version of the plugin.

Being relatively new to rust, is there any way we can help with this problem ?

**Comment by Undin** [comment] 2022-05-12 21:52
Works with 0.4.169.4584-221

It looks like it was fixed by #8726

**Closed by Undin** 2022-05-12 21:52 UTC
Labels: subsystem::type inference & name resolution, bug
