### ISSUE TITLE
PluginClassLoader: Rust references via parent Toml that must be unloaded

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#7097] opened 2021-04-12 12:51 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.142.3705-211
* **Rust toolchain version:**
* **IDE name and version:** CLion 2021.1
* **Operating system:** OS Mac OS X(x86_64) v11.2.3

## Problem description

A lot of java.lang.Throwable: PluginClassLoader exceptions. Unfortunately there is no repro.
```
java.lang.Throwable: PluginClassLoader(plugin=PluginDescriptor(name=Rust, id=org.rust.lang, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/CLion2021.1/plugins/intellij-rust, version=0.3.142.3705-211, package=null), packagePrefix=null, instanceId=79, state=active) references via parents PluginClassLoader(plugin=PluginDescriptor(name=Toml, id=org.toml.lang, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/CLion2021.1/plugins/intellij-toml, version=0.2.142.3705-211, package=null), packagePrefix=null, instanceId=54, state=unload in progress) that must be unloaded
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.ide.plugins.ClassLoaderTreeChecker.checkThatClassloaderNotReferenced(ClassLoaderTreeChecker.kt:44)
	at com.intellij.ide.plugins.ClassLoaderTreeChecker.checkThatClassLoaderNotReferencedByPluginClassLoader(ClassLoaderTreeChecker.kt:21)
	at com.intellij.ide.plugins.ClassLoaderTreeChecker.checkThatClassLoaderNotReferencedByPluginClassLoader(ClassLoaderTreeChecker.kt:23)
	at com.intellij.ide.plugins.ClassLoaderTreeChecker.checkThatClassLoaderNotReferencedByPluginClassLoader(ClassLoaderTreeChecker.kt:17)
	at com.intellij.ide.plugins.DynamicPlugins.unloadPlugin(DynamicPlugins.kt:559)
	at com.intellij.ide.plugins.PluginInstaller.uninstallDynamicPlugin(PluginInstaller.java:125)
	at com.intellij.ide.plugins.newui.MyPluginModel.apply(MyPluginModel.java:155)
	at com.intellij.ide.plugins.newui.MyPluginModel.runRestartButton(MyPluginModel.java:977)
	at com.intellij.ide.plugins.newui.RestartButton.lambda$new$0(RestartButton.java:13)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by Undin** [comment] 2022-04-18 08:37
@intellij-rust/qa Could you try to reproduce it? If it cannot be reproduced, let's close it

**Comment by mili-l** [comment] 2022-04-26 15:38
Cannot reproduce
CLion 2022.1  Build #CL-221.5080.224
IntelliJ IDEA 2022.1 (Ultimate Edition) Build #IU-221.5080.210
Rust version: 0.4.170.4585-221-nightly

**Closed by mili-l** 2022-04-26 15:38 UTC
Labels: bug, subsystem::IDE
