### ISSUE TITLE
No autocomplete for trait extension implemented for type aliases

### ISSUE THREAD

**Issue by asv1** [intellij-rust/intellij-rust#3708] opened 2019-04-14 07:01 UTC
## Environment

* **Intellij-Rust plugin version:**
0.2.96-2122-191
* **Rust toolchain version:**
1.34.0
* **IDE name and version:**
PyCharm Community 2019.1
* **Operating system:**
Windows 10 LTSC 1809

## Steps to reproduce
```
fn main() {
    let v = vec![A, A, A];

    v.method(); // doesn't show in autocomplete
}

type VectorsA = Vec<A>;

struct A;

trait VecExt {
    fn method(&self);
}

// if modify to Vec<A> than ok
impl VecExt for VectorsA {
    fn method(&self) {
        unimplemented!()
    }
}

```

**Comment by mchernyavsky** [comment] 2019-04-14 07:58
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/2778.

**Closed by mchernyavsky** 2019-04-14 07:58 UTC
Labels: bug, duplicate, type inference & resolve
