### ISSUE TITLE
'Variable is never used' for implicit named arguments

### ISSUE THREAD

**Issue by danmysak** [intellij-rust/intellij-rust#8539] opened 2022-02-10 10:32 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.164.4409-213
* **Rust toolchain version:** 1.58.1 (db9d1b20b 2022-01-20) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.3.3 (CL-213.6777.58)
* **Operating system:** macOS 12.1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

The 'Variable is never used' warning is wrongly displayed when a variable is only used as an implicit named argument.

## Steps to reproduce

```rust
fn main() {
    let lang = "rust";
    println!("{lang}");
}
```

**Comment by Kobzol** [comment] 2022-02-10 18:15
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/8417.

**Closed by Kobzol** 2022-02-10 18:15 UTC
