### ISSUE TITLE
Autocomplete Fails on SmallVec When SmallVec and smallvec! Are Both In Scope

### ISSUE THREAD

**Issue by cwfitzgerald** [intellij-rust/intellij-rust#4500] opened 2019-10-06 05:36 UTC
## Environment

* **IntelliJ Rust plugin version:**
`0.2.106.2135-192`
* **Rust toolchain version:**
`stable-1.37`
* **IDE name and version:**
`CLion 2019.2 Build #CL-192.5728.100, built on July 23, 2019`
* **Operating system:**
`Xbuntu 18.04`
uname:
`Linux connor-laptop 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
## Problem description

With both `smallvec::SmallVec` struct and `smallvec::smallvec` macro in scope, autocomplete/go to definition breaks for the struct. This happens no matter what macro engine is enabled, or with either disabled.

Edit: A valid workaround appears to be having the `use` statement of the macro be in an inner scope, like function local. Example added to repo.

## Steps to reproduce

Example repo: https://github.com/cwfitzgerald/intellij-rust-bug-0. Open to `main.rs`, see it fail. Open `works.rs` see it work.

Edit: Example used stable.

**Comment by Undin** [comment] 2019-10-10 17:48
Thanks for the report and example!
It seems `use crate_name::crate_name` import breaks name resolution.
Duplicate of #4509

**Closed by Undin** 2019-10-10 17:48 UTC
Labels: bug, type inference & resolve
