### ISSUE TITLE
Chained tuple indexing syntax is unsupported

### ISSUE THREAD

**Issue by JarvisCraft** [intellij-rust/intellij-rust#6174] opened 2020-09-28 23:41 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.131.3366-201
* **Rust toolchain version:** 1.46.0
* **IDE name and version:** CLion 2020.1.3
* **Operating system:** Ubuntu 20.04.1 LTS

## Problem description
Rust 1.46.0 has brought better syntax for tuple indexing, i.e. it allows chaining of indexes without explicit delimiters.
For example for `x` being a tuple `x.0.0` is now valid syntax for what used to be possible only via `(x.0).0` or `x.0 .0`. However, the plugin seems to be unaware of this syntax thus displaying errors on such statements.

## Steps to reproduce
1. Write any expression which uses tuple indexing syntax without spaces such as:
```rust
fn foo(x: ((i32), (i32))) -> i32 {
    x.0.0
}
```
2. Indexing expression will be treated as invalid and the variable will be considered unused:
![image](https://user-images.githubusercontent.com/7693005/94496388-e9278600-01fc-11eb-8843-94f538cbc8eb.png)

## Real-life example 
![image](https://user-images.githubusercontent.com/7693005/94495845-7c5fbc00-01fb-11eb-8938-fee76aebac92.png)

**Comment by Undin** [comment] 2020-09-29 05:40
Duplicate of #6029

**Closed by Undin** 2020-09-29 05:40 UTC
Labels: rust
