### ISSUE TITLE
The semicolon issue

### ISSUE THREAD

**Issue by Biacode** [intellij-rust/intellij-rust#2351] opened 2018-03-06 12:21 UTC
In the example below, the code format shortcut generates infinite `;` - semicolon.

```rust
extern crate rand;

use rand::Rng;
use std::cmp::Ordering;
use std::io;

fn main() {
    println!("Guess the number!");

    let secret_number = rand::thread_rng().gen_range(1, 101);

    loop {
        println!("Please input your guess.");
        let mut guess = String::new();
        io::stdin().read_line(&mut guess).expect("Failed to read line");
        let guess: u32 = match guess.trim().parse() {
            Ok(num) => num,
            Err(_) => continue; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;; ; ;
        };
        println!("You guessed: {}", guess);
        match guess.cmp(&secret_number) {
            Ordering::Less => println!("Too small!"),
            Ordering::Greater => println!("Too big!"),
            Ordering::Equal => {
                println!("You win!");
                break;
            }
        }
    }
}
```

**Comment by Undin** [comment] 2018-03-06 13:02
Duplicate of #2339

**Closed by Undin** 2018-03-06 13:02 UTC
