### ISSUE TITLE
IDE removes contents of the file on save with rustfmt enabled

### ISSUE THREAD

**Issue by nazar-pc** [intellij-rust/intellij-rust#8913] opened 2022-06-08 01:21 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.171.4656-222
* **Rust toolchain version:** 1.63.0-nightly (42e1761c7 2022-05-15) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2022.2 EAP Ultimate Edition (IU-222.2889.14)
* **Operating system:** Linux 5.17.6-xanmod1-x64v2
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
When saving https://github.com/subspace/subspace/blob/93bfaa3f8ebe2973c4939e6be21caffff9e57933/orml/vesting/src/weights.rs with "Run rustfmt on save" IDE removes contents of the whole file

## Steps to reproduce
1. Clone https://github.com/subspace/subspace
2. Checkout commit 93bfaa3f8ebe2973c4939e6be21caffff9e57933
3. Edit `orml/vesting/src/weights.rs` (add whitespace or whatever)
4. Save file
5. Observe file becoming empty ⁉️

I didn't bother checking if it is reproducible standalone, but you have the code, so feel free to experiment.

**Comment by LoganDark** [comment] 2022-06-12 21:22
Duplicate of #8846

**Closed** 2022-09-19 14:47 UTC
Labels: subsystem::tools::rustfmt
