### ISSUE TITLE
Information Extraction of testing is incorrect

### ISSUE THREAD

**Issue by ifsheldon** [intellij-rust/intellij-rust#4219] opened 2019-08-03 16:00 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.102.2130-192
* **Rust toolchain version:** 1.36
* **IDE name and version:** Clion
* **Operating system:** Windows

## Problem description
When using assert_eq! like assert_eq!(1,2), the test should fail and it will show a message "Expected: 2
Actual: 1" which is weird because Rust doesn't care which value is Expected or Actual.

If we run tests in command line directly using cargo test, the message given will be "thread 'test::case_test' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`"

## Steps to reproduce
Just try testing in the IDE using assertions like assert_eq!(1,2)

**Comment by mchernyavsky** [comment] 2019-08-03 16:04
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/3814

**Closed by mchernyavsky** 2019-08-03 16:04 UTC
Labels: duplicate, tests
