### ISSUE TITLE
Plugin cannot infer code that compiles

### ISSUE THREAD

**Issue by KanbeKotoriDaisuki** [intellij-rust/intellij-rust#9040] opened 2022-07-11 05:35 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.173.4714-221
* **Rust toolchain version:** 1.60.0-nightly
* **IDE name and version:** CLion 2022.1.3
* **Operating system:** WSL

## Problem description

The plugin fails to infer the type of function return type and throws E0308 error for a code that compiles properly.

## Steps to reproduce

```rust
fn route_map<'a, G: Html>(
  cx: Scope<'a>,
  route: &'a ReadSignal<Routes>,
) -> View<G> {
  let memo = create_memo(
    cx,
    on([route], move || match route.get().as_ref() {
      Routes::Home => t("home"),
      /// Branches
      Routes::NotFound => t("error"),
    }),
  );
  (*memo.get()).clone()
}
```

where `create_memo`, `on`, and `t` has type signature (from sycamore-rs/sycamore)

```rust
pub fn create_memo<'a, U: 'a>(
  cx: Scope<'a>, 
  f: impl FnMut() -> U + 'a
) -> &'a ReadSignal<U>
```
```rust
pub fn on<'a, U, const N: usize>(
  dependencies: [&'a (dyn AnyReadSignal<'a> + 'a); N], 
  mut f: impl FnMut() -> U + 'a
) -> impl FnMut() -> U + 'a
```
```rust
pub fn t<G: GenericNode>(t: impl AsRef<str>) -> View<G>
```

and ```Html``` trait extends trait ```GenericNode```.

**Comment by Maksim20023** [comment] 2023-07-28 16:57
Hi! I’m closing this ticket because the issue does not reproduce in the current environment (CLion 2023.2 Build #CL-232.8660.186, Rust plugin 0.4.199.5415-232). If this issue still reproduces for you, please reopen the ticket.

**Closed by Maksim20023** 2023-07-28 16:57 UTC
