### ISSUE TITLE
Pattern matching LHS checker bad bad

### ISSUE THREAD

**Issue by ice1000** [intellij-rust/intellij-rust#4349] opened 2019-09-04 00:47 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.2.105.2728-192-nightly
* **Rust toolchain version:** 1.37.0 (eae3437df 2019-08-13) x86_64-pc-windows-msvc
* **IDE name and version:** CL-192.6262.62
* **Operating system:** Windows 10 10.0

## Problem description

![image](https://user-images.githubusercontent.com/16398479/64217513-b8570f00-ce8b-11e9-8216-4db647e5fd15.png)

This function should compile but intellij rust is too silly to realize that.

Code for copy&paste:

```rust
fn test() {
    let a = &Some(1);
    let b = &Some(1);
    match (a, b) {
        (None(..), None(..)) => (),
        (Some(..), Some(..)) => (),
        (Some(..), _) | (_, Some(..)) => (),
    }
}
```

## Fun fact

Removing `&` which makes `a` and `b` not references suppresses the error hint.

**Comment by ortem** [comment] 2020-09-04 14:00
Looks like it was fixed some time ago

**Comment by ortem** [comment] 2020-09-04 14:08
Oh, sorry, it'll be fixed by https://github.com/intellij-rust/intellij-rust/pull/5720

**Comment by ortem** [comment] 2020-09-08 11:48
@Undin I've reproduced it on this code with `_` instead of `..`:

```Rust
fn test() {
    let a = &Some(1);
    let b = &Some(1);
    match (a, b) {
        (None, None) => (),
        (Some(_), Some(_)) => (),
        (Some(_), _) | (_, Some(_)) => (),
    }
}
```

**Closed** 2020-09-11 12:41 UTC
Labels: bug, subsystem::code insight
