### ISSUE TITLE
Code autocompletion not working for crates using C libraries

### ISSUE THREAD

**Issue by wulkanat** [intellij-rust/intellij-rust#3257] opened 2019-01-16 22:37 UTC
## Environment

* **Intellij-Rust plugin version:** v0.2.0.2114-183
* **Rust toolchain version:** 1.31.1
* **IDE name and version:** IntelliJ IDEA 2018.3.1 (Community Edition)
Build #IC-183.4588.61, built on December 4, 2018
* **Operating system:** Windows 10 Build 17763.253

## Problem description
Code autocompletion and suggestions don't work with certain external crates or some functions in them. Code still compiles and shows no errors in the editor.

**Suspected cause:** External crates use C libraries. Only functions referring to them are not shown.

In my case that is the crates 'gl' 0.10.0 and 'openvr' 0.5.2
OpenGL crate shows no suggestions at all.
OpenVR only shows some.

**Comment by FelixBrakel** [comment] 2019-03-11 18:12
Same issue here. Possibly it is because of the include statement in the lib.rs which includes a file generated by build.rs?

**Comment by Undin** [comment] 2019-03-11 22:29
@FelixBrakel Yep, exactly
We will try to support such generated code after releasing of new macro expansion engine (see #3015)

**Comment by Seeker14491** [comment] 2019-05-08 18:18
Should this be closed in favor of #1908?

**Comment by Undin** [comment] 2019-10-25 12:23
Should be fixed by #4542

**Closed by Undin** 2019-10-25 12:23 UTC
Labels: bug, code insight, macros

**Comment by Salmondx** [comment] 2020-09-09 19:27
I still can reproduce this issue with `gl` crate for OpenGL. Autocomplete doesn't work, project compiles and runs without any problems.

Clion 2020.2.1, Rust plugin: 0.3.130.3337-202.

![image](https://user-images.githubusercontent.com/9963444/92644094-a3c80680-f297-11ea-95c5-6a1d5be15269.png)

**Comment by Mershl** [comment] 2021-01-06 22:47
This still seems to affect crates like `gl`. Just tested on Clion 2020.3.2, Rust plugin: 0.3.138.3572-203.

**Comment by Undin** [comment] 2021-01-07 19:10
@Salmondx @Mershl is it `org.rust.cargo.evaluate.build.scripts` experimental feature is enabled? You can enable it in the corresponding dialog. To open the dialog, just invoke `Help | Find Action` action and type `Experimental features`

**Comment by Mershl** [comment] 2021-01-07 20:09
Thanks for the hint. Activating `org.rust.cargo.evaluate.build.scripts` does indeed show the auto completion nicely for the `gl` crate. Any plans to activate it by default or integrate it in the UI?

**Comment by Undin** [comment] 2021-01-07 20:10
> Thanks for the hint. Activating org.rust.cargo.evaluate.build.scripts does indeed show the auto completion nicely for the gl crate.

Great!

> Any plans to activate it by default or integrate it in the UI?

It's a part of #6104

**Comment by Mershl** [comment] 2021-02-18 23:43
Updated rust+IntelliJ plugin today. Something has broken the org.rust.cargo.evaluate.build.scripts feature working with gl (OpenGL). Checked that the experimental feature is still enabled. Is it possible to install older versions of the plugin to help you bisect?

* **IntelliJ Rust plugin version:** 0.3.141.3674-203
* **Rust toolchain version:** 1.50.0 (cb75ad5db 2021-02-10) x86_64-unknown-linux-gnu

**Comment by Undin** [comment] 2021-02-19 06:26
@Mershl Could you provide logs (`Help | Show logs in %your file manager name%`), please?

**Comment by Mershl** [comment] 2021-07-20 21:23
Sorry, have been on a Rust hiatus for some time. Tested it just now with the latest plugin version and the issue is no longer reproduciable. Thank you.
