### ISSUE TITLE
Error dialog JavaDummyHolder

### ISSUE THREAD

**Issue by a1ien** [intellij-rust/intellij-rust#8513] opened 2022-02-04 13:25 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.4.165.4416-213-nightly
* **Rust toolchain version:** 1.58.1
* **IDE name and version:** IDEA 2021.3.2
* **Operating system:** Linux

## Problem description
![image](https://user-images.githubusercontent.com/280794/152535872-b34eac02-fb9d-41fd-a88a-a8d073892333.png)
More strange that is Error dialog and not stack trace in event log

## Steps to reproduce
I did refactor-> move for trait

**Comment by dima74** [comment] 2022-02-15 11:08
@a1ien Thanks for the report! Could you please provide source code, screencast, or something like this? I can't reproduce the issue with simple example

**Comment by a1ien** [comment] 2022-02-15 11:37
Sorry but I also can't reproduce this. It's happened only once. I theory if no one know how this can be happen i thin we can close this.

**Comment by dima74** [comment] 2022-02-15 11:45
I don't know how this could happen unfortunatelly. Let's close the issue for now. Please reopen if you find reproduction or it happens again, we will investigate

**Closed by dima74** 2022-02-15 11:45 UTC
Labels: subsystem::refactoring
