### ISSUE TITLE
Newest clion EAP throwing NoSuchMethodError exceptions

### ISSUE THREAD

**Issue by david-mcgillicuddy-moixa** [intellij-rust/intellij-rust#6271] opened 2020-10-19 13:59 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.132.3395-203
* **Rust toolchain version:** 1.40.0 (73528e339 2019-12-16) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3 EAP (CL-203.4818.55)
* **Operating system:** macOS 10.15.7

## Problem description
Ever since upgrading to the latest clion EAP build, the rust plugin has stopped working. Errors in logs give the stack trace at https://pastebin.com/8gAtnmS5 but very short version is
```
java.lang.NoSuchMethodError: 'void com.intellij.util.containers.ConcurrentWeakKeySoftValueHashMap.<init>(int, float, int, gnu.trove.TObjectHashingStrategy)'
	at org.rust.lang.core.resolve.ref.RsResolveCacheKt$createWeakMap$1.<init>(RsResolveCache.kt:270)
	at org.rust.lang.core.resolve.ref.RsResolveCacheKt.createWeakMap(RsResolveCache.kt:274)
	at org.rust.lang.core.resolve.ref.RsResolveCacheKt.getOrCreateMap(RsResolveCache.kt:264)
	at org.rust.lang.core.resolve.ref.RsResolveCacheKt.access$getOrCreateMap(RsResolveCache.kt:1)
	at org.rust.lang.core.resolve.ref.RsResolveCache.getRustStructureDependentCache(RsResolveCache.kt:57)
	at org.rust.lang.core.resolve.ref.RsResolveCache.getCacheFor(RsResolveCache.kt:151)
	at org.rust.lang.core.resolve.ref.RsResolveCache.resolveWithCaching(RsResolveCache.kt:97)
	at org.rust.lang.core.resolve.ref.RsReferenceCached.cachedMultiResolve(RsReferenceCached.kt:27)
	at org.rust.lang.core.resolve.ref.RsReferenceCached.multiResolve(RsReferenceCached.kt:20)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
```
Clion itself also triggered a bug report, it's 5900591 on their system.

## Steps to reproduce
Upgrade to latest clion EAP, install rust plugin. Persists through rust plugin reinstall. Happens even in fresh hello-world projects.

**Comment by Undin** [comment] 2020-10-19 14:08
Duplicate of #6225
A new stable build with the fix will be landed this week

**Closed by Undin** 2020-10-19 14:08 UTC
Labels: bug, subsystem::IDE
