### ISSUE TITLE
`Implement members` produces invalid code for `Display` trait

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#6661] opened 2021-01-13 15:57 UTC
## Environment

* **IntelliJ Rust plugin version:** 0.3.140.SNAPSHOT-203-dev
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3.1 (CL-203.6682.181)
* **Operating system:** macOS 10.16
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
`Implement members` refactoring/quick-fix does not generate `fmt::Result` import and so produces invalid code on `Display` trait.
![display](https://user-images.githubusercontent.com/4854600/104476350-345d7d00-55d1-11eb-983c-823bd2dc7585.gif)

The implementation is located in `org/rust/ide/refactoring/implementMembers`

## Steps to reproduce

Before:
```Rust
use std::fmt::{Display, Formatter};

struct S { x: i32, y: i32 }

impl Display for S { // Invoke "Implement members" quick-fix
}

fn main() {}
```

After:
```Rust
use std::fmt::{Display, Formatter};

struct S { x: i32, y: i32 }

impl Display for S {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result { // should be `fmt::Result` instead
        unimplemented!()
    }
}

fn main() {}
```

**Comment by Undin** [comment] 2021-01-13 16:00
Duplicate of #4979

**Closed by Undin** 2021-01-13 16:00 UTC
Labels: bug, subsystem::code insight, subsystem::refactoring
