### ISSUE TITLE
Plugin doesn't understand conditional symbols

### ISSUE THREAD

**Issue by xahon** [intellij-rust/intellij-rust#4159] opened 2019-07-18 13:08 UTC
## Environment

* **IntelliJ Rust plugin version:** v0.2.101.2129-191
* **Rust toolchain version:** 1.38.0 nightly-x86_64-unknown-linux-gnu
* **IDE name and version:** 
IntelliJ IDEA 2019.1.3 (Community Edition)
Build #IC-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-25-generic

* **Operating system:** Ubuntu 18.10

## Problem description
```rust
#[cfg(windows)]
use gfx_backend_dx12 as backend;
#[cfg(target_os = "macos")]
use gfx_backend_metal as backend;
#[cfg(all(unix, not(target_os = "macos")))]
use gfx_backend_vulkan as backend;
...
let instance = backend::Instance::create("Part 00: Triangle", 1);
                                |
                                | 
                                V
```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![image](https://user-images.githubusercontent.com/18731681/61459468-1e590700-a9b0-11e9-88a4-1a70149056bf.png)

however vscode's plugin can  
![image](https://user-images.githubusercontent.com/18731681/61459720-b5be5a00-a9b0-11e9-9c7b-4ea8a56176f8.png)

---
_struct `Instance` is defined in each module (from `use`) with different signatures_

**Comment by Undin** [comment] 2019-07-18 16:08
Duplicate of #1191

**Closed by Undin** 2019-07-18 16:08 UTC
Labels: cfg

**Comment by Undin** [comment] 2019-10-15 07:22
@xahon we decided to split cfg attributes support into parts and now the plugin has initial support of cfg attributes.
The current set of supported cfg options is quite small (full set can be found in #4488) but it includes `windows` and `target_os` so it should fix your issue.
At this moment, you can enable this feature manually via `Help | Find Action | Experimental Features | org.rust.lang.cfg.attributes` option with latest plugin version. Also, it will be enabled by default in next release (approximately next week)
Could you please try it and share your feedback? It will help us to polish this feature
