### ISSUE TITLE
Gutter icon doesn't create test command

### ISSUE THREAD

**Issue by la10736** [intellij-rust/intellij-rust#1964] opened 2017-11-02 09:09 UTC
Start by a new bin project and click on run gutter icon. Now create a new test function like

```rust
#[test]
fn fail() {
    assert!(false)
}
```
and click on gutter icon to run the test but it will run just `cargo run` old command a don't create a new one.

This scenario also occurs for test modules and test function in test modules.

**Comment by mchernyavsky** [comment] 2018-10-12 13:58
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/1252.

**Closed by mchernyavsky** 2018-10-12 13:58 UTC
Labels: bug, tests
